### ISSUE TITLE
Provide possibility to ignore filters on null value

### ISSUE THREAD

**Issue by Propaganistas** [spatie/laravel-query-builder#104]
```php
'filter' => [
    'name' => 'John',
    'email' => null,
]
```

Current behavior: searching for models with (partial) name "John" AND an empty email address.
Expected behavior: searching for models with (partial) name "John". Email address doesn't matter since it isn't being filtered.

Or at least some option should be provided to ignore `null`...

**Comment by michgeek** [comment]
If you don't want to do the manual filtering you can put it in a middleware wherever needed

```php
class RemoveParametersWithEmptyValueFromQueryString {

    public function handle($request, Closure $next)
    {
        $request->query->replace(array_filter($request->query->all(), 'mb_strlen'));
        return $next($request);
    }

}
```

**Comment by michgeek** [comment]
If you don't want to manually filter everywhere you can put it in a middleware. Since filters are only 1 level deep you can loop on the first level. If you need to filter more deeply see the second solution

Solution 1: only first level

```php
class RemoveParametersWithEmptyValueFromQueryString {

  /**
   * Remove parameters with empty value from query string
   *
   * @param $request
   * @param Closure $next
   *
   * @return mixed
   */
  public function handle($request, Closure $next) {
    $query = $request->query->all();

    foreach($query as $key => $values) {
      $query[$key] = array_filter($values, 'strlen');

      if(empty($query[$key])) {
        unset($query[$key]);
      }
    }

    $request->query->replace($query);

    return $next($request);
  }
}
```

Solution 2: deeply nested filters

```php
class RemoveParametersWithEmptyValueFromQueryString {

  /**
   * Remove parameters with empty value from query string
   *
   * @param $request
   * @param Closure $next
   *
   * @return mixed
   */
  public function handle($request, Closure $next) {
    $query = $request->query->all();
    $request->query->replace($this->remove_empty_parameters($query));

    return $next($request);
  }

  /**
   * Remove empty parameters
   *
   * @param $array
   *
   * @return mixed
   */
  public function remove_empty_parameters($array) {
    foreach ($array as $key => &$value) {
      if (is_array($value)) {
        $value = $this->remove_empty_parameters($value);

        if (!sizeof($value)) {
          unset($array[$key]);
        }
      } elseif (!strlen($value)) {
        unset($array[$key]);
      }
    }

    return $array;
  }

}
```

**Comment by hulkur** [comment]
Looked into it. Your option is to extend QueryBuilder and override `addFiltersToQuery` which gets collection and you can call `filter` on it.

**Comment by Propaganistas** [comment]
> Looked into it. Your option is to extend QueryBuilder and override `addFiltersToQuery` which gets collection and you can call `filter` on it.

This does not elegantly cover the situation where a GET form holds a combination of "ignorable" filters and "always-on".

**Comment by hulkur** [comment]
Yes. You just have to build your business logic regarding filters into extended class.

**Comment by michgeek** [comment]
What about a callback that determine if the parameter is optional. Example:

```php
QueryBuilder::for(User::class)
    ->allowedFilters([
        'name',
        Filter::exact('email', function($request) { return $request->filled('name'); }),
    ])
    ->get();
```

**Comment by Propaganistas** [comment]
@michgeek That would be a valid solution indeed, and accommodates to my request:

> Or at least some option should be provided to ignore null...

 Perhaps the second parameter could be extend to accept a closure or a castable boolean?

@AlexVanderbist : pinging you into the discussion.

**Comment by AlexVanderbist** [comment]
Sorry to leave you guys waiting. Here's a couple of thoughts:
- `?filter[name]=` should always be parsed a filter with an empty string as value `''`
- `?filter[name]=null` should probably be parsed as a filter with value `null` (_not_ a string - this is an exception)
- an optional filter should be left out at the front-end - however, I understand that leaving these out at the front-end is not always an option

As a solution for now you can always create a custom filter that leaves out empty (`''`) filters. 

In the future we can maybe support something like this?
```php
QueryBuilder::for(User::class)
    ->allowedFilters([
        'name',
        Filter::exact('email')->default(null), // when the filter value is empty, default to `null`
    ])
    ->get();
```
Any thoughts?

**Comment by michgeek** [comment]
I think `?filter[name]=null` should not be parsed as `null`. 

There's a legitimate use case and need to be able to do a partial match with someone called `"Nullable"` or `"Nullification"`. the `->default(null)` looks great to me.

**Comment by Propaganistas** [comment]
> I think `?filter[name]=null` should not be parsed as `null`.
> 
> There's a legitimate use case and need to be able to do a partial match with someone called `"Nullable"` or `"Nullification"`. the `->default(null)` looks great to me.

Agreed.

The `->default(null)` enhancement is viable. I'd name it `->nullable()` or `->ignorable()` though. When `ConvertEmptyStringsToNull` kicks in, the value is already `null`, so now you'd just need to know whether a `null`  filter should be ignored.

Or perhaps `->ignore(null, '-1')` to explicitly specify values that should be ignored.

**Comment by Propaganistas** [comment]
Made a quick PR.

**Comment by AlexVanderbist** [comment]
Gonna close this for now, we'll continue this discussion in the above PR :) Thanks guys

**Comment by nickescobedo** [comment]
The ability to set a default would be great if nothing is passed in.
