### ISSUE TITLE
ID in included resources are being populated with the pivot table id instead of the actual resource id

### ISSUE THREAD

**Issue by javis** [spatie/laravel-query-builder#111]
somewhere between version "1.9.0" and latest versions this behavior changed. 
In version 1.9.0, if you request a with a included collection of models, the id of these models will be correct, in latest version, it will be filled with the pivot id instead of the original model.

**Comment by ce-brex** [comment]
Ran into a similar issue where pivot attributes were now being returned with models which is new.  Look like the `fix fields option (SELECT * FROM table instead of SELECT table.* FROM table)` change in 1.11 causes it.

**Comment by ce-brex** [comment]
This also causes issues when a model's table and pivot table have fields with the same name and using defaultSort().

In my case, both the model's table and pivot table had `created_at` fields, and I default sort by `-created_at`.  Downgrading to 1.10.4 fixed both issues.

**Comment by ce-brex** [comment]
Chaining `->select('<table>.*')` on the QueryBuilder solves the issue in the latest version, but seems like more of a workaround to me.

**Comment by AlexVanderbist** [comment]
Could this be the same issue as #118? A fix for that one was tagged a couple of minutes ago in 1.11.2. Can you please check if the issue is still there on that version?

**Comment by ce-brex** [comment]
@AlexVanderbist I think that fix may solve this issue as well, I noticed the commit but haven't had time to test it.

**Comment by javis** [comment]
I will test the new version soon

**Comment by ce-brex** [comment]
This got to retesting this, and it seems my issue is still around.  Pivot table fields are being combined with the main table fields and causing them to be overwritten and/or conflict.

**Comment by keepwn** [comment]
The bug still in 1.12.0，i only can using `QueryBuilder::for($user->posts()->select('posts.*')->getQuery())` to temporary fix it.

**Comment by AlexVanderbist** [comment]
Hi guys, can you check if the bug persists in 1.13.0? If it does, please PR a failing test and I'll take a look at it there :) Thanks

**Comment by saeidee** [comment]
Still, I am facing the same problem! :(
