### ISSUE TITLE
[Discussion] Use static instead of self return types to keep autocompletion working when extending the class

### ISSUE THREAD

**Issue by Lelectrolux** [spatie/laravel-query-builder#113]
It's a comfort things but as I don't think it will break anything, and it's a 2 min fix, I might try. And if there was a real reason, I might learn something.

I extended the `QueryBuilder` to add a `getResponse` method that I can chain. I simplify a bit but my point remains :

```php
class MyQueryBuilder extends \Spatie\QueryBuilder\QueryBuilder
{
    public function getResponse()
    {
        return response()->json(
            // If asked to paginate the response
            $this->request->hasAny('limit', 'page')
                ? $this->paginate($this->request->input('limit'))
                : $this->get()
        );
    }
    // ...
}

class ModelController
{
    public function index()
    {
        return MyQueryBuilder::for(Model::class)
            ->defaultSort('id')
            ->allowedSorts('id', 'name')
            ->allowedFilters(Filter::scope('search'))
            ->getResponse(); // PhpStorm says this doesn't exists but the code works.
    }
    // ...
}
```

The only issue is that, as all the `defaultSort`, `allowedSorts`, etc. methods are typehinted to return `self` in code or in PhpDoc, PhpStorm says that the `getResponse` method doesn't exists even though it does (and works).

Using `static` as a return type would allow extension without loosing autocompletion.

For any method, if I `return $this;`, unless the class is `final` where it doesn't matter, I think `static` is a more correct return type than `self`.

Did I miss something  ?

**Comment by freekmurze** [comment]
Feel free to send a PR to update the docblocks
