### ISSUE TITLE
Selecting specific columns not working because allowedFields not exist

### ISSUE THREAD

**Issue by voeurnchy** [spatie/laravel-query-builder#128]
```php
return QueryBuilder::for(User::class)->allowedFields('name')->get();

// get 500 error 
Call to undefined method Illuminate\\Database\\Query\\Builder::allowedFields()
```

- laravel-query-builder v 1.10
- Lumen (5.5.2)

**Comment by AlexVanderbist** [comment]
Hi! The option for `allowedFields` was only added in v1.11! This should work when you upgrade to that version. 

When using this package together with Lumen you might run into other issues. Please read #98 for the basic solutions.
