### ISSUE TITLE
Query builder ignores soft delete scope

### ISSUE THREAD

**Issue by ntzm** [spatie/laravel-query-builder#13]
Potentially all global scopes?

**Comment by AlexVanderbist** [comment]
Good catch, thanks! Fixed this in 1.2.0 :)

**Comment by shabushabu** [comment]
Pretty sure this update just broke my tests. If, for example, you pass in an existing query that removed a global scope, then the query builder adds them all back in again, like so:

```php
QueryBuilder::for(User::withTrashed())
```

**Comment by shabushabu** [comment]
It's easy to refactor and call those global scope methods on the query builder instead of passing them in, but it should either be documented somewhere or you could use the `removedScopes()` method to not add already removed scopes back in again.

**Comment by AlexVanderbist** [comment]
@shabushabu Sorry this broke your tests. I'll look into it right now.

**Comment by AlexVanderbist** [comment]
Turns out this is not as simple as it seems. Looks like we'll manually have to set scopes, eager loaded relationships, local macro's and the `onDelete` callback.

I'm nearly done with a fix on [`fix-scopes-and-other-builder-properties` branch](https://github.com/spatie/laravel-query-builder/tree/fix-scopes-and-other-builder-properties)

**Comment by shabushabu** [comment]
No worries, it's what tests are for ;)

**Comment by MateusFGoncalves** [comment]
Any personal news? I have the same problem

**Comment by dominikb** [comment]
> Any personal news? I have the same problem

What version of this package are you using in your project? In newer versions, there are tests implemented to cover this issue.

If you are using an older version, can you update it and try to reproduce your issue?
