### ISSUE TITLE
Broken morph eager queries

### ISSUE THREAD

**Issue by rainerkent** [spatie/laravel-query-builder#130]
Hi, this solution seems to break the morph eager queries. As it was before it worked correctly for morph relations!

May be some like this could work:

```php
return [$fullRelationName => function ($query) use ($fields) {
    if(!($query instanceOf MorphTo)) {
        $query->select($this->prependFieldsWithTableName($fields, $query->getModel()->getTable()));
    }
}];
```

Or may be I got it all wrong! :(

_Originally posted by @rusowyler in https://github.com/spatie/laravel-query-builder/pull/118#issuecomment-436054718_

**Comment by AlexVanderbist** [comment]
Feel free to PR a failing test for this one - if not I'll get back to this soon

**Comment by rainerkent** [comment]
I'd also like to share my experience with this bug.

I have these three models:

``` php
class User 
{
    public function profile()
    {
        return $this->morphTo();
    }
}

class AdminProfile
{
    public function user()
    {
        return $this->morphOne(User::class, 'profile');
    }
}

class CustomerProfile
{
    public function user()
    {
        return $this->morphOne(User::class, 'profile');
    }
}
```

Controller:
``` php
return QueryBuilder::for(User::class)
    ->allowedIncludes('profile')
    ->get();
```

Now when I request:
`https://localhost:8000/api/users?include=profile`

I get QueryException:
`SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select "users".* from "admin_profiles" where "admin_profiles"."id" in (1))"`

Including reverse (morphOne) relationship works as expected.

For now, I'm using rusowyler's suggestion as a workaround.

**Comment by AlexVanderbist** [comment]
Thanks! Gonna merge the PR and provide a fix :)

**Comment by AlexVanderbist** [comment]
Tagged in 1.13.1
