### ISSUE TITLE
Versions 1.11.*  ignores distinct from model relationship

### ISSUE THREAD

**Issue by masterix21** [spatie/laravel-query-builder#132]
Hi dears,

i have a model with the following relationship:
```php
public function trainers()
{
	return $this->hasManyThrough(User::class, ClassPlanning::class, 'class_id', 'id', 'id', 'user_id')->distinct('user_id');
}
```

If i use the version 1.10.4 distinct works, but with 1.11.* it will be ignored and result contains duplicates.

Any idea to solve?

**Comment by freekmurze** [comment]
Feel free to PR a fix for this.

**Comment by dominikb** [comment]
You could try to use a `groupBy` instead.
```php
public function hasManyNested(): HasManyThrough
{
    return $this->hasManyThrough(NestedRelatedModel::class, RelatedModel::class)->groupBy('nested_related_models.id');
}
```

### Possible explanation
I tried to reproduce your case and found, that the method `distinct()` does not take any arguments, but only adds a __distinct__ clause the the __select__ statement and the query becomes `select distinct "tablename".*` See [Laravel API Doc](https://laravel.com/api/5.7/Illuminate/Database/Query/Builder.html#method_distinct).

Given a table that does not have any unique-constraints, this would work as expected.
If the table `class_plannings` does have an __incremental id__ or __date columns__ that get selected, the distinct clause would not be sufficient.

Using the `groupBy` clause will give you a collection with unique values.

**Comment by AlexVanderbist** [comment]
+1 for using `groupBy` in this case. If `distinct` is still an issue in 1.13.0, please feel free to PR a failing test and I'll take a look at it there :) Thanks
