### ISSUE TITLE
Compatibility with znck/belongs-to-through

### ISSUE THREAD

**Issue by Indemnity83** [spatie/laravel-query-builder#135]
Not sure that this is necessarily a bug, but at the same time I don't know how to work around it. 

The [znck/belongs-to-through](/znck/belongs-to-through) package makes use of a temporary select column in the query in order match deeply linked models together. 

```php
public function addEagerConstraints(array $models)
{
    $this->getQuery()->addSelect([
        $this->getParent()->getQualifiedKeyName().' as '.self::RELATED_THROUGH_KEY,
    ]);
    $this->getQuery()->whereIn($this->getParent()->getQualifiedKeyName(), $this->getKeys($models, $this->localKey));
}
```
[full class here](https://github.com/znck/belongs-to-through/blob/b888044a5a64d2359f6100d1346ea71768b2bab4/src/Relations/BelongsToThrough.php#L159-L166)

However, when using this packages QueryBuilder, the select query is overwritten to match the request (or '*' if the request has no fields). 

https://github.com/spatie/laravel-query-builder/blob/d048ddc577b7dc2d876986999e6143793db7c1a3/src/QueryBuilder.php#L294-L296

This makes it so no eager loaded models can be matched and my relationship returns an empy set. 

Is there a way to work around this that I've just overlooked?

**Comment by staudenmeir** [comment]
I'm the new maintainer of the `belongs-to-through` package.

What does your request look like?

**Comment by AlexVanderbist** [comment]
I'm not sure but I think this has since been fixed.

Feel free to open a new issue or a PR with a failing test if you're still experiencing this issue.
