### ISSUE TITLE
allowedIncludes alias

### ISSUE THREAD

**Issue by Gaia-Nutrition** [spatie/laravel-query-builder#137]
Is there any way I can alias relations within the `allowedIncludes()` function similar to what can already be done with filters?

My problem: I'm using Laravel Nova and need my relations to return all models by default. For my API, I would like to restrict relations. A good example: `/api/category?include=posts` should include only published posts.

Here is the setup:
```php
// Category.php 
class Category extends Model
{
    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function publishedPosts()
    {
        return $this->hasMany('App\Post')->published();
    }
}
```
```php
// Post.php
class Post extends Model
{
    public function scopePublished($query) {
        return $query->whereNotNull('published_at')->where('published_at', '<=', Carbon::now());
    }
}
```
```php
// Inside some ApiController. Responds to /api/categories request
$categories = QueryBuilder::for(Category::class)
            ->allowedIncludes('published-posts')
            ->get();
```
Now I need to query like `/api/categories?include=published-posts`
Obviously, I would much rather like to have `/api/categories?include=posts`.
Has anyone encountered a similar problem? How did you solve it?

**Comment by AlexVanderbist** [comment]
Hi, thanks for the suggestion. I agree that this would be a good addition to the package.

What about something like this? 
```php
$categories = QueryBuilder::for(Category::class)
            ->allowedIncludes([
                // new include, uses `posts` in the request but will load the `publishedPosts` relationship
                'posts' => 'published-posts',
                
                // regular include, same relationship as include name
                'users',
            ])
            ->get();
```

**Comment by dominikb** [comment]
What would be your preferred way to go about alias naming conflicts?
Something like an `AliasNamingConflictException`?

Would we still want to allow for the actual relationship name or only for the alias?

**Comment by Gaia-Nutrition** [comment]
@AlexVanderbist That setup would be great!

**Comment by AlexVanderbist** [comment]
Damnit bot - we'll continue this issue in the PR

**Comment by z-h-z-h** [comment]
@AlexVanderbist any progress?
