### ISSUE TITLE
Add ILike varaint for postgres

### ISSUE THREAD

**Issue by Insolita** [spatie/laravel-query-builder#14]
In mysql "like" is case-insensitive, for postgres ilike is more useful;
or common variant  for any db - "like" compare with LOWER() wrapper for column value and searchable value

**Comment by AlexVanderbist** [comment]
>"like" compare with LOWER() wrapper for column value and searchable value

I think I prefer this approach as it's not too much conditional code based on what db is used. I'll look into this later this weekend :)

**Comment by ibrunotome** [comment]
Hi @AlexVanderbist , first of all, congratulations for this great package. Do you have any idea of when will be released the lowercase search feature?
