### ISSUE TITLE
No relations loaded when building query from relation

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-query-builder#142]
When I use this code I get all `categories` that the `user` has subscribed to, with their posts:

```php
$categories_with_posts = $user->categories()->with('posts')->get();
```
But for some reason when I try to add query builder to this, I only get the categories:

```php
$categories_with_posts = QueryBuilder::for($user->categories()->with('posts')->getQuery())->get();
```
The strange thing is not only the `posts` relation is not eager loaded, I can't even access it in my blade through `{{ $category->posts }}`.

Any ideas?

**Comment by dominikb** [comment]
I tried to replicate the described behavior with a fresh install of Laravel, but could not reproduce the issue.

I've uploaded the models used [here.](https://gist.github.com/dominikb/bd05ae21be6e0f45534569ec87e31765)

Can you elaborate in a little more detail?

**Comment by mokhosh** [comment]
Thanks for taking the time. It should be that simple, shouldn't it? I don't know what I can elaborate more on.
Look at it this way: I'm using the exact same query, in the first attempt I'm simply `get`ing the results which works just fine (returns the categories with posts as expected), and in the second attempt I'm giving the query to `query-builder` but it only returns the categories, and not the posts.

**Comment by dominikb** [comment]
I will upload the project I was using to re-create the bug tomorrow.

Maybe you can try and find steps to reproduce the bug.

What versions of this package an Laravel are you using?

**Comment by mokhosh** [comment]
```json
"laravel/framework": "5.7.*",
"spatie/laravel-query-builder": "^1.12",
```

If this doesn't tell you anything, I will try to reproduce this with the same database but a new laravel installation and get back to you.
