### ISSUE TITLE
Exception thrown on using Filter::scope()

### ISSUE THREAD

**Issue by Konfuze** [spatie/laravel-query-builder#145]
I'm using `"spatie/laravel-query-builder": "^1.12"`

`Argument 1 passed to App\MyModel::scopeSmthBetween() must be an instance of App\Models\Builder, instance of Spatie\QueryBuilder\QueryBuilder given`

Model:
```
public function scopeSmthBetween(Builder $query, $from, $to): Builder
{
    return $query
        ->where('rating', '<=', $to)
        ->where('rating', '>=', $from);
}
```

Controller:
```
$items = QueryBuilder::for(MyModel::class)
    ->allowedFilters([Filter::scope('smth_between')])
    ->get();
```

Request:
`/some/route?filter[smth_between]=1,2`

Looks like [this ticket](https://github.com/spatie/eloquent-sortable/issues/5)

**Comment by pactode** [comment]
@Konfuze Looks like you forgot to import the `Builder` class:

```php
use Illuminate\Database\Eloquent\Builder;
```

**Comment by Konfuze** [comment]
@pactode, thanks for your response. Unfortunately, I'm getting the same error.

Changed method definition to `public function scopeSmthBetween($query, $from, $to)` — now it works correctly, but [README](https://github.com/spatie/laravel-query-builder/blob/master/README.md#scope-filters) contains info about type-hinting

**Comment by freekmurze** [comment]
Looking at your error message I'm thinking the solution proposed by @pactode is the @pactode is the right one. Are you sure you added that import?
