### ISSUE TITLE
Add support for Eloquent models in scope using filters

### ISSUE THREAD

**Issue by thijsw** [spatie/laravel-query-builder#146]
It would be nice when models are automatically retrieved if they are type-hinted in the scope function.

For a URI like **/filter?[user]=1**, the package would retrieve user with ID = 1 and use the model in calling the scope method. When the model is not found, a 404 can be generated.

In Eloquent model:
```php
public function scopeUser(Builder $query, User $user): Builder
{
    return $query->has(/* ... */);
}
```

instead of:
```php
public function scopeUser(Builder $query, $id): Builder
{
    return $query->has(/* ... */);
}
```

**Comment by dominikb** [comment]
I tried to implement this and it was possible without lots of overhead. [See Gist](https://gist.github.com/dominikb/a4340cf33d35bace9e77def9d0e97ee0)

However, I don't know if this would be a case better handled by using a custom filter?

**Comment by AlexVanderbist** [comment]
I think one of my colleagues (@rubenvanassche) implemented this in a client project as well. I'm not sure what his final thoughts were but I'll discuss this with him tomorrow. 

Either way, I wouldn't mind having this in a new, custom filter.

**Comment by AlexVanderbist** [comment]
Only a couple months of delay 🙈 

If someone want to add this to the `ScopeFilter` in a PR with documentation, I'll be happy to merge it.

@dominikb's comment above contains a good starting point. Here's another implementation from a client project we did: https://gist.github.com/AlexVanderbist/043a6065e43eda616148315ef02583c7

**Comment by DaniloBenevides** [comment]
Is anyone working on this issue?

**Comment by michapietsch** [comment]
@thijsw I'd rather not generate a 404. IMO it should return an empty result.

@DaniloBenevides I'd take it on. 😊

**Comment by michapietsch** [comment]
Sorry, just realized the PR by @50bhan.

If he doesn't follow up on this, I'd like to offer my help.

Also, I think there is an issue with primary keys other than ```id``` and the implementation ```is_numeric($value)```. The type hinting is already done and the scope gets an Eloquent model instance, but if we work with the given identifier, we have to accept all options, right?

As mentioned above, I'd also not ```findOrFail```. Anyway, as I see it, a test for this case is missing. But what if we were to allow multiple options like ```filter[user]=1,3```, and user 1 didn't exist, but user 3?

But first I'll wait a bit and leave it to @50bhan.

**Comment by AlexVanderbist** [comment]
Some great ideas, @michapietsch. Let's continue this discussion in the PR :)
