### ISSUE TITLE
Avoid To Include Relations That Are Not Explicitly Requested

### ISSUE THREAD

**Issue by MannikJ** [spatie/laravel-query-builder#148]
### Problem
When using `allowedIncludes` to load the relations together with conditional includes on an eloquent api resource with `whenLoaded`, it might occur that relations are included that are not explicitly requested, because they have been loaded before or implicitly in an accesor function or whatever.

### Some Brainstorming
First step would be to enable to get the includes that have been parsed from the request from other places than the QueryBuilder itself. I guess it would probably make sense to extend the request object with the logic of parsing the requested includes as opposed to doing this in the QueryBuilder. No matter how it will be done, I am sure it would make sense to make this include parsing / eager loading logic  accessible and reusable since it is actually quite elaborate.

If you enable accessibility it will still be quite tricky to implement the actual conditional includes because of the nested relation includes. As far as I understand you cannot tell from within an eloquent resource at which level of the nesting tree the resource will be included.
But you would need that information to check if the path is part of the includes the client sent.  

I'm surprised that apparently no one has ever dealt with this problem before, so I might have overlooked something essential. What do you think?

**Comment by almas1992** [comment]
Are you sure that resource collection like that 

```php
rpublic function toArray($request)
{
    return [
        'id' => $this->id,
        'name' => $this->name,
        'email' => $this->email,
        'posts' => PostResource::collection($this->whenLoaded('posts')),
        'created_at' => $this->created_at,
        'updated_at' => $this->updated_at,
    ];
}
```
not like that

```php
public function toArray($request)
{
    return [
        'id' => $this->id,
        'name' => $this->name,
        'email' => $this->email,
        'posts' => $this->whenLoaded('posts',PostResource::collection($this->posts)),
        'created_at' => $this->created_at,
        'updated_at' => $this->updated_at,
    ];
}

**Comment by almas1992** [comment]
This usage is right 
```php
 return [
      "someRelation" => someResource::collection($this->whenLoaded('someRelation'))
];
```

> However I would want it to only append foo, but not the implicitly loaded relation someRelation

probably you has do like that
```php
 return [
      "someRelation" => $this->whenLoaded('someRelation',someResource::collection($this->someRelation))
];
```
sorry,I really can't express my mean in English freely in-deed 😭

**Comment by dominikb** [comment]
I see where you are trying to get at.

The easiest implementation would be to with the `QueryBuilder::get($columns = ['*'])` method to filter out keys that are not allowed appends, allowed includes or properties of the model itself.

A change like this requires thorough thinking, as this is likely to introduce implicit breaking changes.

For your use case, you could extend the `QueryBuilder::class` and implement a filter that fits your needs.

**Comment by ce-brex** [comment]
From my understanding, you're saying that a relation might be included for some reason in your logic, but unless it's specified in the `include` query parameter, you don't want it to be included in the response?  If so, QueryBuilder adds some macros to the `Request` class that could be useful for this.

```
return [
    $this->mergeWhen($request->includes('someRelation'), function () use ($request) {
        return someResource::collection($this->someRelation)->resolve($request);
    }),
];
```

This isn't tested and may need to be modified to work properly, but the main point is to use the `includes` macro on the `Request` to see if a relation was specified to be included.

**Comment by MannikJ** [comment]
Thank you @ce-brex and @dominikb. I've deviated a bit from the topic, that's why I didn't answer.
When I get back to refactoring our responses I will keep your hints in mind. I guess there really is nothing new needed in that package.
It's a shame that I have overseen the package comes with various request marcros and actually already wrote my own :confused:

**Comment by AlexVanderbist** [comment]
To get back to your original issue: I agree that if an include is not explicitly selected it shouldn't be included in the response. However, the query builder only deals with... building queries - not how the data is returned to the API consumer.

As a solution, I usually go for something like @ce-brex' last comment. 
Just a quick reminder, in v2 of the package these request macros will be replaced by the `QueryBuilderRequest` class - so maybe your own macros will still come in handy.

**Comment by chimit** [comment]
I tried to follow @ce-brex logic:

`User` and `Group` has **Many to Many** relationships.

```php
// Group resource
'users' => $this->when($request->includes('users'), User::collection($this->users)),
```

```php
// User resource
'groups' => $this->when($request->includes('groups'), User::collection($this->groups)),
```

```php
// Group controller
$group = QueryBuilder::for(Group::class, $request)
    ->allowedIncludes(['users', 'users.groups'])
    ->findOrFail($group_id);

$this->authorize('get', $group);

return new GroupResource($group);
```

1. `GET /groups/1?include=users,users.groups` returns only a group with users without the second level include.
2. `GET /groups/1?include=users.groups` doesn't display any includes.

Apparently, a `when` condition should be much smarter. It would be great if this package could handle it for us.

@AlexVanderbist any plans to implement it?

**Comment by MannikJ** [comment]
@chimit @ce-brex @AlexVanderbist 
So how is the status on this? The mentioned function `includes` where you can pass a specific relation to check if it should be included does not exists yet, correct? This is actually what I was missing when opening this issue although I was not that clear about it.
And I think it would make sense for this package to offer something like that.

**Comment by ce-brex** [comment]
@MannikJ The `includes` method is currently a macro on the Request object provided by query builder.

**Comment by MannikJ** [comment]
Is [that](https://github.com/spatie/laravel-query-builder/blob/master/src/QueryBuilderRequest.php#L16) what you mean?
I now about this function, but I am looking for something more elaborated than just splitting the include parameter, because it doesn't really help at deciding which relations to include and especially which to leave out. There is some more processing needed. Nested includes are very complicated to handle. 
I think fractal does this quite well.

**Comment by ce-brex** [comment]
I don't see any other way to know what relations were or weren't requested to be included.  Fractal and Query Builder solve different problems.  Query Builder is just a tool to build queries for retrieving data based on request information.  What you do with that data after it has been retrieved is beyond the package's scope.

**Comment by MannikJ** [comment]
@ce-brex I agree that this feature doesn't necessarily has to be part of this package, nor do I think it's the wrongest place of all.
Fractal in fact is a response formatting framework but it also [parses request parameters](https://github.com/thephpleague/fractal/blob/master/src/Manager.php#L163). Request and response are a tight couple you know? Or at least should be...
In my dreams this stuff would all be part of the native API resources framework without the need of any of those packages (this one included).
I dont't find this feature request too extraordinary and really wonder why not many others have the same demand.

**Comment by ce-brex** [comment]
It parses request parameters so that it can aid you with outputting your data, yes.  I can see why they have included that.  It makes no sense for this package to have that capability.  Your comment was that more processing needs to be done to determine if nested relations should be included or not in the response.  I agree, more processing does need to be done, however that processing should not be handled by this package as, again, it's out of the package's scope.  If you want something to handle that for you, why not dump the simple built in api resources and use fractal for the responses?

I disagree that all this should be part of the native api resources framework, unless it's split off and made an optional package.  That just adds bloat that not everyone needs.  API resources were added to make quick and easy responses, not be an end all replacement.

**Comment by MannikJ** [comment]
We use fractal and api resources, but each has its drawbacks (as always of course). But generally I prefer native solutions over any other third-party package and least in laravel ecosystem where I know everything is well thought out when it finally finds its way into the framework. 
A framework should give you options to solve problems properly without expecting you to reinvent the wheel. Nothing is mandatory and it doesn't really matter if it is a separate package or part of the base framework as long as it's a maintained part of the ecosystem. 
I don't think API resources were added just to only solve the most basic issues. Laravel has always been a framework trying to solve everything for you in a clean familiar style, so why should this be an exception? Also api resources are superior over fractal by design in many ways imho.

But of the same mentioned reasons I can also understand why we don't have a more elaborate solution for this stuff yet. It just takes time to come up with something solid.

But we should stop going in circles here. This is just the best place I can think of to declare my displeasure ;)

**Comment by adjustmentlayer** [comment]
You can utilize Spatie `QueryBuilderRequest` to solve this problem.
It can help you know what includes a user requested. e.g. `$queryBuilderRequest->includes() // ['variants', 'property_values', ...]`. Having known requested relationships, you can 'easily' avoid including relations that are not explicitly requested.

Take a look at the example below
```php
class ProductResource extends JsonResource
{
    public QueryBuilderRequest $queryBuilderRequest;

    public function __construct($resource) {
        parent::__construct($resource);
        $this->queryBuilderRequest = QueryBuilderRequest::fromRequest(app('request'));
    }
    
    public function allowedIncludes(): array {
        // this is a crucial part, this how we know what includes a user requested. e.g. ?include=variants,property_values
        return $this->queryBuilderRequest->includes()->toArray();
    }

    public function resourceMap(): array
    {
        // todo: automatically find resource for the relation, probably it should be found by convention
        return [
            'variants' => fn($data) => VariantResource::collection($data),
            'property_values' => fn($data) => PropertyValueResource::collection($data),
        ];
    }

    public function toArray($request)
    {
        $relations = collect($this->allowedIncludes())->mapWithKeys(
            function($relationName) {
                // we are dealing with 'count' relation, e.g. variantsCount
                if(\Str::endsWith($relationName, $this->countSuffix())) {
                    return [$relationName => $this->whenCounted($relationName)];
                }
                // we are dealing with 'exists' relation, e.g. variantsExists
                if(\Str::endsWith($relationName, $this->existsSuffix())) {
                    $relationMethod = \Str::of($relationName)->substr(0, -1 * strlen($this->existsSuffix()))->toString();
                    return [$relationName => $this->{$relationMethod}()->exists()];
                }
                // we are dealing with a regular relation, e.g. variants
                if(isset($this->resourceMap()[$relationName])) {
                    $resolver = $this->resourceMap()[$relationName];
                    return [$relationName => $resolver($this->whenLoaded($relationName))];
                }
                return [$relationName => $this->whenLoaded($relationName)];
            },
        );
        
        return array_merge(
            ['id' => $this->id, 'title' => $this->title],
            $relations->toArray(),
        );
    }
    
    public function countSuffix() {
        return config("query-builder.count_suffix");
    }

    public function existsSuffix() {
        return config("query-builder.exists_suffix");
    }
}
```
