### ISSUE TITLE
Boolean type filter ignored in 1.13.0

### ISSUE THREAD

**Issue by cioraneanu** [spatie/laravel-query-builder#153]
After updating to the recent version 1.13.0 I can no longer properly filter using boolean values. For example if I allow this filter:
`Filter::exact('is_visible'),`

This request:
`GET https://...api.../resource?filter[is_visible]=true` -> shows all visible resources

`GET https://...api.../resource?filter[is_visible]=false` -> ignores filter. Shows both visible and non visible

**Comment by Lydnasty** [comment]
The problem is in Spatie\QueryBuilder\Filter.php line 41
` if (empty($valueToFilter)) {
            return;
        }`
when the value is 0 or false, **_empty()_** returns true, so the filter is not applied.

**Comment by AlexVanderbist** [comment]
Thanks for reporting this! @dominikb PR'd a good fix that I'll tag as 1.13.1 later today :)
