### ISSUE TITLE
Loading relation restricted by relation value

### ISSUE THREAD

**Issue by lukecurtis93** [spatie/laravel-query-builder#159]
Is there a way with this package to achieve something like the following:

```
return QueryBuilder::for(Post::class)
        ->allowedIncludes(['media', 'user])
```
But lets say I want to load only the `images` collection on media (I'm using spatie media library), so i'd use a custom scope, like
```
return $query->whereHas('media', function (Builder $query) use ($value) {
            $query->where('collection_name', $value);
        });
```

However this will exclude results that don't have an images media collection which is not what i need

What if i want to load all my posts, but only include media that is of the collection type `image`?

Sorry if this has already been documented/answered, I just couldn't find the appropriate use case

**Comment by AlexVanderbist** [comment]
Hi!

For this particular use case I think I would create a new `images` relation on the `Post` model that only loads said `Media` items. Maybe something like this:

```php
public function images()
    {
        return $this->media()->where('collection_name', 'images');
    }
``` 

You can then include and request the `images` include from the query builder.

Hopefully this solves your issue?

**Comment by lukecurtis93** [comment]
Yeah thanks Alex that's perfect :)
