### ISSUE TITLE
Multiple default sorts?

### ISSUE THREAD

**Issue by matthew-inamdar** [spatie/laravel-query-builder#169]
Although you can provide multiple fields to sort by via the query string:

```
...?sort=first_name,last_name
```

It seems as if there is no way to provide multiple fields as the default sort. It only seems to support a single property:

```php
// ❌
QueryBuilder::for($baseQuery)
    ->defaultSort('first_name,last_name')
    ->allowedSorts('first_name', 'last_name');

// ❌
QueryBuilder::for($baseQuery)
    ->defaultSort('first_name', 'last_name')
    ->allowedSorts('first_name', 'last_name');

// ❌
QueryBuilder::for($baseQuery)
    ->defaultSort(['first_name', 'last_name'])
    ->allowedSorts('first_name', 'last_name');

// ✅
QueryBuilder::for($baseQuery)
    ->defaultSort('first_name')
    ->allowedSorts('first_name', 'last_name');
```

Can you confirm if this is the case? If so, I'm happy to go and open a PR to add this ability - I just want to check before I spend time doing so!

Cheers,
Matt

**Comment by dominikb** [comment]
Hi Matt!

You're right on this one. The default sort on the `QueryBuilder` currently takes either a property name that gets converted into a `SortsField` object or an object implementing the `Sort` interface.

Currently, the only way to achieve this behaviour, is to create a specific custom Sort:

```php
class MultipleColumnSort implements Sort
{
    public function __invoke(Builder $query, $descending, string $properties) : Builder
    {
        foreach(str_split(',', $properties) as $property) {
            $query->orderBy($property, $descending ? 'desc' : 'asc');
        }
        
        return $query;
    }
}
```

Personally I think it would be great if default sorting would allow for the same syntax as adding new allowed sorts does.

**Comment by matthew-inamdar** [comment]
Thanks @dominikb - I thought that was the case. I'll get a PR ready over the next few days to add this ability!

**Comment by matthew-inamdar** [comment]
There's now a PR open to add this functionality.
