### ISSUE TITLE
Binary gets converted to array

### ISSUE THREAD

**Issue by crashkonijn** [spatie/laravel-query-builder#170]
Hi there,

First of all, thanks for providing this package. It's essential to all of our projects!

Today we ran into a very strange bug where in certain conditions the filter wouldn't work, after some debugging we found that in certain cases a binary could be transformed to an array by [this piece of code](https://github.com/spatie/laravel-query-builder/blob/master/src/QueryBuilderServiceProvider.php#L70) which would result in in a binary with a , in it getting split.

```
array:2 [▼
  0 => b"\x11é$~EàÙ"
  1 => b"¼`ú\x16>~öó"
]
````
We fixed this issue by creating a copy of the filters macro and adding the following before the is_array check.
```PHP
try {
    if (Uuid::fromBytes($value)) {
        return $value;
    }
} catch (\Exception $e) {}
```
If you're willing to add Ramsey\Uuid\Uuid as a dependency to this package or have a better idea to check for a binary I'd be happy to create a PR.

If not, hopefully this will help someone someday :)

Cheers!

**Comment by dominikb** [comment]
Hey crashkonijn,

thanks for providing feedback.

One solution, as you pointed out, would be to add the dependency and the check you implemented.

Another way I could think of tackling this, without limiting to a specific binary implementation, would be to specify a set of characters (maybe a regex) that gets checked before splitting.
This, however, could still fail its purpose in certain edge cases and introduce some assumptions on the filter clauses, we don't want to make.

In my opinion the best way to handle this would be to add a disclaimer in the documentation and link to this issue for future reference.

**Comment by AlexVanderbist** [comment]
Hi! I'm afraid I agree with @dominikb - this is too much of an edge case to include a new dependency. Adding the uuid dependency wont fix all problems with binary strings as filters either... In this case I think overwriting the filters macro is probably the best solution.

Feel free to PR an update to the `filters` macro if there's a good way to detect binary data (as opposed to random characters containing a comma).
