### ISSUE TITLE
Unexpected behavior when using getQuery() method to apply filters on a base query that returns a Relation instance instead of Builder

### ISSUE THREAD

**Issue by lilisgeorge** [spatie/laravel-query-builder#171]
I have following tables on my database

users (id,name,...)
accounts (id,name,...)
memberships (id,user_id,account_id)
campaigns (id,name,account_id,...)

and I have defined a relation on Users model for returning all campaigns from accounts where the user is member at, like so:

```
public function campaigns()
{
    return $this->hasManyThrough(
        \App\Models\Campaign::class,
        \App\Models\Membership::class,
        'user_id',
        'account_id',
        'id',
        'account_id',
    );
}
```

I then have defined an index method on my controller to return a paginated list of user campaigns, like so:

```
public function index()
{
    $campaigns = auth()->user()
        ->campaigns()
        ->paginate();

    return new CampaignCollection($campaigns);
}
```

The resulting sql query (using toSql() method was)
```
select *
from `campaigns`
inner join `memberships` on `memberships`.`account_id` = `campaigns`.`account_id`
where `memberships`.`user_id` = ?
```

The above method returned a paginated list of the following format

```
[
    'data' => [
        [
            'id' => '...', // Campaigns id,
            'name' => '...', // Campaigns name,
            // ...
        ],
        // ...
    ],
    // ...
]
```

Some days later, I decided to implement a filter feature for this endpoint so after reading the docs I changed the index method to this:

```
public function index()
{
    $baseQuery = auth()->user()
        ->campaigns()
        // Using getQuery() since campaigns() doesn't return a Builder instance
        ->getQuery(); 

    $campaigns = QueryBuilder::for($baseQuery)
        ->allowedFilters(['name'])
        ->paginate();

    return new CampaignCollection($campaigns);
}
```

The resulted sql query was:
```
select *
from `campaigns`
inner join `memberships` on `memberships`.`account_id` = `campaigns`.`account_id`
where `memberships`.`user_id` = ? and LOWER(`name`) LIKE ?
```

but the result was the following:

```
[
    'data' => [
        [
            'id' => '...', // Accounts id!,
            'name' => '...', // Campaigns name,
            // ...
        ],
        // ...
    ]
]
```

The issue was happening only when I was using the getQuery() method.

In order to fix it I had to change my index method and explicitly define the selected columns like so:

```
public function index()
{
    $baseQuery = auth()->user()
        ->campaigns()
        // Need to explicity define the select cause getQuery does weird things
        ->select('campaigns.*')
        ->getQuery();

    $campaigns = QueryBuilder::for($baseQuery)
        ->allowedFilters(['name'])
        ->paginate();

    return new CampaignCollection($campaigns);
}
```

The resulting sql for this was
```
select `campaigns`.*
from `campaigns` inner join `memberships` on `memberships`.`account_id` = `campaigns`.`account_id`
where `memberships`.`user_id` = ? and LOWER(`name`) LIKE ?
```

Laravel version: **5.7.25**
Spatie Query Builder version: **1.13.1**

Am posting this here,
- firstly, because I am not sure If it is a Laravel bug or Package bug (if not bug at all)
- secondly, to let other know in case they come across the same situation
- and last to get advise from anyone on whether there is another way of filtering relations without using the getQuery() method

**Comment by lilisgeorge** [comment]
Have edited my initial post with the resulting sql statements for each change i made

**Comment by lilisgeorge** [comment]
Maybe by getting the Builder instance through getQuery(), I am losing any mappings that were initially created and I should bind them back before calling the paginate() method??

**Comment by scheMeZa** [comment]
I am also experiencing this problem, with a HasManyThrough relationship. Thank you for reporting, it's a difficult one to explain...

**Comment by ce-brex** [comment]
This was submitted in #111, I don't think it was ever fixed properly.

**Comment by pactode** [comment]
I am experiencing this as well on a `BelongsToMany` relation, where the pivot table `id` is returned from the api resource instead of the appropriate resource `id`. 

Any updates on this?

**Comment by FutureFutureTo** [comment]
Was having this issue as well - thanks a ton @lilisgeorge . saved me from insanity!

**Comment by AlexVanderbist** [comment]
This seems to be a bug (?) in the way that eloquent generates and fetches queries for related models through pivot tables...

Without using `getQuery` the relation method generates the following SQL:
```sql
select "related_through_pivot_models".*, "pivot_models"."test_model_id" as "pivot_test_model_id", "pivot_models"."related_through_pivot_model_id" as "pivot_related_through_pivot_model_id" from "related_through_pivot_models" inner join "pivot_models" on "related_through_pivot_models"."id" = "pivot_models"."related_through_pivot_model_id" where "pivot_models"."test_model_id" = ?
```

As you can see there's a couple selects that make sure the IDs all end up where they need to be. My guess is that eloquent will parse those internally and make sure the returned models are correct.

However, using `getQuery` I got the following SQL:
```sql
select * from "related_through_pivot_models" inner join "pivot_models" on "related_through_pivot_models"."id" = "pivot_models"."related_through_pivot_model_id" where "pivot_models"."test_model_id" = ?
```

The additional selects aren't there and when `get()`ing the models they have the wrong IDs.

**Comment by dennislindsey** [comment]
I'm also having this problem using a HasManyThrough relation. I believe it's related to https://github.com/laravel/framework/issues/23548

This issue was "fixed" in Laravel 5.8 but the way in which it was done does not provide the intermediary column alias when calling `->getQuery()` on the relation object. It's only added to the query builder by calling the protected method `HasManyThrough::shouldSelect()` which is only called inside of the query-execution methods on the builder (`get`, `paginate`, `cursor`, etc).

I'm not sure there's an easy way to fix this in this package. In the meantime I've forced the select statement to not return columns from the intermediary table by appending a call to `->select()` on the relation definition.

```
class User extends Authenticatable
{
    ...

    public function returns(): HasManyThrough
    {
        return $this->hasManyThrough(OrderReturn::class, Order::class)
            ->select('order_returns.*');
    }

    ...
}
```

This allows me to continue using this package like so:
```
    public function index(Authenticatable $user, Request $request): LengthAwarePaginator
    {
        return QueryBuilder::for($user->returns()->getQuery(), $request)
            ...
            ->paginate(min($request->input('per_page', 15), 15));
    }
```

**Comment by pactode** [comment]
On a short term basis, we could replicate the underlying functionality from the `shouldSelect` method on `Illuminate\Database\Eloquent\Relations\BelongsToMany`. However, that does not seem to be the best solution as the code is already in place. Perhaps, when calling the `getQuery` method on the relation it should also apply those selects?

**Comment by AlexVanderbist** [comment]
This will be fixed in v3 of the package.

Closing for now, thanks everyone for your help :)
