### ISSUE TITLE
Global scopes not applied

### ISSUE THREAD

**Issue by denitsa-cm** [spatie/laravel-query-builder#173]
Perhaps I'm doing something out of the ordinary but I would like to use the Query builder for a single existing model and I notice that the global scopes are not applied (I have a custom global scope and a soft delete).

Example:

```
  public function show(Publisher $publisher)
    {
        $publisher->load('owner');
        dump('normal load', $publisher->query()->toSql());
       // dumps "select * from `providers` where `providers`.`deleted_at` is null and `is_publisher` = ?"

        $publisher = QueryBuilder::for($publisher->load('owner')->query());
        dd('query builder load', $publisher->getQuery()->toSql());
        // dumps "select * from `providers`"

        return response()->api('Publisher show data', new PublisherResource($publisher));
    }
```

My Publisher extends a Provider model and the scope is defined in the `boot()` of the Publisher like so:

```
class Publisher extends Provider implements HasDeletionConfirmation
{
    use HasDeletionConfirmationTrait, HasParentModel;

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('publisher', function (Builder $builder) {
            $builder->where('is_publisher', true);
        });
    }
.....
```

The same happens if I just use the `Publisher::class` 

```
       $publisher = QueryBuilder::for(Publisher::class)
            ->allowedIncludes(['addresses'])
            ->where('id', 2)
            ->getQuery()
            ->toSql();
```

P.S. I did notice there is another issue for this (#162) but I can't seem to establish what's wrong on my end.

I am using v1.13.1

**Comment by bsormagec** [comment]
is there any update @freekmurze

**Comment by AlexVanderbist** [comment]
Hm, that's pretty weird. We've got some passing tests for these global scopes... Can someone PR a failing test for this? That'll make it easier to pin down the problem.

**Comment by bkintanar** [comment]
This is also happening to my code.

**Comment by AlexVanderbist** [comment]
Gonna close this for now. Scoped queries are working for us and in the tests. If anyone else is still experiencing this on the latest version, please send a PR with a failing test.

**Comment by cjaoude** [comment]
hi @denitsa-md 

Did you figure this out? I'm encountering the same issue. The scope works fine on the parent model, but once moved to an extending model, return is always empty. 

Although what's odd is, this only happens for the spatie method, and not a Model 'where' method for example.

tnx, if u figured it out
