### ISSUE TITLE
Select fields in included table problem

### ISSUE THREAD

**Issue by Trixpua** [spatie/laravel-query-builder#175]
If I make a request and include a relation table and specific to return just some fields, it return empty.

```
GET /categories?include=products
// returns categories with all data in products relation

GET /categories?include=products&fields[products]=name
// returns categories with a empty array in products relation

GET /categories?include=products&fields[products]=name,description
// returns categories with a empty array in products relation
```

But if I add the relation id column it returns all fields correct

```
GET /categories?include=products&fields[products]=category_id,name
// returns categories with a category_id and name array in products relation

GET /categories?include=products&fields[products]=category_id,name,description
// returns categories with a category_id, name and description array in products relation
```

Is necessary to add the relation id to this work or I am making something wrong?

**Comment by thebrubaker** [comment]
Yes if you do not include the foreign keys for how two tables are joined, then eloquent can't load that relationship, so I imagine you must include those fields necessary for joining two relations.

**Comment by ce-brex** [comment]
While you do need to include the foreign keys so eloquent can load it properly, this really seems like unnecessary information to have to pass.  Seems like query builder should be able to figure this out on it's own and add it when needed.

**Comment by Trixpua** [comment]
The documention says I don't need it:

> Selecting fields for included models works the same way. This is especially useful when including entire relationships when you only need a couple of columns. Consider the following example:
> 
> `GET /posts?include=author&fields[author]=name`
> All posts will be fetched including only the name of the author.

But it dosen't work as example, need to add the 'author_id' and 'name' to work properly
`GET /posts?include=author&fields[author]=author_id,name`

I am newbie in laravel, sorry if I am talking bullshit,  but as @ce-brex said, I think query builder should be able to figure out the relations keys without need to declare it in each request.

**Comment by AlexVanderbist** [comment]
>But it doesn't work as example
Ironically, I have never tested the examples 🙈- I'll update the readme.

>I think query builder should be able to figure out the relations keys without need to declare it in each request.
I agree. However, we haven't figured out a good solution yet that works for all Eloquent relationships... Feel free to PR any idea that you guys might have. In the meantime I'll leave this issue open

**Comment by DHSprout** [comment]
I am facing same issue. Could you please suggest any solution for this?

**Comment by champak-7span** [comment]
"spatie/laravel-query-builder": "^3.3"  in this version working well 
 
 But Custom field is not getting in the spatie/laravel-query-builder": "^5.2

**Comment by lebadapetru** [comment]
so has this been fixed? it looks like the relations are null if i don't add the relation id
