### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by taai** [spatie/laravel-query-builder#176]
Yesterday Laravel 5.8 was released. I can't upgrade to newest Laravel version because this package supports Laravel versions up to 5.7.x. 😉 

By the way, does anyone know how to tell Composer to ignore version requirements of a specific package? I spent an hour and didn't find how to do it.

**Comment by matthew-inamdar** [comment]
@taai I don't think you can ignore the package dependencies. you ignore the platform requirements (PHP version, extensions, etc.) with the `--ignore-platform-reqs` flag.

Your options are to:
1. Fork this repo and update the `composer.json` to support `laravel/framework 5.8` (be aware there may be breaking changes)
2. Wait until they release 5.8 support

**Comment by AlexVanderbist** [comment]
We'll be tagging support for L5.8 in about half an hour :)
