### ISSUE TITLE
Validation?

### ISSUE THREAD

**Issue by martinandersen3d** [spatie/laravel-query-builder#216]
Hi, do I need to validate the incoming get request, and if so, how? :-) 

Thanks.

![image](https://user-images.githubusercontent.com/19984581/53901140-7c5b0280-403e-11e9-87b5-d89ef5b97c39.png)

**Comment by dominikb** [comment]
Generally speaking, you do not have to validate the input as the input will be sanitized by the underlying ORM (Eloquent) which uses [PDO prepared statements](http://php.net/manual/de/pdo.prepared-statements.php) under the hood.

Nevertheless, SQL-Injection is a quite complex topic and I would advise you to do some further reading related to this topic. You can find a good write-up [here](https://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection/12202218#12202218).

**Comment by martinandersen3d** [comment]
Thank you so much for the reply.

I'm know that Eloquent is sanitizing before it insert it to the database.

My suspicion & concern is this scenario:

1. User fill out form > user send request (laravel-query-builder)
2. the users inputs does not get through Validation (app/Http/Requests/Person.php) like a normal Post request is... and handled by the FormRequest*
3. And the data is then available in the Person Controller, without checking that the user input is correct.

My question is, in the controller, how can get the user input from the laravel-query-builder, and check it with the FormRequest* ?

..and thanks, I hope my question is a bit more clear :D

***FormRequest**

```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Person extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'id' => 'nullable|integer',
            'name' => 'required|nullable|string|max:5',
            'age' => 'required|nullable|integer',
            'zip' => 'required|nullable|string|max:255',
            'street' => 'required|nullable|string|max:255',
        ];
    } 
}
```

**Comment by dominikb** [comment]
You should still be able to type-hint the FormRequest within your controller action to automatically apply validation before building the `QueryBuilder` instance.


```php
class PersonController extends Controller
{
    // Validation fails if your parametes do not match the validation of the request
    public function store(App\Http\Request\Person $request)
    {
        $person = QueryBuilder::for(App\Person::class, $request)
            ->get();

        return response()->json($person);
    }
}
```

If for any reason you need to validate the data manually or want to apply additional rules, you can manually create a `Validator` for this request.

```php
class PersonController extends Controller
{
    public function store(Illuminate\Http\Request $request)
    {
        $properties = $request->all();
        $rules = app(App\Http\Request\Person::class)->rules();

        Illuminate\Support\Facades\Validator::validate($properties, $rules);

        $person = QueryBuilder::for(App\Person::class, $request)
            ->get();

        return response()->json($person);
    }
}
```

**Comment by AlexVanderbist** [comment]
For your search endpoint, you don't need any other validation. All get parameters will be sanitized by the query builder or underlying ORM.

For the update endpoint: as @dominikb said, you can (and should) still use the `App\Http\Request\Person` FormRequest validation to validate incoming data, even in combination with the query builder.

On a side-note: when updating or creating entities, I wouldn't use the query builder. You should probably specify the id in the url and/or use [route model binding](https://laravel.com/docs/master/routing#route-model-binding) to get the right person to update.

Something like this:
```php
//web.php
Route::post('/person/{id}', 'PersonController@update');

class PersonController extends Controller
{
    public function store(App\Http\Request\Person $request, $id)
    {
        $person = Person::findOrFail($id);
        $person->update($request->validated());

        return response()->json($person);
    }
}
```

Good luck and feel free to open another issue if you need any more help :)
