### ISSUE TITLE
Default Sort not working with specific filter

### ISSUE THREAD

**Issue by falvarezh90** [spatie/laravel-query-builder#218]
Hi, I have a problem with default sort when add a specific filter in the query. For example, when I use default sort in a simple query like `api/sl_customer`, the data is fetched normally, but when i want to add a filter in my query (normal filter, not custom filter) `api/sl_customer?filter[rut]=76430498-5` I get  Exception below :

`
{
    "error":"Call to a member function sort() on null",
    "file":"\/var\/www\/agroplastic_backend\/vendor\/spatie\/laravel-query-builder\/src\/QueryBuilder.php",
    "line":294
}
`

Someone know's what is happened ?

**Comment by dominikb** [comment]
I've done some digging, but it's hard to debug with this little information.

Can you specify what version you are using (I'm assuming 1.13.0 ?) and how your `QueryBuilder` gets built?

If my assumption is correct and you are using 1.13.0, please try switching to a newer version and see if your problem persists.

**Comment by falvarezh90** [comment]
You was right, my version was 1.13.0, after update to newer version the problem has  gone, thanks!
