### ISSUE TITLE
Boolean type nested filter

### ISSUE THREAD

**Issue by njxqlus** [spatie/laravel-query-builder#226]
I have 3 object, where nested object attribute `approval.approved` is boolean and have values:
* approval.approved = true 
* approval.approved = false
* approval = null

When I request `/flights?include=approval&filter[approval.approved]=true` there only 1 object return where `approval.approved` = true  and it's right.

When I request `/flights?include=approval&filter[approval.approved]=false` there only 1 object return where `approval.approved` = false and it's right.

When I request `/flights?include=approval&filter[approval.approved]=abaracadabra` there only 1 object return where `approval.approved` = false and it's wrong.

I use next code: 
```
QueryBuilder::for(Flight::class)
            ->allowedFilters([Filter::exact('approval.approved')])
            ->allowedIncludes(['approval'])
```

I do something wrong or it's bug?

And some interesting thing: When I request `/flights?include=approval&filter[approval.approved]=3` there no one object return and it's true.

**Comment by r-nicol** [comment]
I have just been able to replicate this too. I used `DB::enableQueryLog();` and `$dump = DB::getQueryLog();` to get the actually SQL and bindings and then ran this in MySQL. Basically Laravel is passing your filter in as a string to MySQL. MySQL then casts these strings to boolean for the comparison. [See here for some explanation](https://stackoverflow.com/a/22080540/3985886). So the results you get a quirks of MySQL casting. As FilterExact does not appear to be written for Boolean comparison I would suggest writing a Custom Filter and validating your request input beforehand.
