### ISSUE TITLE
Add support to filter by attributes

### ISSUE THREAD

**Issue by chrismpettyjohn** [spatie/laravel-query-builder#227]
As of right now when trying to filter by an attribute, it will always try doing it by SQL column

**Comment by rogervila** [comment]
+1

**Comment by AlexVanderbist** [comment]
Thanks for the suggestion, do you guys mean [accessors and mutators](https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators)?

I'm afraid we won't be able to make that work. The query builder only handles creating eloquent (sql) queries. We can't actually filter data _after_ it's been retrieved. 

If I misunderstood, feel free to open a new issue 👍
