### ISSUE TITLE
How can i create a QueryBuilder from a model relation?

### ISSUE THREAD

**Issue by selmonal** [spatie/laravel-query-builder#23]
I have Product and Category model. A product belongs to many categories then i need a query like below

```
QueryBuilder::for($category->products())->get();
```

But it won't work. How can i make it work?

Thanks! great package.

**Comment by AlexVanderbist** [comment]
Hi @selmonal! This is because the `QueryBuilder` expects a `Builder` (eloquent query) instance instead of a relationship. 

You can easily solve this by calling `getQuery()` on the relationship:
```php
QueryBuilder::for($category->products()->getQuery())->get();
```

Let me know if you need any more help :)
