### ISSUE TITLE
Getting error on the latest update

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-query-builder#235]
@AlexVanderbist I just took and update of the latest version and I am getting an error on line https://github.com/spatie/laravel-query-builder/commit/3aa483b63c79d9fabcb8653fe837a7736eb93bea#diff-3591cf5c140b20d1bf5fa38e063bfdf7L84

Error `Method Spatie\QueryBuilder\QueryBuilderRequest::sort does not exist.`

**Comment by Lydnasty** [comment]
https://github.com/spatie/laravel-query-builder/issues/224#issuecomment-475294329

**Comment by abishekrsrikaanth** [comment]
@Lydnasty already have that. The issues seems to be the fact that the method `sort` was removed from the class `QueryBuilderRequest` but is being called on the line I linked on my initial post.

**Comment by jayjfletcher** [comment]
I'm having the same issue, failing on the sort

**Comment by AlexVanderbist** [comment]
A fix by @jayjfletcher was just merged and will be tagged soon
