### ISSUE TITLE
Getting error on Lumen

### ISSUE THREAD

**Issue by andisis** [spatie/laravel-query-builder#236]
Laravel-query-builder :  1.17
Lumen : 5.7

Request `fields, include, and filter` work perfectly but if I try combine `include, fields, filter` got error 400

`GET /notes?include=user&fields[notes]=title` Error 400 `Array to string conversion`
`GET /notes?include=user&filter[author_id]=100` Error 400 `Array to string conversion`
`GET /notes?fields[notes]=title,author_id&filter[author_id]=100` Error 400 `Array to string conversion`

My controller
```php
use Spatie\QueryBuilder\QueryBuilder;
use Spatie\QueryBuilder\Filter;
.....

$notes = QueryBuilder::for(Note::class)
            ->allowedFields('id', 'title', 'body', 'author_id')
            ->allowedFilters(Filter::exact('author_id'))
            ->allowedIncludes('user')
            ->get();
```

**Comment by andisis** [comment]
I try to re-install and now work perfectly.
Sorry for inconvenience

**Comment by abishekrsrikaanth** [comment]
@andisis, have you added `$app->configure('query-builder');` to your `bootstrap/app.php`. It looks like the config values aren't loading. I hope that helps.

**Comment by andisis** [comment]
> @andisis, have you added `$app->configure('query-builder');` to your `bootstrap/app.php`. It looks like the config values aren't loading. I hope that helps. This is a required step for lumen.

I'm already added `$app->configure('query-builder');` to `bootstrap/app.php`
This is my bad, I deleted `append => append` on `config/query-builder.php` and it made an error. 
I put back append on config and now working perfectly.
