### ISSUE TITLE
Sort Aliases should be excluded from new validation

### ISSUE THREAD

**Issue by lionslair** [spatie/laravel-query-builder#239]
With the latest update 1.17.1 to prevent the SQL injection attack.
Ref https://murze.be/an-important-security-release-for-laravel-query-builder
Ref https://github.com/spatie/laravel-query-builder/commit/3aa483b63c79d9fabcb8653fe837a7736eb93bea

I fully agree. No issue with this. My issue is that the new VALID_COLUMN_NAME_REGEX

` private const VALID_COLUMN_NAME_REGEX = "/^(?![0-9])[A-Za-z0-9_-]*$/";`

Is applied to sort aliases. I tried to update my code to use sort aliases in order to not accept the field from the request. However Sort Aliases still have the column name run through the regex and cause an exception to be thrown.

I use both the media library which has the custom_properties field and the schemaless attributes package. 

This update means I can no longer sort any data by json fields these packages provide.

Using the sort alias in the allowedSorts() statement should protect and permit sorting on these fields. Because it is using an alias does this not prevent the SQL injection from occurring?

**Comment by AlexVanderbist** [comment]
You are right! I'll update this soon
