### ISSUE TITLE
Next major release - Features/Requests for v2

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-query-builder#244]
As there's a couple of breaking changes lined up for v2 of the package we might as well open up discussion about any other breaking changes we'd like to see.

This is what we've got so far:

- [x] remove request macros
- [x] add a couple of useful helpers to `QueryBuilderRequest` (see #148)
- [x] allowed sorts need to be explicitly defined
- [x] allowed fields need to be explicitly defined
- [x] ~~refactor fields to work the same way as sorts and filters (separate `Field` class, aliases, etc...)~~
- [x] allowed includes and requested includes are all converted to camelCase

Any feedback or new ideas are certainly welcome!

**Comment by viezel** [comment]
Search would be nice https://github.com/spatie/laravel-query-builder/pull/223

**Comment by mikemand** [comment]
The ability to sort NULLs either first or last. Right now, if I try to use an `orderByRaw` while using `QueryBuilder` I get the following exception:

```json
{
    "message": "Undefined index: column",
    "exception": "ErrorException",
    "file": "vendor/spatie/laravel-query-builder/src/Concerns/SortsQuery.php",
    "line": 165
}
```

**Comment by rez1dent3** [comment]
see https://github.com/spatie/laravel-query-builder/issues/256

**Comment by steffex** [comment]
It would be great to have the possibility to add a default filter with a default value.

Example:

```php
<?php
$posts = QueryBuilder::for(Post::class)
    ->defaultFilter('post_status', 'published')
    ->allowedFilters(
        Filter::exact('post_status', 'postStatus.name')->ignore(null),
        Filter::exact('post_author')->ignore(null)
    )
    ->defaultSort('-published_at')
    ->allowedSorts('post_status', 'published_at')
    ->get();
```

**Comment by loonpwn** [comment]
> The ability to sort NULLs either first or last. Right now, if I try to use an `orderByRaw` while using `QueryBuilder` I get the following exception:
> 
> ```json
> {
>     "message": "Undefined index: column",
>     "exception": "ErrorException",
>     "file": "vendor/spatie/laravel-query-builder/src/Concerns/SortsQuery.php",
>     "line": 165
> }
> ```

This needs to be fixed ASAP please. It breaks displaying anything in random order
`->inRandomOrder()`

**Comment by barmmie** [comment]
Can we make the `addFiltersToQuery` method on the `FiltersQuery` trait public?
Or perhaps a new method that does the preParsing and then calls `addFiltersToQuery`?

This would allow us to add custom filters without necessarily whitelisting the filters.

I can create a PR for this if you deem it

**Comment by lilisgeorge** [comment]
I am currently searching for a way to implement filter groups for advanced filter functionality.

An example:

I want all posts with status=x and tag=a,b OR with status=z and tag=c

That could be described as

`GET /posts?filter-group[0][filter][status]=x&filter-group[0][filter][tag]=a,b&filter-group[1][filter][status]=z&filter-group[1][filter][tag]=c&filter-group[1][operator]=or`

Maybe that would be a nice feature to implement 😄

**Comment by lilisgeorge** [comment]
Another approach (assuming that filter groups are by definition grouped with an or statement) would be to change the way filter is handled. When a filter is an Object then is a simple filter else if is an array then is an advanced filter

Let me explain with an example.

The below request

`GET /posts?filter[status]=x&filter[tag]=a,b`

is transformed into an object

```json
{
    "filter": {
        "status": "x",
        "tag": "a,b"
    }
}
```

While the following request

`GET /posts?filter[0][status]=x&filter[0][tag]=a,b&filter[1][status]=z&filter[1][tag]=c`

is transformed into an array

```json
{
    "filter": [
        {
            "status": "x",
            "tag": "a,b"
        },
        {
            "status": "z",
            "tag": "c"
        }
    ]
}
```

So when `filter` is an Object then do _your thing_, and when `filter` is an Array, then, again do _your thing_ but at the end of each iteration (except the initial) wrap the generated query with an `orWhere` method

I guess this approach is better as
1. it keeps URL length sort
2. doesn't introduce any new syntax but instead enhances the current implementation

**Comment by rpouls** [comment]
Currently in Laravel it is possible to do the following:

```
$model->with(['relation' => function($query) use ($id) {
  $query->where('id', '=', $id);
]};
```

This is currently (as far as I know) not possible in V1 and V2 of _Laravel Query Builder._ 

### Proposed functionality:

```
QueryBuilder::for(Model::class)
                ->allowedIncludes(['products' => function(...){...}], 'users')
```

### Backward compatibility
This has a Backward compatibility break:

Adding multiple includes by an array is not possible. 

```
QueryBuilder::for(Model::class)
                ->allowedIncludes(['products' , 'users'])
```

This can be solved with ... before the array. 

```
QueryBuilder::for(Model::class)
                ->allowedIncludes(...['products' , 'users'])
```

### Alternatives:
Add new method allowedIncludesCallback();

**Comment by Trixpua** [comment]
> Currently in Laravel it is possible to do the following:
> 
> ```
> $model->with(['relation' => function($query) use ($id) {
>   $query->where('id', '=', $id);
> ]};
> ```
> 
> This is currently (as far as I know) not possible in V1 and V2 of _Laravel Query Builder._
> 
> ### Proposed functionality:
> ```
> QueryBuilder::for(Model::class)
>                 ->allowedIncludes(['products' => function(...){...}], 'users')
> ```
> 
> ### Backward compatibility
> This has a Backward compatibility break:
> 
> Adding multiple includes by an array is not possible.
> 
> ```
> QueryBuilder::for(Model::class)
>                 ->allowedIncludes(['products' , 'users'])
> ```
> 
> This can be solved with ... before the array.
> 
> ```
> QueryBuilder::for(Model::class)
>                 ->allowedIncludes(...['products' , 'users'])
> ```
> 
> ### Alternatives:
> Add new method allowedIncludesCallback();

This will be great, I was thinking a way to implement something like this to sort the included relations.

->with(['category' => function($query) use ($order) {
    $query->orderBy($order);
}]);

Maybe with a Include::custom() method, similar to the Filter::custom() method;

Sorry if I am saying nonsenses.

**Comment by backstageel** [comment]
Hability to cache the queries like https://github.com/GeneaLabs/laravel-model-caching since they won't support 3rd party Builders.

**Comment by AlexVanderbist** [comment]
@lilisgeorge I can see this being useful but we won't be able to get it in the v2 release. If you're still interested in discussing this further, please feel free to copy/paste your comment into a new issue as I'm closing this one. Thanks! 

@backstageel I feel like caching model queries is out of scope for this package (we're building queries, not caching eloquent results). However if anything can be done to better support the package you mentioned, please open a new issue/PR. Thanks :) 

@Trixpua and @rpouls same answer as the above: I feel like this is out of scope for a query builder package. As a solution I would propose using [accessor/mutators](https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators). Those can be added using `allowedAppends`. If you guys see a better solution that's inline with the packages core idea of building queries, feel free to open a new issue. Thanks!

**Comment by cvgeldern** [comment]
> @backstageel I feel like caching model queries is out of scope for this package (we're building queries, not caching eloquent results). However if anything can be done to better support the package you mentioned, please open a new issue/PR. Thanks :)
> 
True, but compatibility would indeed be great!

**Comment by Yehonal** [comment]
> Currently in Laravel it is possible to do the following:
> 
> ```
> $model->with(['relation' => function($query) use ($id) {
>   $query->where('id', '=', $id);
> ]};
> ```
> 
> This is currently (as far as I know) not possible in V1 and V2 of _Laravel Query Builder._
> 
> ### Proposed functionality:
> ```
> QueryBuilder::for(Model::class)
>                 ->allowedIncludes(['products' => function(...){...}], 'users')
> ```
> 
> ### Backward compatibility
> This has a Backward compatibility break:
> 
> Adding multiple includes by an array is not possible.
> 
> ```
> QueryBuilder::for(Model::class)
>                 ->allowedIncludes(['products' , 'users'])
> ```
> 
> This can be solved with ... before the array.
> 
> ```
> QueryBuilder::for(Model::class)
>                 ->allowedIncludes(...['products' , 'users'])
> ```
> 
> ### Alternatives:
> Add new method allowedIncludesCallback();

This feature is really needed, however for now I'm using a workaround...inside the model:

```
  /**
   * Get the public pictures record associated with the profile
   */
    public function pictures()
    {
        return $this->allPictures()
        ->whereIn("type", array(
        [...]
        ));
    }

```

So, when you use `allowedIncludes(["pictures"])"` it will be properly filtered by the whereIn condition. However, it's not so much dynamic. Please improve it!
