### ISSUE TITLE
overwrite filters 

### ISSUE THREAD

**Issue by pcieslaczyk** [spatie/laravel-query-builder#245]
Hi i have problem with overwrite filters in project 
In Class OrderRepository i have constructor with query builder 

OrderRepository : 
```
public function __construct(OrderItem $orderItem)
    {

        $this->order = QueryBuilder::for(Order::class);

        $this->order->allowedIncludes(['user', 'orderItems']);

        $this->order->allowedFilters(['user_id', 'key', 'status', 'payment_status']);

        $this->orderItem = $orderItem;

    }

```
then i injects it in OrderItemRepository Class

OrderItemRepository :
```
 public function __construct(OrderInterface $order)
    {
        $this->order = $order;
        $this->orderItem = QueryBuilder::for(OrderItem::class);
        $this->orderItem->allowedIncludes(['product', 'container', 'order', 'driver', 'position']);
        $this->orderItem->allowedFilters(['order_id', 'container_id', 'product_id', 'driver_id', 'status', 'quantity', 'price','transport_price']);
        
    }
```
finally result is that in  OrderItemRepository class 
$this->orderItem->allowedFilters  have values ​​from OrderRepository.
And end with error 

> Given filter(s) `driver_id` are not allowed. Allowed filter(s) are `user_id, key, status, payment_status`.

**Comment by AlexVanderbist** [comment]
Hi, 

The query builder package is meant to respond to an HTTP request. This means that if your request contains a `driver_id` filter, _all_ query builders will try to filter by `driver_id`. This is okay for your `OrderItem` model, but obviously not for your `Order` model. 
So in short; don't use two different query builders for the same request.

What are you trying to achieve in your example?

**Comment by pcieslaczyk** [comment]
I have repositories class each class have methods like index, store , update etc.Each methods like index which return collection need query builder. So i put query builder in constructor  to not copy and past it all methods.Class OrderItem needs methods from Class Order so  I inject it in constructor and  here comes the problem Order Class overwrite my query builder instance in OrderItem Class.

I hope you understand what I wrote and thank you in advance

**Comment by dominikb** [comment]
In your code example, you use a single variable for two different types of data:

```php
public function __construct(OrderItem $orderItem)
    {

        $this->order = QueryBuilder::for(Order::class);

        $this->order->allowedIncludes(['user', 'orderItems']);

        $this->order->allowedFilters(['user_id', 'key', 'status', 'payment_status']);

        $this->orderItem = $orderItem; // Here it's of type OrderItem

    }

public function __construct(OrderInterface $order)
    {
        $this->order = $order;
        $this->orderItem = QueryBuilder::for(OrderItem::class); // Now the item is of type QueryBuilder
        $this->orderItem->allowedIncludes(['product', 'container', 'order', 'driver', 'position']);
        $this->orderItem->allowedFilters(['order_id', 'container_id', 'product_id', 'driver_id', 'status', 'quantity', 'price','transport_price']);
        
    }
```

Maybe you could use a different variable like ```$orderItemQuery``` to distinguish between the injected instance and the actual query?

**Comment by pcieslaczyk** [comment]
could you write an short example of how you would see? it because I do not understand.
thanks you in advance

**Comment by AlexVanderbist** [comment]
I'm still not sure what you're trying to do... Can you move creating the query builder to the index methods? That way they wont be instantiated when `__construct` is called. You can move the allowed includes and filters to properties on the class. Something like this:

```php
class OrderRepository
{
    protected $filters = ['user_id', 'key', 'status', 'payment_status'];

    protected $includes = ['user', 'orderItems'];

    protected $orderItem;

    public function __construct(OrderItem $orderItem)
    {
        $this->orderItem = $orderItem;
    }

    public function index()
    {
        return QueryBuilder::for(Order::class)
            ->where('id', $this->orderItem->id)
            ->allowedFilters($this->filters)
            ->allowedIncludes($this->includes);
    }
}

class OrderItemRepository
{
    protected $filters = [ 'order_id', 'container_id', 'product_id', 'driver_id', 'status', 'quantity', 'price', 'transport_price'];

    protected $includes = [ 'product', 'container', 'order', 'driver', 'position'];

    protected $order;

    public function __construct(Order $order)
    {
        $this->order = $order;
    }

    public function index()
    {
        return QueryBuilder::for(OrderItem::class)
            ->where('order_id', $this->order->id)
            ->allowedFilters($this->filters)
            ->allowedIncludes($this->includes);
    }
}
```

**Comment by pcieslaczyk** [comment]
That's what i tried to avoid to not copy and past that part
 ` return QueryBuilder::for(OrderItem::class)
            ->where('order_id', $this->order->id)
            ->allowedFilters($this->filters)
            ->allowedIncludes($this->includes);`
but its ok :)
Thx for help and sorry for trouble

**Comment by AlexVanderbist** [comment]
I see, sadly we're immediately parsing the given request when calling `allowedFilters` (and thus throwing the `Given filter(s) are not allowed...` exception). Good luck!
