### ISSUE TITLE
'for' method triggers phpfmt to mark that method as a control structure

### ISSUE THREAD

**Issue by markdieselcore** [spatie/laravel-query-builder#25]
When using phpfmt to auto-psr2 php files, phpfmt treats the QueryBuilder::for method as a control structure and will attempt to auto format it, resulting in broken code.

`$products = QueryBuilder::for(Product::class)->allowedFilters('name')->paginate($count);`

becomes

        $products = QueryBuilder::for (Product::class) {
                ->allowedFilters('name')->paginate($count);
        }

Suggest renaming the method or adding a proxy method named `forModel`.

**Comment by freekmurze** [comment]
Seems like this is something that should be fixed in `phpfmt` instead of changing the perfectly valid code in this package.

**Comment by alexgiuvara** [comment]
@markdieselcore you can add this method in your main repository or a place you don't touch too often:
```php
public function queryFor($value = null): QueryBuilder
    {
        return QueryBuilder::for($value);
    }
``` 

and use it in child classes:
```php
$this->queryFor(Post::class)
...
```
