### ISSUE TITLE
[Question] dynamic query

### ISSUE THREAD

**Issue by AleSpreafico** [spatie/laravel-query-builder#250]
I think its going to be a stupid question...
But How can I dynamically filter on multiples fields?
ex
`mysite.test/api/users?filter[name]=foo&filter[email]=foo`

on `key-up` I run an `axios` get request that is going to return names containing `foo` and email containg `foo` and doesn't give me empty query if no emails contains `foo`...

Any Idea how to achieve this?

I hope I got my point clear.

Thanks

**Comment by dominikb** [comment]
Filters, by default, are chained using and __AND__ clause, which is why you will be returned an empty result if either filter does not return a match.
There is a pull request open (#223) that adds this capability.

In the meantime, you could use a custom filter class like so:
```php
use Illuminate\Database\Eloquent\Builder;

class FilterOrPartial implements Filter
{

    public function __invoke(Builder $query, $value, string $property): Builder
    {
        return $query->orWhere($property, "%${value}%");
    }
}
```

I hope this helps!

**Comment by AlexVanderbist** [comment]
Or maybe even a custom `SearchUserFilter` to make things really explicit:

```php
// GET /users?filter[search]=foo

use Illuminate\Database\Eloquent\Builder;

class SearchUsersFilter implements Filter
{
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        // $property will be `search` so no use to use, we'll hardcode the fields
        return $query->where('name', 'LIKE', "%{$value}%")->orWhere('email', 'LIKE', "%${value}%");
    }
}
```

**Comment by AleSpreafico** [comment]
@AlexVanderbist yep Thanks a lot!
It worked... even use some resource collection as written in other issue.... Thanks!
