### ISSUE TITLE
Return related model data in foreign key field

### ISSUE THREAD

**Issue by baltun** [spatie/laravel-query-builder#252]
I'd like to have an ability to return data from related table as attributes of field which contains foreign key. 
User table:
id
name

Posts table:
id
user_id
text

Relation in Posts to User named posts_user.

I want to get Post with it's User.

Now if I will ask for: /api/post/somepost/?include=posts_user
I will get
post:[
  {id:<postId>,
   user_id:<user_id>
   text:<text>
   post_user:<object_with_user_attributes>},
  ...
]
I want to get something like this:
post:[
  {id:<postId>,
   user_id:<object_with_user_attributes>
   text:<text>},
   ...
]

for example in oData there is such ability named _expand_ 

Is it possible? Is it needed as new PR?

**Comment by dominikb** [comment]
You could use a combination of this package to specify the query and [Eloquent API Resources](https://laravel.com/docs/5.8/eloquent-resources) to format it however you want before returning it to the user.

I don't think there is a clean way without messing with the data after it got returned from the `QueryBuilder`.

**Comment by baltun** [comment]
I think that "expand" term and it's functionality is widely used in different APIs so it would be good to have this ability in Query Builder.

API Resources is not about what data to get, but about it's format to send. I don't think it is right way to say what kind of data to get

**Comment by baltun** [comment]
but unfortunately as I see in `addIncludesToQuery` method, it implements with Eloquent `with` ability which will create new flat attributes, and I don't know another functionality in Eloquent which will give an ability to put it's result to foreignKey field. So it is more Eloquent constraint...

**Comment by AlexVanderbist** [comment]
I agree, as you said, it's more an eloquent constraint. You could however, like @dominikb suggested, use API resources to format the output data to be formatted as if it's been expanded:

```php
// in your Post API resource:

public function toArray($request)
{
    return [
        'id' => $this->id,
        'user_id' => $this->whenLoaded('user', function () {
            return UserResource::make($this->user);
        }, $this->user_id),
        'text' => $this->text,
    ];
}
```

This will have the user's id the `user_id` property by default. When the user relationship is loaded (using `?include=post_user`), the `user_id` property will contain the user resource (= user object will all attributes).

Hopefully this helps?

**Comment by AlexVanderbist** [comment]
Closing this due to ApiResources being a pretty good solution and inactivity.
