### ISSUE TITLE
posts?includeCount=comments,links [withCount]

### ISSUE THREAD

**Issue by rez1dent3** [spatie/laravel-query-builder#256]
Hello.

I need to be able to call "withCount" through the library. Do you plan such an opportunity?

PS, I  read https://github.com/spatie/laravel-query-builder/issues/87, but I need optional...

**Comment by AlexVanderbist** [comment]
Definitely an interesting feature - maybe we can implement this through a `?scopes=with-comment-count` parameter that adds a scope to a query? Seems like a more flexible solution.

**Comment by rez1dent3** [comment]
@AlexVanderbist it would be great. I'm waiting.

**Comment by decisive-dev** [comment]
@AlexVanderbist I vote for " includedcount." I think it will be easier. The shell will be, and to create scope for with the Count is not correct.

**Comment by AlexVanderbist** [comment]
Hi @decisive-dev! I agree on the `?scopes` parameter not being te correct solution. Currently, I feel like a count is probably just another `include`. Everything include ending in `*Count` will just be included as a relationship's count (when whitelisted using `allowedIncludes`). This is something I'd definitely want to include in the next major version so any feedback is greatly appreciated.

**Comment by AlexVanderbist** [comment]
This has since been added for all allowed relationships. You can also add specific relation counts using `AllowedInclude::count()`. More on this feature in the docs: https://docs.spatie.be/laravel-query-builder/v2/features/including-relationships/#including-related-model-count
