### ISSUE TITLE
Allow allowedIncludes and allowFilters to accept an array

### ISSUE THREAD

**Issue by markdieselcore** [spatie/laravel-query-builder#26]
Would really appreciate it if these two methods could accept arrays or strings. Would be nice to declare my filters in an array and pass them in as needed.

**Comment by jshayes** [comment]
You should still be able to do it by doing
```PHP
$includes = ['foo', ;bar'];
QueryBuilder::for(Model::class)->allowIncludes(...$includes);
```

**Comment by freekmurze** [comment]
@jshayes that's a nice suggestion, that'll work.

But it would indeed be nice if passing an array would just work.

We'd accept a PR with tests for this.
