### ISSUE TITLE
ability to override isRelationProperty

### ISSUE THREAD

**Issue by ashgibson** [spatie/laravel-query-builder#262]
I have a QueryBuilder which joins a table which joins another table e.g. Invoices -> Jobs -> Customers and I want to show a list of invoices filtering on the customer. I have tried this in the allowedFilters

`Filter::exact('customer_id','jobs.customer_id');`

Due to the current logic in inRelationProperty it thinks I am trying to load the jobs relation on the invoice object whereas I am actually trying to filter on the customer_id field on the joined jobs table.

Perhaps there could be something like this `Filter::exact('customer_id','jobs.customer_id', false);` to override running the relation logic.

For the moment I have extended the FilterExact class and overridden the isRelationProperty method.

**Comment by skyrpex** [comment]
Same here.

**Comment by AlexVanderbist** [comment]
Fair point! Feel free to send a PR adding that boolean option. If not, I'll probably include this in the v2 release.

**Comment by AlexVanderbist** [comment]
Will be tagged in 2.2.0! Thanks :)
