### ISSUE TITLE
Class 'Spatie\QueryBuilder\QueryBuilderFacade' not found

### ISSUE THREAD

**Issue by lukevincent** [spatie/laravel-query-builder#27]
Hi I'm trying to use this package, but i just can't get it working.

I've got a fresh install of Laravel 5.5
```
laravel new myapp
```

Then I run
```
composer require spatie/laravel-query-builder
```
and finally a closure in api.php
```
Route::get('/users', function(){
	$users = QueryBuilder::for(User::class)->get();
	return $users;	
});
```
But, I get this error
```
Class 'Spatie\QueryBuilder\QueryBuilderFacade' not found
```
It's a fresh install of laravel 5.5, and i've tried 

```
composer dump-autoload
```
and
```
php artisan cache:clear
```
Is there anything more I can try??

Thanks!!!

**Comment by lukevincent** [comment]
I managed to get the package working by changing the alias path in composer.json from

```
"QueryBuilder": "Spatie\\QueryBuilder\\QueryBuilderFacade"
```
to
```
"QueryBuilder": "Spatie\\QueryBuilder\\QueryBuilder"
```

```
"extra": {
        "laravel": {
            "providers": [
                "Spatie\\QueryBuilder\\QueryBuilderServiceProvider"
            ],
            "aliases": {
                "QueryBuilder": "Spatie\\QueryBuilder\\QueryBuilder"
            }
        }
    }
```

Is this a bug worthy of a pull request or something I'm doing wrong?


Thanks!!

**Comment by freekmurze** [comment]
I've tagged a new version where this problem has been fixed.

**Comment by lukevincent** [comment]
:thumbsup:

**Comment by einnar82** [comment]
i solve by using this approach:

add this code in laravel-query-builder composer 
  `"extra": {
        "laravel": {
            "providers": [
                "Spatie\\QueryBuilder\\QueryBuilderServiceProvider"
            ],
            "aliases": {
                "QueryBuilder": "Spatie\\QueryBuilder\\QueryBuilder"
            }
        }
    }`

then register in your laravel's app.php

providers: ` Spatie\QueryBuilder\QueryBuilderServiceProvider::class,`
aliases: `'QueryBuilder' => Spatie\QueryBuilder\QueryBuilderFacade::class,`
then use it in your app by include: `use Spatie\QueryBuilder\QueryBuilder;`
