### ISSUE TITLE
Query-Builder not working for Laravel GraphQL(nuwave/lighthouse) package.

### ISSUE THREAD

**Issue by vijaybajrot** [spatie/laravel-query-builder#271]
Hi, 

I am using [nuwave/lighthouse](https://github.com/nuwave/lighthouse) package for GraphQL APIs, and i want to add filters in apis.

My Code is: 
```php
public function resolve($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
        $query = Post::select('*')->latest();
        $request = $context->request();

        $request->merge(array_only($args, 'filter'));
        
        return (new QueryBuilder($query, $request))
            ->allowedFilters('status');
    }
```

[Lighthouse](https://lighthouse-php.com) package is using [paginate()](https://lighthouse-php.com/3.4/api-reference/directives.html#paginate) function as directive.

**Comment by mohammad-fouladgar** [comment]
@vijaybajrot  Hi,

The first argument of the `QueryBuilder` must be either a class namespace like this `Post::class` or `Illuminate\Database\Eloquent\Builder` like this :
```php
$query = Post::where('active', true); // Builder
return QueryBuilder::for($query)->latest();
```
Please re-read the [document](https://github.com/spatie/laravel-query-builder#basic-usage).

**Comment by AlexVanderbist** [comment]
I think @vijaybajrot got it right. Not sure what the issue is tho. Can you provide some more information? What error are you getting? What have you tried to debug?
