### ISSUE TITLE
"only_trashed" and "with_trashed" scope filters

### ISSUE THREAD

**Issue by chimit** [spatie/laravel-query-builder#274]
I'm trying to move from Fractal to API Resources + Laravel Query Builder and faced some problems with `only_trashed` filter. I'm trying to make my `only_trashed` filter as flexible as possible so in my case the expected behavior is like this:

1. `only_trashed` is `true`. Only trashed items should be returned.
2. `only_trashed` is `false` means "not only trashed". All items should be returned.
3. `only_trashed` is `null`. The default case. Only existing items without soft deleted should be returned.

I don't know how to implement this logic using scope filters. 

I tried to make a scope filter but it's not even invoked:
```php
public function scopeOnlyTrashed(Builder $query, $value): Builder
{
    if ($value == '1') {
        return $query->onlyTrashed();
    } elseif ($value == '0') {
        return $query->withTrashed();
    }

    return $query;
}
``` 
Apparently, `only_trashed` and `with_trashed` filters are already available but their behavior differs with my needs: no matter which value `with_trashed` parameter has, it's always considered as true.

As an alternative solution, I can define two filters (`only_trashed` and `with_trashed`) instead of one to reach the same flexibility but their behavior is different: `?filter[only_trashed]` works fine without value but `?filter[with_trashed]` needs any value to work. It's really confusing but apparently is a Laravel specific.

**Comment by AlexVanderbist** [comment]
Sounds like you've answered your own question there: seems like Laravel's `onlyTrashed` is interfering with your `onlyTrashed` scope. 

As a solution for your problem I'd propose a custom filter (instead of the scope filter). Something like this should do the trick:

```php
class FiltersTrashed implements Filter
{
    public function __invoke(Builder $query, $value, string $property) : Builder
    {
        if ($value === true) {
            return $query->onlyTrashed();
        } elseif ($value === false) {
            return $query->withTrashed();
        }

        return $query;
    }
}
```

The query implementation looks like this:
```php
QueryBuilder::for(User::class)
    ->allowedFilters([Filter::custom('only_trashed', OnlyTrashed::class)]);
```
with the following request: `GET /users?filter[only_trashed]=false` (...or true, or left out).

Hopefully this answers your question?
