### ISSUE TITLE
Scope filters don't work with custom Builder objects

### ISSUE THREAD

**Issue by bwrice** [spatie/laravel-query-builder#300]
Order Model class:

```
    public function newEloquentBuilder($query)
    {
        return new OrderBuilder($query);
    }

    // OrderBuilder extends Eloquent/Builder
    public function scopeWithStatus(OrderBuilder $builder, string $status)
    {
        return $builder->withStatus($status);
    }
```

You can't type-hint OrderBuilder in the scope or use it's custom methods because this package passes a Eloquent/Builder object into the scope methods.

**Comment by maciejfikus** [comment]
I would like to reopen this issue. 

Using it like:
`SomeModel::query()` - return `SomeModelQueryBuilder`
`QueryBuilder::for(SomeModel::query())` - return `QueryBuilder`

Even using it like:
`QueryBuilder::for(SomeModel::class)->someCustomFromCustomQueryBuilder()->get()` will not work as package execute everything on raw Eloquent Builder, which doesn't have scopes.
