### ISSUE TITLE
One string to filter multiple columns with 

### ISSUE THREAD

**Issue by HuubD** [spatie/laravel-query-builder#303]
I have a list view with a single text input to filter with. I want to use it to filter the following columns: title, city and zipcode. Is this possible already? If not, will it ever be?

**For example:** /endpoint?filter[title,city,zipcode]=yoursearchqueryhere

Awesome package already but a feature like this would be pretty nice!

**Comment by freekmurze** [comment]
You could create a custom filter with this behaviour: https://github.com/spatie/laravel-query-builder#filtering
