### ISSUE TITLE
Turn off lower() on filter::partial

### ISSUE THREAD

**Issue by piotrgulbis** [spatie/laravel-query-builder#304]
Problem I have is that I am filtering on a TEXT MSSQL field. This does not support lower(). 

I am not able to change the DB structure.

Is there any way to use filter::partial without it trying to lowercase the text?

**Comment by piotrgulbis** [comment]
At the moment I'm using filter::scope to do this. If that is the correct way, then please let me know and I will close the issue.

**Comment by vdbelt** [comment]
There is no planned support for MSSQL, so a custom scope would be the way to go 👍!

**Comment by AlexVanderbist** [comment]
Or a custom partial filter. You can copy the `FiltersPartial` class to you own codebase (https://github.com/spatie/laravel-query-builder/blob/master/src/Filters/FiltersPartial.php), change it as required and apply is using `$qb->allowedFilters(Filter::custom('text_filter', MyCustomPartialFilter::class))`. More info on custom filters is available here: https://github.com/spatie/laravel-query-builder#custom-filters
