### ISSUE TITLE
Includes with camelCase gives error.

### ISSUE THREAD

**Issue by hemratna** [spatie/laravel-query-builder#307]
```
$users = QueryBuilder::for(User::class)
            ->allowedIncludes('campaigns', 'campaigns.redirectionUrls')
            ->paginate(1);
```

The request to `/users?include=campaigns,campaigns.redirectionUrls` will throws `Spatie\QueryBuilder\Exceptions\InvalidIncludeQuery` exception.

The reason behind this is, package convert `campaigns.redirectionUrls` into `campaigns.redirectionurls`.

Currently, I can make this work by making `include` the in lower case like

```
$users = QueryBuilder::for(User::class)
            ->allowedIncludes('campaigns', 'campaigns.redirectionurls')
            ->paginate(1);
```

Feel free to close the issue if this expected behavior. If not I am happy to work on this issue.

**Comment by AlexVanderbist** [comment]
I'm not sure why we're converting the include to all lowercase... I think the easiest way to handle this might be to use kebab-case for requested includes, that seems to work. 

In v2 of the package we'll convert all requested includes to camelcase automatically.
