### ISSUE TITLE
Custom filter issue

### ISSUE THREAD

**Issue by ChiselspeedTuning** [spatie/laravel-query-builder#308]
Hi, I am having an issue with the custom filter which filters a relationship, the problem I am having is:

For example, you have 2 products that are black but one is a different size.
the filters would be Black,Size1 or Size 2

I am accessing the filter by ?filter[filters]=Black,Size1

but because both products are also black, it is returning both products still even though Size 1 is only assigned to one of the products.

```class FilterProduct implements Filter {
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        return $query->whereHas('filters', function(Builder $query) use ($value) {
           $query->whereHas('filter', function($query) use ($value) {
               $query->where('name', $value);
           });
        });
    }
}

above is the custom filter

$products = QueryBuilder::for($category->products()->getQuery())
            ->defaultSort('price')
            ->allowedSorts([
                'price', 'quantity'
            ])
            ->allowedFilters(Filter::custom('filter', FilterProduct::class))
            ->paginate(50);

above is the query builder

```
What am I missing? or am I doing what I want to do completely wrong?

**Comment by ChiselspeedTuning** [comment]
After having a re-read of the docs, it turns out what I was trying to do will not work.

Does anyone know how to make it so on multiple selected filters it queries only if the "product" has both "Black, Size1" and not all products that has filters Black and Size1 assigned?

Really struggling with this

**Comment by AlexVanderbist** [comment]
You were on the right track using a custom filter. You'll just have to query for products that have both of the filters. Something like this:
```php
    // in your custom filter:
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        if (! is_array($value)) {
            // value is not an array, must be a single filter -> wrap in array
            $value = [$value];
        }

        foreach($value as $filter) {
           // loop over all filters and add them one-by-one to the filters
           // where's use AND in their SQL
           $query->whereHas('filters', function(Builder $query) use ($filter) {
               $query->where('name', $filter);
           });
        }

        return $query;
    }
```

Hopefully this is what you're looking for?

**Comment by ChiselspeedTuning** [comment]
That was exactly what I was looking for thank you very much. I did attempt this on my own but I ended up just looping the $values instead of including the actual query in the loop, doh!

Again, thanks for the help
