### ISSUE TITLE
Sorting by true number order

### ISSUE THREAD

**Issue by ChiselspeedTuning** [spatie/laravel-query-builder#315]
Hi,
No idea if this is an issue or not but is there anyway possible for the Sort to be the true number order? e.g

1,2,3,4,5,6,7,8,9,10,11

instead of 1,10,11,2,3,4,5,6,7,8,9

Thanks!

**Comment by AlexVanderbist** [comment]
The sort is being passed directly to the underlying SQL query. If sorting behaviour isn't as expected there's probably something wrong with the way you've set up your columns.

Can you try executing an SQL query manually including an `ORDER BY` clause as a test? Are you sure the column you're trying to sort is an integer and not a string type?
