### ISSUE TITLE
Requested filter(s) `filter` are not allowed

### ISSUE THREAD

**Issue by J4si3k** [spatie/laravel-query-builder#324]
Hi,
My application with this builder does not work on a production server. 
on mine domain `sub.domain.com/?filter[categories]=some_category` I get an error:

`Requested filter(s) "filter" are not allowed. Allowed filter(s) are 
"start_before, name, location, categories, description, page".` but on `localhost` everything works. the application uses the same database for prod and dev. what's the problem?

**Comment by atymic** [comment]
Can you post your code so we can try to replicate the issue?

**Comment by J4si3k** [comment]
I'm doing something like this in a controller
```
    public function getFiltredTrainings($request, $perPage = 10) {
      
        $page = $request['page'] ? $request['page'] : 1;

        return QueryBuilder::for(Training::class)
            ->allowedFilters([
                AllowedFilter::scope('start_before'),
                'name', 
                'location', 
                'categories', 
                'description',
                'page'
            ])
            ->defaultSort('created_at')
            ->allowedSorts('categories', 'name', 'location')
            // ->get(); 
            ->paginate($perPage, ['*'], 'page', $page)
            ->appends(request()->query());
    }

    public function index(Request $request)
    {
        $trainings = $this->getFiltredTrainings($request);
        ....
    }
```
this is happening on shared hosting with apache.

**Comment by AlexVanderbist** [comment]
The fact that it's working locally but not on your production environment tells us it's probably an issue with your Apache config or your mod_rewrite config.

The exception message tells us the `filter` get parameter is somehow seen as a filter value itself? So apache is parsing `/?filter[categories]=some_category` as `$_GET['filter']=filter` which is wrong.

Maybe someone using Apache in production can shed some light on this?

**Comment by J4si3k** [comment]
Problem has been solved. The application could not access the query-builder config file. After adding this file to Laravel configuration the problem does not occur.

**Comment by Punksolid** [comment]
I had the same error and fixed with the same solution as @J4si3k 
Happened using PHPUnit and PHP 7.3.10

**Comment by accidentul** [comment]
any ideea how to solve this probleme on a apache server on a shared hosting ...

**Comment by J4si3k** [comment]
@accidentul Have you tried to add config file to laravel app?

> config/query-builder.php

```
<?php

return [
    'parameters' => [
        'include' => 'include',
        'filter' => 'filter',
        'sort' => 'sort',
        'fields' => 'fields',
        'append' => 'append',
    ],
    'count_suffix' => 'Count',
];
```

**Comment by accidentul** [comment]
> @accidentul Have you tried to add config file to laravel app?
> 
> > config/query-builder.php
> 
> ```
> <?php
> 
> return [
>     'parameters' => [
>         'include' => 'include',
>         'filter' => 'filter',
>         'sort' => 'sort',
>         'fields' => 'fields',
>         'append' => 'append',
>     ],
>     'count_suffix' => 'Count',
> ];
> ```

Yes, sadly this is the exact file :(

**Comment by J4si3k** [comment]
I think you would have to describe your problem more to help you. Does your problem also occur locally? I only performed this activity. Perhaps the filter just collects the wrong values what you can see in this [ISSUE](https://github.com/spatie/laravel-query-builder/issues/334#issuecomment-552113812). Maybe check the correctness of parameters passed from scope filters?

**Comment by accidentul** [comment]
Spatie\QueryBuilder\Exceptions\InvalidFilterQuery: Requested filter(s) `filter` are not allowed. Allowed filter(s) are `title, created_at`. in  ....

The controller method
 $programsCategory=QueryBuilder::for(ProgramCategory::class)
            ->allowedFilters(['title', 'created_at'])
           ->allowedSorts(['title','created_at'])
         ->allowedIncludes(['programs'])
          ->get();

And it works locally but not on the hosting

**Comment by fabianlugones** [comment]
Hi. After adding the config file to the laravel app I had to refresh the laravel cache to get rid of the filter error. Here are the commands that I used:

php artisan cache:clear

php artisan route:clear

php artisan config:clear

**Comment by plateena** [comment]
Hi. I got the same problems. But I'm working on packages. When I use the package on the  laravel app, it's working. error happened only when I run phpunit on the package itself.

**Comment by timoteo7** [comment]
I have the same problem in Lumen 8 yet
with simple allowedFilters(['title'])

**Comment by nipunTharuksha** [comment]
I was going through all the comments. as they say check that `query-builder.php` available in config folder. If it is not then please run 
`php artisan vendor:publish --provider="Spatie\QueryBuilder\QueryBuilderServiceProvider" --tag="config"` 

and then you may run commands at https://github.com/spatie/laravel-query-builder/issues/324#issuecomment-656118260 . 
Thanks
