### ISSUE TITLE
Possible to have query builder applied with route model binding?

### ISSUE THREAD

**Issue by docmattman** [spatie/laravel-query-builder#325]
I'm trying a technique that Freek discussed in his [Laracon talk](https://youtu.be/FxACh4X-Xc0?t=1486).  He mentioned having a `Queries` folder and injecting them into controllers like this:

PostController.php
```
public function show(\App\Http\Queries\PostQuery $query, $id) {
    $post = $query->findOrFail($id);
    ...
}
```

However, Laravel has built-in [route model binding](https://laravel.com/docs/5.8/routing#route-model-binding) like this:

PostController.php
```
public function show(Post $post) {
    // Don't need this anymore, since $post is already bound
    // $post = $query->findOrFail($id);
    ...
}
```

The above scenario provides the convenience of not having to grab the post manually.  However, it doesn't have any of the query builder features built-in (includes, filters, etc).  

Is there a way to use the route model binding while still having the query builder features applied to the `$post` that is injected so we can have the includes, filters, etc available on the model?

**Comment by docmattman** [comment]
As a potential solution, I created a `QueryBuilderBindable` trait:

QueryBuilderBindable.php
```
public function resolveRouteBinding($value)
{
    return (new static::$queryClass($this))->findOrFail($value);
}
```

Then in the `Post` model (or any other model I want to do the same), I added this:

```
use QueryBuilderBindable;

protected static $queryClass = \App\Http\Queries\PostQuery::class;
```

Does anyone see issues with doing it this way?  Or is there a better/recommended method for achieving this?

**Comment by freekmurze** [comment]
I think you can just add multiple paramters, and Laravel will try to do the right thing.

public function show(Post $post, PostQuery $query)

**Comment by docmattman** [comment]
@freekmurze, thanks for the reply and the awesome work you're doing!

Yes, you can add multiple params to the method, but the `Post $post` above will not be built from QueryBuilder.  So if I made a request:

`posts/1?include=author,comments`

The author/comments wouldn't be attached, because the `$post` wasn't resolved using QueryBuilder.  Basically the bound `$post` would be a vanilla eloquent model and wouldn't apply the `includes`, `filters`, etc from QueryBuilder.

**Comment by bskimball** [comment]
I just ran into this, but I'm not using Queries (I will listen to the Laracon talk linked above). The easiest way I can think to do it is to just convert the model instance to a query builder instance on the fly.
```
public function show(Team $team)
    {
        $team = QueryBuilder::for(Team::where('id', $team->id))
            ->allowedIncludes(['nodes', 'members', 'type', 'owner'])
            ->get();

        return response()->json($team, 200);
    }
```

**Comment by netbuilding** [comment]
same question here. how can i includes relationship when using route model binding?

**Comment by reppair** [comment]
Interesting that the this discussion is quite for some time now, looking to solve this too

**Comment by bskimball** [comment]
I ended up ditching route model binding when I'm using QueryBuilder
## Model
```
class Area extends Model
{
    protected $connection = 'timetracker';

    protected $table = 'areas';

    protected $fillable = [
        'name',
        'description'
    ];

    protected $hidden = [
        'created_at',
        'updated_at'
    ];

    public function tasks()
    {
        return $this->hasMany('App\Models\Task');
    }
}
```

## Resource
```
class AreaResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'description' => $this->description,
            'tasks' => TaskResource::collection($this->whenLoaded('tasks'))
        ];
    }
}
```

## Controller Action
```
    /**
     * @param $id
     * @return AreaResource
     */
    public function show($id)
    {
        $area = QueryBuilder::for(Area::where('id', $id))
            ->allowedIncludes(['tasks'])
            ->first();
        return new AreaResource($area);
    }
```

## Query URL
```
/areas?include=tasks
```

**Comment by reppair** [comment]
I went @docmattman 's way:

**`QueryBuilderBindable` trait**
```php
    public function resolveRouteBinding($value, $field = null)
    {
        return (new $this->queryClass)
            ->where($field ?? $this->getRouteKeyName(), $value)
            ->first();
    }
```

**Model**
```php
use QueryBuilderBindable;

protected string $queryClass = DivisionQuery::class;
```

**Query class**
```php
class DivisionQuery extends QueryBuilder
{
    /**
     * Define the allowed query builder options.
     */
    public function __construct()
    {
        parent::__construct(Division::query());

        $this->allowedIncludes('company')
            ->allowedFilters('name');
    }
}
```

**Controlle**
```php
    public function show(Company $company): CompanyResource
    {
        return new CompanyResource($company);
    }
```

Works nicely.

**Comment by leon0399** [comment]
@reppair haven't you yet faced an issue with nested controllers: 

`GET /posts/{post_id}/comments?include=liked_by`

Controller:
```php
function index(Post $post) {
    return QueryBuilder::for($post->comments())
        ->allowedIncludes(['likedBy'])
        ->paginate();
}
```

Post:
```php
public function resolveRouteBinding($value, $field = null)
{
    return QueryBuilder::for(__CLASS__)
        ->allowedIncludes(['comments'])
        ->where($field ?? $this->getRouteKeyName(), $value)
        ->first();
}
```

Since router will try to resolve `Post` through `QueryBuilderBindable`, which doesn't have `likedBy` allowed to include, it will fail with `InvalidIncludeQuery` exception

**Comment by reppair** [comment]
I will try, and let you know.

**Comment by reppair** [comment]
@leon0399 you are correct, here is how I use it currently, just got rid of the route model binding..

```php
public function events(int $companyId, EventQuery $eventQuery): EventCollection
{
    return new EventCollection($eventQuery->where('company_id', $companyId)->all());
}
```

**Comment by C-Collamar** [comment]
I'm not sure whether my comment is already in tangent with the discussion, but as for the original question, my solution is as follows:

1. First, make sure to use `Spatie\QueryBuilder\QueryBuilder` in your `my-resources.index` route. Nothing unusual; and I presume that everyone in here is doing that.

    For example, in your `MyResource` controller:

    ```php

    namespace App\Http\Controllers;

    use App\Models\MyResource;
    use Spatie\QueryBuilder\QueryBuilder;

    class MyResourcesController extends Controller
    {
        public function index()
        {
            return QueryBuilder::for(MyResource::class) /* setup filters, includes, etc. */;
        }
    }

    ```

1. Then in your `MyResource` model, explicitly define the route model binding logic, as follows:

    ```php

    public function resolveRouteBinding($id, $field = null) {
        $primaryKey  = $this->getKeyName();
        $requestUrl  = route('driver-truck-pairs.index');
        $queryParams = parse_url(request()->getUri())['query'] ?? '';

        $subRequest  = Request::create("$requestUrl?filter[$primaryKey]=$id&$queryParams");
        $modelsFound = Route::dispatch($subRequest)
            ->getOriginalContent()
            ->items();

        return current($modelsFound);
    }

    ```
    The idea is to consume your own API by making an internal request to the `my-resources.index` route. I like this approach because we only have to define the query-building rules in just one place. It enforces consistency in our API.

1. After that, now we can work on the `my-resources.show` route as normal.

    ```php

    class MyResourcesController extends Controller
    {
        public function index() { /* ... */ }

        public function show(MyResource $my_resource)
        {
            // the bound `$my_resource` model now has laravel-query-builder applied to it 🔥 
        }
    }

    ```

I hope this helps!
