### ISSUE TITLE
V2 Lumen Support

### ISSUE THREAD

**Issue by ce-brex** [spatie/laravel-query-builder#327]
V2 seems to make heavy use of the `request()` helper, as did V1, which is not available in Lumen.  Since that helper is part of the laravel-foundation and not required by the composer.json file, it might make sense to change these instances to `app('request')` for better support.

If Lumen is not going to be officially supported, then this can be ignored.

**Comment by freekmurze** [comment]
We don’t use Lumen for our projects, so we’re not going to support it.
