### ISSUE TITLE
V2 Upgrade Guide - macro removal

### ISSUE THREAD

**Issue by ce-brex** [spatie/laravel-query-builder#328]
In the upgrade guide, it mentions replacing all macros calls to using the methods on the QueryBuilderRequest class.  The examples don't work as they don't have the proper request object.  There are a couple of possible ways to do this however.

1. Change `app(QueryBuilderRequest::class)->includes()` to something like `app(QueryBuilderRequest::class)->fromRequest(app('request'))->includes()`

2. Inform the user to add a binding for QueryBuilderRequest in `AppServiceProvider::register()`
```
$this->app->bind(QueryBuilderServiceProvider::class, function ($app) {
    return QueryBuilderRequest::fromRequest($app['request']);
})
```
3. Update the `QueryBuilderServiceProvider` to include a register method and the binding from above.

The last two offer the ability to also inject the QueryBuilderRequest instead of the Laravel Request class in to controllers.

A note on the guide that these methods do not accept arguments would also be helpful.

**Comment by AlexVanderbist** [comment]
You're right! I'll add some info and a link to this issue in the upgrade guide. I didn't feel like having adding the request class to the service container as it didn't have much use in the package but I can see this being valueable in the context of a controller. 

On the method arguments: the macros were deprecated a while ago and it's easy enough to call `contains` on any of the `QueryBuilderRequest` methods. I'll add a note for that too. 

Thank you!

**Comment by klimov-paul** [comment]
At the current 'master' code, binding for `QueryBuilderRequest` is already present:
https://github.com/spatie/laravel-query-builder/blob/master/src/QueryBuilderServiceProvider.php#L22-L24

And examples like:

```php
app(QueryBuilderRequest::class)->includes();
```

works correctly.

See e66471c34b28a9511bb545d8c8ec0164b2913301

**Comment by klimov-paul** [comment]
I suppose this issue can be closed.
