### ISSUE TITLE
Custom filter for several params

### ISSUE THREAD

**Issue by z-h-z-h** [spatie/laravel-query-builder#329]
Hi,
for example, I have two params in query string:
`?filter[param_a]=value_a&filter[param_b]=value_b`
I need both in one filter (scope or custom filter), but I can't use comma separated data like that
`?filter[params]=value_a,value_b`

how to implement custom filter with access to both param_a and param_b?

**Comment by AlexVanderbist** [comment]
Hi, 

This actually works out of the box. If you pass two parameters separated by a comma we'll pass those values to your custom filter or scope as an array. Take a look at this test: https://github.com/spatie/laravel-query-builder/blob/6540eb05f8e8e71dc16703ee64877f495e41ec41/tests/FilterTest.php#L190-L203

Good luck and feel free to open a new issue if you're still experiencing issues.

**Comment by z-h-z-h** [comment]
@AlexVanderbist sorry, but I asking about antoher feature. 
Can I do like this:
`?filter[param_a]=value_a&filter[param_b]=value_b`
and then get param_a and param_b BOTH in ONE scope filter

**Comment by blite** [comment]
@AlexVanderbist I don't really see where this solves this issue.  For instance if you needed to do a subquery that contains two different parameters.

**Comment by blite** [comment]
imo both https://github.com/spatie/laravel-query-builder/discussions/557 and https://github.com/spatie/laravel-query-builder/pull/550 are related to this.  The suggested ```passFullRequest``` could solve this issue potentially.  It would additionally need a way to not run certain filters if they have already been run elsewhere.
