### ISSUE TITLE
Requested filter(s) `page` are not allowed. Allowed filter(s) are `postcode`."

### ISSUE THREAD

**Issue by mikebrandl** [spatie/laravel-query-builder#330]
When adding in this functionality it works great on a staging server, however on the production server running the same code I get the following: 

{
    "message": "Requested filter(s) `page` are not allowed. Allowed filter(s) are `postcode`."
}

We use pagination which works fine most of the time. 

Example: 

Front end: 

```
  query = "/api/products?page=" + page + "&filter[name]=" + this.search;
       axios.get(query)
        .then(({ data }) => (this.Products = data));

```
Which then hits: 

```

Route::apiResources(
    [
        'products' => 'API\ProductController',
    ]
);
```

Which goes to: 

```
 public function index()
    {

        return QueryBuilder::for(Product::class)
        ->allowedFilters('name')
        ->paginate(20);
    }
```

We then get: Requested filter(s) `page`,`filter` are not allowed. Allowed filter(s) are `postcode`."
However when we send it a page in the URI it get's very upset...

Any immediate ideas? 

I've checked the NGINX Config, PHP Versions, Composer.lock files. 

Thanks

Mike

**Comment by mikebrandl** [comment]
This also happens if we remove pagination and just have the filtering. 

This then returns "message": "Requested filter(s) `filter` are not allowed. Allowed filter(s) are `postcode`."

**Comment by AlexVanderbist** [comment]
Can you post the contents of your query builder config file? Thanks!

**Comment by mikebrandl** [comment]
Hi, I've just tried implementing this again and it now working, not sure what happened before because the code is the same, thanks for your help.

**Comment by fabianlugones** [comment]
Hi. After adding the config file to the laravel app I had to refresh the laravel cache to get rid of the filter error. Here are the commands that I used:

php artisan cache:clear

php artisan route:clear

php artisan config:clear
