### ISSUE TITLE
query by 2 values send from front

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#331]
consider i have a filed named stars and i wanna filter them in a checkbox so user send me 2 numbers hotels with 3 star and 4 star how can i show the result of both because with the code below it just shows the last number that user send which in this case is 4 here is the code 
```
$data = QueryBuilder::for(Hotel::class)
            ->allowedFilters(['stars')
            ->paginate(10);
```

**Comment by AlexVanderbist** [comment]
I'd suggest adding a `scopeStars(...)` [scope](https://laravel.com/docs/master/eloquent#local-scopes) to your `Hotel` class. You can then use a scope filter to filter using the scope.

Something like this:

```php
class Hotel extends Model {
    // ...

    public function scopeStars(Builder $query, ...$stars) {
        return $query->whereIn('stars', $stars);
    }
}
```

and in your controller: 

```php
$data = QueryBuilder::for(Hotel::class)
            ->allowedFilters([AllowedFilter::scope('stars')])
            ->paginate(10);
```

Query then looks like this: `/hotels?filter[stars]=1,2,5` for hotels with 1, 2 and 5 stars. The commas will be automatically parsed as multiple values and passed to the `scopeStars` scope as multiple parameters.

Hopefully this is what you're looking for? If not, feel free to open a new issue :)
