### ISSUE TITLE
Cannot query relationship name with underscore

### ISSUE THREAD

**Issue by felix28** [spatie/laravel-query-builder#332]
I have a relationship named as user_other_infos and check_ups. I put them inside here:

->allowedIncludes(['user_other_infos', 'check_ups', 'cashiers', 'fecalyses']);

Those without underscore works but those with underscore don't work.

For now, I am removing the underscore to make it work.

**Comment by vdbelt** [comment]
The names of the relationships will be converted to camel case.

So for `user_other_infos`, laravel-query-builder will look for `userOtherInfos`

**Comment by thijsw** [comment]
I'm using this workaround for now:

```php
->allowedIncludes(
  'cashiers',
  collect([
     new AllowedInclude('check_ups', new IncludedRelationship(), 'check_ups'),
  ])
)
```
