### ISSUE TITLE
scope filter not pass all parameters after comma

### ISSUE THREAD

**Issue by J4si3k** [spatie/laravel-query-builder#334]
If I make request

`GET /?filter[category]=techniczne,klimatyzacja`

and use the fallowing filter:

```
public static function scopeCategory(Builder $query, $value): Builder
    {
        $categoryNames = explode(',', $value);

        dump($categoryNames);

        return $query->whereHas('categories', function($query) use ($categoryNames) {
            $query->whereIn('name', $categoryNames);
        });
    }
```
then in `$value `I receive only first string from category filter (in this case "techniczne"). Why am I losing other arguments? In standard filter it works fine.
 Maybe can I pass ith in `$request->query('filter')['category']` somehow?

my query looks like this:
```
    public function getFiltredTrainings($request, $perPage = 10) {
      
        $page = $request['page'] ? $request['page'] : 1;

        return QueryBuilder::for(TrainingModel::class)
            ->allowedFilters([
                AllowedFilter::scope('category'),
            ])
            ->defaultSort('created_at')
            ->paginate($perPage, ['*'], 'page', $page)
            ->appends(request()->query());
    }
```

**Comment by pactode** [comment]
As far as I know it splits the value automatically by comma, so `$value` should be an array. I'm not sure if that behaviour has been changed, but try dumping the `$value` to check if that is the case.

**Comment by J4si3k** [comment]
@pactode `gettype($value)` return string and `$value` is a first param of filter

**Comment by webbyrankonsulterna** [comment]
Hello, this happens to me too. Must be a bug? I switched to custom filter, where I get an array correctly.

**Comment by chuckienorton** [comment]
I have the same issue. 
`&filter[specialties][]=1&filter[specialties][]=2` 
only passes into the scope value the string
`"1"`
if i try passing in a string with commas as first commenter 
`&filter[specialties]=1,2`
i also just get the first value as a string
`"1"`

**Comment by che1974** [comment]
Class FiltersScope return ...$values explaining what this mean by link  https://stackoverflow.com/questions/41124015/meaning-of-three-dot-in-php
And in Model scope function we must use same construction, for example 
public function scopeWorkDate(Builder $query, ...$dates)

**Comment by J4si3k** [comment]
@che1974 answer is correct for me.

**Comment by nelson6e65** [comment]
Is this documented somewhere? It should be in the FAQs. 

Thanks, @che1974
