### ISSUE TITLE
camelCase is converting into lowercase

### ISSUE THREAD

**Issue by sclavijo93** [spatie/laravel-query-builder#336]
Hello! 
I don't know if it is a bug or it is the way it should work

When I try to include a camelCase relationship it is converted to lowercase.
For example:
If I request to `/api/unit-groups?include=baseUnit` it throws this error:
`Requested include(s) 'baseunit' are not allowed. Allowed include(s) are 'baseUnit, baseUnitCount'.`

Can you help me with that? If you need more information just let me know..

Thanks in advance

Versions
Package: 2.0.1
Laravel: 5.8

**Comment by sclavijo93** [comment]
It seems like here is what is failing to me:

When ensureAllIncludesExist() is executed it iterates over $this->request->includes();
https://github.com/spatie/laravel-query-builder/blob/2f4f7dd0dada2f2110b06320a33e79cd2d701c09/src/Concerns/AddsIncludesToQuery.php#L36

Wich is created here:
https://github.com/spatie/laravel-query-builder/blob/2f4f7dd0dada2f2110b06320a33e79cd2d701c09/src/QueryBuilder.php#L30

and the problem is here because is always converting all to lowercase
https://github.com/spatie/laravel-query-builder/blob/2f4f7dd0dada2f2110b06320a33e79cd2d701c09/src/QueryBuilderRequest.php#L22-L24

removing strtolower() or replacing it with Str::camel()  is fixing the problem to me.

**Comment by AdamNimDev** [comment]
+1

**Comment by AlexVanderbist** [comment]
Thanks, that's definitely a bug! Will tag a fix in a couple of minutes.

**Comment by sclavijo93** [comment]
Thanks @AlexVanderbist!
