### ISSUE TITLE
custom filter error ilterBedCount::__invoke() must be an instance of 

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#343]
hi i am attemting to create a costum filter for my app and here is my code :
```
<?php
/**
 * Created by PhpStorm.
 * User: farshad
 * Date: 9/25/19
 * Time: 4:32 PM
 */

namespace App\Api\V1\Filters;



use Spatie\QueryBuilder\Filters\Filter;
use Illuminate\Database\Eloquent\Builder;

class FilterBedCount implements Filter
{
    public function __invoke(Builder $query, $value, string $property) : Builder
    {
        $query->whereHas('gallery', function (Builder $query) use ($value) {
            $query->where('src', $value);
        });
    }
}
```
this is my costum filter and here is my controller :   
```
public function scopeFilter(){
        $data = QueryBuilder::for(Accommodation::class)
//            ->allowedIncludes(['gallery','city','accommodationRoomsLimited'])
            ->allowedFilters([
//                'name', 'grade_stars','src',
                AllowedFilter::custom('gallery', new FilterBedCount),
                ])
            ->paginate(10);
        return $data;
```
but when i run it i get this error : 
```
{
    "message": "Return value of App\\Api\\V1\\Filters\\FilterBedCount::__invoke() must be an instance of Illuminate\\Database\\Eloquent\\Builder, none returned",
    "status_code": 500
}
```
any idea which part i am doing wrong ???

**Comment by farshadff** [comment]
where is every one ?? :)

**Comment by freekmurze** [comment]
It’s weekend, so everybody is probably resting, spending time with their family, that sort of thing.

**Comment by farshadff** [comment]
ok cool i asked cause i opened the issue 4 days ago !!

**Comment by freekmurze** [comment]
So? We don’t make a commitment on a timeframe in which issues are handled. We’ll take a look when we have the time. There currently are more important things on our plate than your problem.

Please be patient or look for help on another platform.

Thanks for understanding.

**Comment by farshadff** [comment]
a good package is to be active for user errors otherwise it would be . . . any way i dont have right to complain about it because i dont pay for it and i dont take it for granted . thanks for your much friendly answer . . .  and sorry to bother you .
