### ISSUE TITLE
Argument 1 passed to App\\Accommodation::App\\{closure}() must be an instance of App\\Builder

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#344]
i am using scope filter with this package i do all things as documentation says but i get this error below : 
```
{
    "message": "Argument 1 passed to App\\Accommodation::App\\{closure}() must be an instance of App\\Builder, instance of Illuminate\\Database\\Eloquent\\Builder given, called in /home/farshad/my-projects/tika_acco/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 1008",
    "status_code": 500
}
``` 
and here is my code : 
```
 public function scopeBedCount($query,$bed_count)
    {
        return $query->whereHas('accommodationRooms', function (Builder $query) use ($bed_count){
            $query->where('src', $bed_count);
        });
    }
```
and here is my controller : 
```
 public function scopeFilter(){
        $data = QueryBuilder::for(Accommodation::class)
            ->allowedFilters([
            AllowedFilter::scope('bed_count')
                ])
            ->paginate(10);
        return $data;
    }}
```

**Comment by AlexVanderbist** [comment]
Hi! This is an issue on your end. You're using the `Builder` type in your scope but it's not imported. Add the `Illuminate\Database\Eloquent\Builder` import at the top of your `Accommodation` class and this should be solved. Good luck!

**Comment by SerkoCy** [comment]
> Hi! This is an issue on your end. You're using the `Builder` type in your scope but it's not imported. Add the `Illuminate\Database\Eloquent\Builder` import at the top of your `Accommodation` class and this should be solved. Good luck!

Thank you very much mate you saved me. I have been spend whole my morning to find this error.

**Comment by muzamilasaanghar** [comment]
> Illuminate\Database\Eloquent\Builder

worked for me thanks :)
