### ISSUE TITLE
QueryBuilderRequest only using $this->query(), maybe change to $this->input()?

### ISSUE THREAD

**Issue by Haskiez** [spatie/laravel-query-builder#345]
Maybe this is a bit narrow in focus but, it would be nice to use the QueryBuilder for querying your data but also for updating it. This package is great if you are putting everything in the query string, but what if you want to use this QueryBuilder to handle scoping for something like updating via a PUT request?

Let's say we want to update specific records that match the filters being passed. Since the package only uses $this->query() it won't pick up anything in the body. It would be nice if it used $this->input() instead so it could find the filters, includes, and fields in both the body and in the query string.

Essentially the only change would be updating it to use the right ->input() instead of ->query() in the QueryBuilderRequest file.

**Comment by AlexVanderbist** [comment]
How exactly would you be using it with a PUT request? I think it's actually more appropriate to keep the filters and data separated but maybe I'm missing something?

Tiny untested example:
```php
QueryBuilder::for(User::class)
->allowedFilters(['email'])
->get()
->update($request->input());
```
Would work for the following request: `PUT /users?filter[email]=gmail` and regular update data as the request body.

**Comment by Haskiez** [comment]
@AlexVanderbist maybe it does. Maybe its more personal preference that when making PUT or POST requests, it feels funky adding things to the url rather than putting it in the body. But I see your point and that also does make sense.

**Comment by AlexVanderbist** [comment]
I suppose if you really wanted something like this, you can extend the `QueryBuilderRequest` class, make the necessary changes and bind it in the service container... Gonna close this for now, feel free to open a new issue if you're still experiencing any issues
