### ISSUE TITLE
Large Query Strings

### ISSUE THREAD

**Issue by T0miii** [spatie/laravel-query-builder#353]
Sometimes the Query String is from the request is to large to submit it.
We tried to submit the request as a POST the problem is that the `QueryBuilderRequest` is only getting the string from the requests query string.
```
    public function filters()
    {
        $filterParameter = config('query-builder.parameters.filter');

        $filterParts = $this->query($filterParameter, []);

        if (is_string($filterParts)) {
            return collect();
        }

        $filters = collect($filterParts);

        return $filters->map(function ($value) {
            return $this->getFilterValue($value);
        });
    }
```
Can this is function somehow be overwritten to use the entire Request body. 
I would like to use `$filterParts = $this->input($filterParameter, []);`

**Comment by dominikb** [comment]
You can extend the `QueryBuilderRequest::class`, overwrite the `filters()` method and register it in your own ServiceProvider.

You need to make sure, that your own service provider is registered after the `QueryBuilderServiceProvider` of this package.

Then you can call the `QueryBuilder` and it will automatically resolve your implementation through the service container.

````php
// This goes into YourServiceProvider.php
app()->bind(QueryBuilderRequest::class, function() {
 // Initialize and return your Request implementation
});

$query = QueryBuilder::for(MyModel::class);
````

This is the code that takes care of resolving to the correct `QueryBuilderRequest`:
https://github.com/spatie/laravel-query-builder/blob/e66471c34b28a9511bb545d8c8ec0164b2913301/src/QueryBuilder.php#L30-L39

**Comment by T0miii** [comment]
thank you, we are going to try this.
