### ISSUE TITLE
Casting Properties Filtering

### ISSUE THREAD

**Issue by paligiannis** [spatie/laravel-query-builder#355]
In my database I have a column named "gender" that is a casted property. 
It returns {"male": 1 , "female":  1}. 
It's a toystore and when both genders are 1 then it returns "unisex". 

In the documentation I can't find any any solution for casted properties.

**Comment by dominikb** [comment]
Filters will be transformed into SQL `WHERE` clauses, thus it is not possible to use the computation logic of casted properties together with this query builder package.

One way you could realize a solution would be to write a custom filter, that takes a string input and generates the corresponding database representation for querying.

```
"unisex" -> "{"male": 1, "female": 1}"
"male" -> "{"male": 1, "female": 0}"
"female" -> "{"male": 0, "female": 1}"
```

Alternatively you could switch to use an string or int enumeration as representation in your database.
