### ISSUE TITLE
Sorting by related properties

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-query-builder#36]
As described in the spec here: http://jsonapi.org/format/#fetching-sorting

>It is recommended that dot-separated (U+002E FULL-STOP, “.”) sort fields be used to request sorting based upon relationship attributes. For example, a sort field of author.name could be used to request that the primary data be sorted based upon the name attribute of the author relationship.

However this is not possible on an eloquent query builder. `Model::with('related')->orderBy('related.name')->get()` doesn't work as the related models would be fetched in a second query and the first query doesn't know the `related.name` field. 
I'm also not sure what the intended behaviour would be relationships returning multiple models. (Sort the related models first; then sort parent models by first related model?)

As I see it there a couple different solutions: 
- if there are any sort queries for related properties (containing `.`) fetch the results first and sort the collection after that. This doesn't work if you're paginating or limiting the query
- use a select to include the related property on the initial query and then sort – only works for `belongsTo` and `hasOne` relationships and feels like a pain to implement

Any thoughts/insights on this are very welcome!

**Comment by ntzm** [comment]
Would be a great feature but I'm not sure how possible it is without joins. I tried to do something similar on a personal project and ended up just abandoning the idea because I couldn't find a reliable way to get it to work for every relationship type.

**Comment by brendt** [comment]
> but I'm not sure how possible it is without joins

Is there a problem to use joins?

Another thing coming to mind, my first thought when I was trying to do this without knowing it wasn't possible: I wouldn't mind implementing this sort myself if that makes it easier for the package, something like:

```php
$favorites = QueryBuilder::for(Favorite::class)
    ->customSorts([
        'loan_type_name' => function (Builder $builder, bool $isDesc): Builder {
            return $builder
                ->join('loan_participations', 'favorites.loan_participation_id', '=', 'loan_participations.id')
                ->join('loan_types', 'loan_participations.loan_type_id', '=', 'loan_types.id')
                ->orderBy('loan_types.name', $isDesc ? 'desc' : 'asc');
        }
    ])

    // ...
```

Don't know if this would be possible, I haven't really looked at the internals of the package yet.

**Comment by robsontenorio** [comment]
@AlexVanderbist 
Maybe? https://github.com/fico7489/laravel-eloquent-join

**Comment by golubkovden** [comment]
Yeah, it would be great to see this feature.

**Comment by matthias-schmitt** [comment]
Hello @ all

First of all thanks for the great package!

Could someone please explain how to achieve sorting and filtering on related models?
Cannot find anything related in the documentation.

Many thanks,

Matthias

**Comment by brendt** [comment]
@matthias-schmitt  Here's an example of a project I'm working on right now. There's one thing I should specify, namely that I tend to use classes for different queries, so that they can be re-used and injected where needed. If this is too complicated to your specific case, you can simply fall back to using an inline query builder, and still do the join and order by you'll see in the example.

```php
class UnitsIndexQuery extends QueryBuilder
{
    public function __construct(Request $request)
    {
        parent::__construct(Unit::query(), $request);

        $this
            ->with('unitType')
            ->allowedSorts('unit_types.name')
            ->defaultSort('unit_types.name');
    }
}
```

So doing this inline would be something like:

```php
QueryBuilder::for(Unit::class)
    ->with('unitType')
    ->allowedSorts('unit_types.name')
    ->defaultSort('unit_types.name');
```

Now you can sort in the url via `?sort=unit_types.name`.

Lastly, instead of using `with` you can of course also join any table you want.

**Comment by matthias-schmitt** [comment]
@brendt Many thanks for helping.

Your code indicates that the relationship is always loaded via the with method, right?
I would like to combine the relationship sorting with the include relationship option.

When I try to load the relationship with the inline solution you showed and sort by a column inside the relation the query tries to sort inside the parent query saying column not found.

**Comment by brendt** [comment]
You want optional sorts depending on whether a relation is loaded or not? I don't think that's possible as you only know if a relationship is loaded after the query has been executed.

I guess you could check for the query parameter in the controller?

```php
$query = QueryBuilder::for(Unit::class);

if (in_array('unitType', $request['include'])) {
    $query
        ->with('unitType')
        ->allowedSorts('unit_types.name')
        ->defaultSort('unit_types.name');
}
```

**Comment by matthias-schmitt** [comment]
Hi @brendt 

This does not work for me as the sort command always refers to the parent query.

Example: Companies have users:

```php
$query = QueryBuilder::for(Company::class);
$query
  ->with('users')
  ->allowedSorts('users.name')
...
```

This query is ending in an exception saying there is no column name in the company table.

**Comment by josegus** [comment]
@brendt 

Hi @matthias-schmitt , same issue here, trying to sort by related.column return exception column not found in parent relation. I suggest made and accesor and append to parent relation when needed

**Comment by mikaeljorhult** [comment]
@AlexVanderbist As @ntzm stated earlier I don't think this is possible without joins as, as you stated, the related models are fetched in another query.

Just started looking into it but could you check for properties containing a `.` and add joins to the query dynamically? I'm doing this right now:

```php
$bookings = QueryBuilder::for(Booking::class)
  ->with(['user'])
  ->join('users', 'users.id', '=', 'bookings.user_id')
  ->defaultSort('start_time')
  ->allowedSorts(['users.name', 'start_time', 'end_time'])
  ->paginate(15);
```

Not sure if this approach will work all kinds of relationships though...

**Comment by brendt** [comment]
Full disclosure: I manually define the joins in my project, so it might very well be possible that `with` doesn't work the way I thought it would.

**Comment by matthias-schmitt** [comment]
@mikaeljorhult @brendt 

Thank you - that´s also what I ended up with.


Would be cool to have something similiar to the custom filter classes.

`        ->allowedSorts(Sort::custom('column', SortColumn::class))`

Unfortunatelly I don´t have much time at the moment to prepare a PR or discuss the topic further.

Maybe someone else?

**Comment by brendt** [comment]
Let's discuss it further. I'm more than willen to submit it PR for this, as I'm doing a lot of manual JOINs at the moment. The solution should be flexible enough though.

From your example, @matthias-schmitt ; I guess `SortColumn::class` is the model class of the relation you're referring to? So it would be something like this?

```php
Sort::custom('users.name', User::class)
```

Becoming this:

```php
->join('users', 'users.id', '=', 'bookings.user_id')
->allowedSorts(['users.name'])
```

There's a few places where we should make assumptions on names with this approach (`bookings.user_id` and `users.id`).

Wouldn't it be better if we'd allow sorts on relations?

```php
->allowedSorts(Sort::relation('user.name', 'user'))
```

As the relation is defined on the model we're querying, we can simply get it from there, and build the join ourselves. I think it might even be possible to use the relation itself to add the join statement to the query.

**Comment by freekmurze** [comment]
Will likely be solved with #91

**Comment by fico7489** [comment]
yeah, you can't order by related table without join tables manually, but if you want to join other tables it is a really awkward and you must be very careful and pay attention to many things. I created a package that solves that problem, you can check my concept, every feedback is welcome : 

https://github.com/fico7489/laravel-eloquent-join

**Comment by bcorcoran** [comment]
For anyone that needs to do this in 2021, on v3:

First, create a custom sort class, then the contents of your `__invoke` function should look like this:

```php

        $direction = $descending ? 'DESC' : 'ASC';

        $query->orderBy(
            Relationship::select('relationship_field')
                ->whereColumn('relationship.id', 'relationship_id')
        );

```

relationship_id = your current model's relationship id field. This is just an example of a hasOne/BelongsTo.

**Comment by jamols09** [comment]
> For anyone that needs to do this in 2021, on v3:
> 
> First, create a custom sort class, then the contents of your `__invoke` function should look like this:
> 
> ```
>         $direction = $descending ? 'DESC' : 'ASC';
> 
>         $query->orderBy(
>             Relationship::select('relationship_field')
>                 ->whereColumn('relationship.id', 'relationship_id')
>         );
> ```
> 
> relationship_id = your current model's relationship id field. This is just an example of a hasOne/BelongsTo.

I know this is too much to ask. but is there a way for me to filter a relation within a relationship?

```
//SortInvoiceByUtilityTypeName
        return $query->orderBy(
            Utility::select('name')
                ->join('utility_types','utilities.id', '=', 'utility_types.id')
                ->whereColumn('invoices.utility_id', 'utilities.id'),
                $descending ? 'desc' : 'asc'
        );
```

**Comment by jamols09** [comment]
> For anyone that needs to do this in 2021, on v3:
> 
> First, create a custom sort class, then the contents of your `__invoke` function should look like this:
> 
> ```
>         $direction = $descending ? 'DESC' : 'ASC';
> 
>         $query->orderBy(
>             Relationship::select('relationship_field')
>                 ->whereColumn('relationship.id', 'relationship_id')
>         );
> ```
> 
> relationship_id = your current model's relationship id field. This is just an example of a hasOne/BelongsTo.

This is really helpful and I've use this a lot. However I have a pivot table it doesn't have a model but how can custom sort be implemented for pivot table's columns ?

**Comment by bcorcoran** [comment]
> > For anyone that needs to do this in 2021, on v3:
> > First, create a custom sort class, then the contents of your `__invoke` function should look like this:
> > ```
> >         $direction = $descending ? 'DESC' : 'ASC';
> > 
> >         $query->orderBy(
> >             Relationship::select('relationship_field')
> >                 ->whereColumn('relationship.id', 'relationship_id')
> >         );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > relationship_id = your current model's relationship id field. This is just an example of a hasOne/BelongsTo.
> 
> This is really helpful and I've use this a lot. However I have a pivot table it doesn't have a model but how can custom sort be implemented for pivot table's columns ?

You could implement another subquery.

I re-implemented the above function slightly differently to satisfy phpstan:

```php
public function __invoke(Builder $query, bool $descending, string $property)
    {
        $direction = $descending ? 'DESC' : 'ASC';

        // Below is equivalent to: Person::select($property)->whereColumn('people.id', 'person_id')
        // We're using a standard DB call to return Illuminate\Database\Query\Builder to satisfy static analysis
        $subQuery = DB::table(with(new Person())->getTable())
            ->select($property)
            ->whereColumn('people.id', 'person_id');

        $query->orderBy($subQuery, $direction);
    }
```

**Comment by jamols09** [comment]
Seems that it's not working as of now. The `with()` doesn't work correctly maybe because I use don't use beta version of `Illimunate/database 9.0` (this requires me to have 9.0 version for `spatie/laravel-query-builder 5.0.0` the furthest I could update is 4.0.3

```
$sub = DB::table(with(new Branch())->getTable())
            ->select($property)
            ->whereColumn('branches.id', 'branch_id');
        $query->orderBy($sub, $direction);
```
`error: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'branch_item.is_active' in 'field list' (SQL: select * from `items` where exists (select * from `branches` inner join `branch_item` on `branches`.`id` = `branch_item`.`branch_id` where `items`.`id` = `branch_item`.`item_id` and `branches`.`id` = 16 and `branches`.`deleted_at` is null) and `items`.`deleted_at` is null order by (select `branch_item`.`is_active` from `branches` where `branches`.`id` = `branch_id`) desc limit 30 offset 0)"
`

**Comment by musiwei** [comment]
> ```
> Relationship::select
> ```

What is `Relationship::select`? I am using Laravel 9 and the only Relationship class I can find is \Illuminate\Database\Eloquent\Factories\Relationship...

**Comment by bcorcoran** [comment]
> > ```
> > Relationship::select
> > ```
> 
> What is `Relationship::select`? I am using Laravel 9 and the only Relationship class I can find is \Illuminate\Database\Eloquent\Factories\Relationship...

Your model name. Sorry, I should have been more clear. i.e. "Person::select"

**Comment by anthonymf** [comment]
It is not strictly necessary to use a custom sort class because you can sort by related properties using dot-notation if you add a join and a select table.* like this:

```php
$query = QueryBuilder::for(YourModel::class)
    ->allowedSorts([
        AllowedSort::field('friendlyLookingSortName', 'RelationTableName.sortField'),
    ])
    // add select *
    ->select('YourModelTableName.*')
    // conditionally add applicable joins to enable sorting on related properties using dot notation
    ->when(str_contains(request()->sort, 'friendlyLookingSortName'), function ($query) {
        return $query->join('RelationTableName', 'RelationTableName.foreignKeyField', '=', 'YourModelTableName.localKeyField');
    })
    
```

It's also worth noting that [joins are typically faster than subqueries](https://reinink.ca/articles/ordering-database-queries-by-relationship-columns-in-laravel).

**Comment by j2L4e** [comment]
This version works with the dot-notation property names.
It splits $property into relation and column name to get the relation and corresponding keys from the QueryBuilder. It uses subqueries, so it's not fast, but it works out-of-the-box and doesn't have side-effects on the original $query.

```
$query = QueryBuilder::for(Model::class)
    ->allowedSorts([
        AllowedSort::custom("customer.name", new RelatedSort()),
    ])
```

```php
use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\Sorts\Sort;

class RelatedSort implements Sort
{
    public function __invoke(Builder $query, bool $descending, string $property)
    {
        [$relationName, $columnName] = explode(".", $property);

        $relation = $query->getRelation($relationName);

        $subquery = $relation
            ->getQuery()
            ->select($columnName)
            ->whereColumn($relation->getQualifiedForeignKeyName(), $relation->getQualifiedOwnerKeyName());

        $query->orderBy($subquery, $$descending ? "desc" : "asc");
    }
}
```

**Comment by chimit** [comment]
@j2L4e it throws `Call to undefined method Illuminate\Database\Eloquent\Relations\HasOneThrough::getQualifiedOwnerKeyName()` for me.

**Comment by j2L4e** [comment]
It only works for direct relations OOTB. It shouldn't be too much effort to make it work, though. You can check the API of `HasOneThrough` over here: https://laravel.com/api/9.x/Illuminate/Database/Eloquent/Relations/HasOneThrough.html

**Comment by kaydenvanrijn** [comment]
> This works with dot-notation property names. It splits $property into relation and column name to get the relation and corresponding keys. It uses subqueries, so it's not fast, but it works out-of-the-box and doesn't have side-effects on the original $query.
> 
> ```php
> $query = QueryBuilder::for(Model::class)
>     ->allowedSorts([
>         AllowedSort::custom("customer.name", new RelatedSort()),
>     ]);
> ```
> 
> ```php
> use Illuminate\Database\Eloquent\Builder;
> use Spatie\QueryBuilder\Sorts\Sort;
> 
> class RelatedSort implements Sort
> {
>     public function __invoke(Builder $query, bool $descending, string $property)
>     {
>         [$relationName, $columnName] = explode(".", $property);
> 
>         $relation = $query->getRelation($relationName);
> 
>         $subquery = $relation
>             ->getQuery()
>             ->select($columnName)
>             ->whereColumn($relation->getQualifiedForeignKeyName(), $relation->getQualifiedOwnerKeyName());
> 
>         $query->orderBy($subquery, $descending ? "desc" : "asc");
>     }
> }
> ```
> 
> edit: Doesn't work with `HasOneThrough` relations

For this to work with MorphToMany relationships, I changed to code to this:

```php
class RelatedSort implements Sort
{
    public function __invoke(Builder $query, bool $descending, string $property)
    {
        [$relationName, $columnName] = explode('.', $property);

        /** @var \Illuminate\Database\Eloquent\Relations\MorphToMany $relation */
        $relation = $query->getRelation($relationName);

        $subquery = $relation
            ->getQuery()
            ->select($columnName)
            ->whereColumn($relation->getQualifiedForeignPivotKeyName(), $relation->getQualifiedParentKeyName());

        $query->orderBy($subquery, $descending ? 'asc' : 'desc');
    }
}
```

I'm using this package in conjunction with the https://github.com/spatie/laravel-permission package, so my use case is to sort a list of users by role name/type so superusers are at the top:

```php
class StaffController extends BaseController
{
    public function index()
    {
        $sort = AllowedSort::custom('roles.name', new RelatedSort());
        $query = QueryBuilder::for(User::class)
            ->staff()
            ->allowedSorts($sort)
            ->defaultSort($sort);

        return Inertia::render('admin/staff/Index', [
            'users' => UsersResource::collection($query->paginate()),
        ]);
    }
}
```

**Comment by dawidlipinski** [comment]
@kaydenvanrijn what if the related entity is in a separate schema?

I have all my core entities in 'public' schema and all the other stuff in 'lookup' schema.
I'm using postgres.
My example is: I have products that belongTo productCategory. Product categories are in lookup schema.
When using RelatedSort class I am getting following error when sorting by ?sort=productCategory.name

> Undefined table: 7 ERROR: relation "product_category" does not exist 

It works when related entity is in the same schema, e.g. I wanted to sort my customers by accountManager relation.
Both customers and AMs are in public schema, therefore ?sort=accountManager.name works perfectly fine.

**Comment by vovarudomanenko** [comment]
@j2L4e Awesome solution. I just had to tweak a little bit your solution to make it work with HasMany relation

```php
$subquery = $relation->getQuery()
    ->select($columnName)
    ->whereColumn(
       $relation->getQualifiedForeignKeyName(),
       $relation instanceof HasMany ? $relation->getQualifiedParentKeyName(): $relation->getQualifiedOwnerKeyName()
   );
```
