### ISSUE TITLE
camelCase is converted into underscore when selecting columns in a relation in camelCase

### ISSUE THREAD

**Issue by xLesterGG** [spatie/laravel-query-builder#366]
Hello!

When I try to select a relationship's camelCase relationship's field, it is converted to underscore format.

For example:
If I call to 

`/branches?include=userInCharge&fields[userInCharge]=user_uid` 

it throws this error:

`Requested field(s) user_in_charge.user_uid are not allowed. Allowed field(s) are userInCharge.user_uid.`

Is this an intended behavior, or are any workaround around this besides changing the relation name?

Versions
Package: 2.3.0
Laravel: 5.8.13

**Comment by AlexVanderbist** [comment]
Hi! This is actually intended behaviour. The `?fields[foo]=bar` parameter is use to add `select` clauses for a certain **table** to the query. This doesn't work for included relationships. For example `?fields[users]=id,name` will add `SELECT users.id, users.name [...]` to the underlying query.

Have a quick read through the docs here: https://docs.spatie.be/laravel-query-builder/v2/features/selecting-fields/#selecting-fields-for-included-relations

In your case, using `/branches?include=userInCharge&fields[users]=id,user_uid` should work as we respect the selected fields when including a relationship. (also, notice the added `id` in the fields parameter, this is required and explained at the bottom of the page here: https://docs.spatie.be/laravel-query-builder/v2/features/selecting-fields/#selecting-fields-for-included-relations).

Good luck and feel free to open a new issue if you still need help with this.
