### ISSUE TITLE
Wrap filters in a Where clause [ADVICE]

### ISSUE THREAD

**Issue by denitsa-cm** [spatie/laravel-query-builder#367]
First, thank you for this package! Makes things look really neat :)

Now onto my question...

I want to have a query, where I apply some custom filters based on query params, and then continue chaining onto my query. For this to work though, I need all my custom filters wrapped in a constraint group (with a where clause), which I am struggling to achieve. 

Here is some code:

This is the filters being applied:

```
        return QueryBuilder::for(SubscriptionPeriod::select('subscription_periods.*'))
            ->allowedFilters([
                AllowedFilter::custom('current', new SubscriptionPeriodCurrentFilter()),
                AllowedFilter::custom('future', new SubscriptionPeriodFutureFilter()),
                AllowedFilter::custom('inactive', new SubscriptionPeriodInactiveFilter()),
                AllowedFilter::custom('oneTimePurchase', new SubscriptionPeriodOneTimePurchaseFilter()),
            ]);
```

All these custom filters look similarly to this:

```
class SubscriptionPeriodCurrentFilter implements Filter
{
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        return $query->orWhere(function ($query) {
            return $query->current();
        });
    }
}
```

I use an `orWhere` because I want an OR condition to those (they can be applied simultaneously).

Now, after that has happened I want to apply some more sorts, like searching for the name of the subscription. However, that should be an `AND` filter that is applied after all those ORs.

And in order to do that I need to wrap all the custom filters inside a 

```
$query->where(function ($query) {
  // query param filters go here
})->where( .. here I continue with my other search filters );
```

Do you have any tips on how to achieve this in a clean way? :) 

I understand that this is not a bug but a question, but maybe someone here has stumbled into the same issue.

**Comment by AlexVanderbist** [comment]
Hi! This is an interesting use-case that we haven't come across yet. Did you find a solution for this in the last couple of weeks? 

I couldn't find a way to make this work with the package as it is right now. 
We could probably get away with wrapping all allowed filters in a `where` clause - regardless of the rest of the query. However, I'm not sure how this impacts existing queries with multiple AND/OR filters in combination with extra `where` clauses - so this would definitely be a breaking change.

**Comment by denitsa-cm** [comment]
Hey @AlexVanderbist!

Since I couldn't achieve it with the query builder, I made up my own code to do it :) 

Would love to have it built in though, because it limits how much I can use it in cases with chaining.

```
<?php
declare(strict_types=1);

namespace App\Queries\SubscriptionPeriods;

use App\Filters\FiltersFromRequestTrait;
use App\Filters\SubscriptionPeriodCurrentFilter;
use App\Filters\SubscriptionPeriodFutureFilter;
use App\Filters\SubscriptionPeriodInactiveFilter;
use App\Filters\SubscriptionPeriodOneTimePurchaseFilter;
use App\Models\SubscriptionPeriod;
use App\Queries\QueryInterface;

class SubscriptionPeriodsWithFilters implements QueryInterface
{
    use FiltersFromRequestTrait;

    private $current = false;
    private $future = false;
    private $inactive = false;
    private $oneTimePurchase = false;

    public function get(): \Illuminate\Database\Eloquent\Builder
    {
        return SubscriptionPeriod::select('subscription_periods.*')->where(function ($query) {
            $query->when($this->current, function ($query) {
                (new SubscriptionPeriodCurrentFilter)($query, null, '');
            })->when($this->future, function ($query) {
                (new SubscriptionPeriodFutureFilter)($query, null, '');
            })->when($this->inactive, function ($query) {
                (new SubscriptionPeriodInactiveFilter())($query, null, '');
            })->when($this->oneTimePurchase, function ($query) {
                (new SubscriptionPeriodOneTimePurchaseFilter())($query, null, '');
            });
        });
    }
}
```

(trait code sets the filter variables)

**Comment by AlexVanderbist** [comment]
That's fair enough. I've tagged this to be revisited when we tag the next major version of the package as it's a pretty breaking change. Thanks for opening the issue!
