### ISSUE TITLE
Does QueryBuilder need to be tied to a Request?

### ISSUE THREAD

**Issue by natepisarski** [spatie/laravel-query-builder#371]
I'm in a situation where I'd like to build up a `QueryBuilder` instance from data gathered from code.

For instance, I do some calculation, and determine that I want:

* All users with a `first_name` of `Joe`
* ...who have a `sex` of `male `

The URL for this would be: `filter[first_name]=Joe&filter[sex]=male`

However, QueryBuilder builds its parameters from a `Request` object **only**. So, it's impossible to add new filters programmatically, or build up queries outside of the request cycle.

I'd like a back-door into the `QueryBuilder` (some static method maybe?) where I can give it an array/Collection of the shape:

```php
[
    'filter[first_name]' => 'Joe',
    'filter[sex]'            => 'male'
]
```

or 

```php
[
    ['filter[first_name]', 'Joe'],
    ['filter[sex]', 'male']
]
```

---

Is there a reason that `Request` is important for QueryBuilder to run? Or could it be re-configured to run against an array to make it more flexible?

I wouldn't mind implementing this myself, I just wanted more background on why things are built like this.

**Comment by djunehor** [comment]
Doesn't that defeat the whole purpose of the package which is to build query from incoming REQUESTS?

**Comment by natepisarski** [comment]
@djunehor idk, I guess that's actually what I'm asking. Is the project strongly coupled with Requests by design, or by oversight?

I can totally see a use-case where we have a method that just builds one of these QueryBuilders from the array I posted earlier. Then, the Request can just turn into one of those Arrays. So, under the hood, the QueryBuilder understands Arrays and Arrays only; meanwhile, most people use it as part of a request.

But if that defeats the purpose of the project I can 100% just fork it off.

**Comment by djunehor** [comment]
From the codebase, I'll say the QueryBuilder is strongly couped with Requests as it leverages the Request methods and properties. Switching to arrays/objects might be a major change even though I know Request object can be created from an array by using
`$request = new Illuminate\Http\Request($test_array);`
And properties can be added to the request object i.e `$request->newProperty = $property;`

Perhaps, you can create a PR to this effect with tests that ensure backward compatibility?

**Comment by PiranhaGeorge** [comment]
FWIW I really don't think the dependency on the request is desirable. It would be much better to add an interface for `QueryBuilderRequest` and depend upon that instead. The `QueryBuilder` appears to only use methods of that class for request data anyway - so no-brainer really.

I had to hack around this on a previous n-tier project as the pertinent request data needed to be serialised and passed through a service layer first. Passing a request would have been all sorts of wrong.

**Comment by natepisarski** [comment]
I'll see if I can take a whack at this when I get some free time. If it's not possible without rewriting large chunks of the project I'll likely fork it off. If I can make it a more non-invasive change I'll definitely add some tests, just to make sure it's backwards-compatible. Thanks for your thoughts guys

**Comment by klimov-paul** [comment]
In general I agree that `Request` dependency is redundant here.
However it is not a big deal to convert plain array into `Request` instance.
It is done at the unit tests of this project.

The actual code would be like following:

```php
use Illuminate\Http\Request;
use Spatie\QueryBuilder\QueryBuilder;

QueryBuilder::for(Item::class, new Request([
    'filter' => [
        'first_name' => 'John',
    ],
]))
    ->allowedFilters(...)
   // ...
```

It might be considered as overhead, but it is better then creating a fork, in my opinion.

**Comment by AlexVanderbist** [comment]
@klimov-paul back at it again with a great suggestion. 

If anyone wants to add `QueryBuilderRequest` as an interface to use custom implementations (like the one using arrays), feel free to send a PR. I'm more than happy to merge that in :)

**Comment by klimov-paul** [comment]
You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) instead. It is not tied to `Request` class.

**Comment by rizaldywirawan** [comment]
> You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) instead. It is not tied to `Request` class.

Is your package still actively maintained? I would like to try because I guess this one is more suitable for action class.

**Comment by klimov-paul** [comment]
> Is your package still actively maintained?

It is.
