### ISSUE TITLE
the example in test not working in production

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#373]
i want to sort my model by its relation attribute so i look at test given in tests as below :
```
   /** @test */
    public function it_can_sort_a_query_by_a_related_property()
    {
        $request = new Request([
            'sort' => 'related_models.name',
            'includes' => 'relatedModel',
        ]);
        $sortedQuery = QueryBuilder::for(TestModel::class, $request)
            ->allowedIncludes('relatedModels')
            ->allowedSorts('related_models.name')
            ->toSql();
        $this->assertEquals('select * from "test_models" order by "related_models"."name" asc', $sortedQuery);
    }
```
and i do the same in my code like below : 
```
public function scopeFilter()
    {
        $data = QueryBuilder::for(Accommodation::class)
            ->allowedFilters([        
                AllowedFilter::scope('name'),
                AllowedFilter::scope('accommodation_facility')            ])
            ->allowedAppends(['cheapestroom'])
            ->allowedIncludes(['gallery','city','accommodationRooms','accommodationRooms.roomPricingHistorySearch','discounts','prices'])
                       ->allowedSorts('prices.sale')
            ->paginate(12);
        return FilterResource::collection($data);
```

now according to test and doc it should sort the by the sale colomn in price relation but it wont do it . any idea how can that be done or its a bug ???

**Comment by farshadff** [comment]
even when i run the raw query which is written in test it would throw me error this is the query :
```
        $this->assertEquals('select * from "test_models" order by "related_models"."name" asc', $sortedQuery);
```
any one has any idea ???

**Comment by AlexVanderbist** [comment]
Are you still having this issue? What's the error being thrown?

Not all eloquent relationships work the same way with the default `->sortBy()`. It's a bit tricky.

**Comment by farshadff** [comment]
@AlexVanderbist  yes i still have the issue and i dont get any errors it just dont work  as the example , have you ever used the nested attribute sort your self ?? or any one else

**Comment by irineujunior** [comment]
Same here.
The test is good, but this query dosent work.
`select * from "test_models" order by "related_models"."name" asc`
You cant order by `related_models` without a join for example.

Error message:
`Column not found: 1054 Unknown column 'related_models.name' in 'order clause'`
