### ISSUE TITLE
Add `limit` parameter 

### ISSUE THREAD

**Issue by atymic** [spatie/laravel-query-builder#376]
Hey :)

This library is awesome, but one thing i've been missing is the ability to limit the amount of results. 

I think this would be pretty simple to add, so if you are happy I can PR :)

**Comment by klimov-paul** [comment]
Instead of having a 'limit' option there should be control over pagination page size (per page).
Regular SQL 'limit' and 'offset' directives are represented as pagination already.

In order to get the first records the request URL will look like following:
```
http://example.com/api/items?page=1&per_page=1
```

**Comment by AlexVanderbist** [comment]
You can use https://github.com/spatie/laravel-json-api-paginate in combination with this package to accomplish this. The pagination package has a `?page[size]=123` option and adheres to the JSON API spec. 

https://docs.spatie.be/laravel-query-builder/v2/advanced-usage/pagination/

Good luck!

**Comment by klimov-paul** [comment]
You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) for the integrated pagination solution.
