### ISSUE TITLE
Argument 1 passed to Illuminate\Database\Eloquent\Builder::__construct() must be an instance of Illuminate\Database\Query\Builder, instance of Illuminate\Database\Eloquent\Builder given

### ISSUE THREAD

**Issue by Davidnadejdin** [spatie/laravel-query-builder#377]
I want to do so
![image](https://user-images.githubusercontent.com/40993387/68747599-b2647380-061c-11ea-93b5-81f7d12806b9.png)

And getting an error
```Argument 1 passed to Illuminate\Database\Eloquent\Builder::__construct() must be an instance of Illuminate\Database\Query\Builder, instance of Illuminate\Database\Eloquent\Builder given```

What is the point of binding tightly to a specific implementation of Query Builder?

**Comment by danilopinotti** [comment]
I had the same problem;
I had to create a new builder and doing the relationship manually.

**Comment by Davidnadejdin** [comment]
> I had the same problem;
> I had to create a new builder and doing the relationship manually.

I did so `$model->relation()->getQuery()`
