### ISSUE TITLE
How can I modify a query for a relationship?

### ISSUE THREAD

**Issue by Davidnadejdin** [spatie/laravel-query-builder#378]
I would like to set sorting, apply scope, limit the number of records received

**Comment by AlexVanderbist** [comment]
Hi! Most of this is documented here: https://docs.spatie.be/laravel-query-builder

- sorting relationships: use the default sorts with dot notation. This sometimes work. You'll probably need custom sorts tho. It's in the docs: https://docs.spatie.be/laravel-query-builder/v2/features/sorting/#custom-sorts
- apply scopes: use scoped filters. Need them on relationships? Use custom filters: https://docs.spatie.be/laravel-query-builder/v2/features/filtering/#custom-filters
- limit the number of records received: in general, use our pagination package (as described in the docs: https://github.com/spatie/laravel-json-api-paginate). For relationships, use custom includes. They're undocumented but work virtually the same as custom filters or sorts.

If you need help with anything more specific that's not documented, feel free to open a new issue.
