### ISSUE TITLE
Add `FilterTrashed`

### ISSUE THREAD

**Issue by klimov-paul** [spatie/laravel-query-builder#382]
It would be nice to support soft deleted records filtering out of the box.

It can be encapsulated into dedicated `FilterTrashed` filter, which will respond in way similar to the one Nova does. It would respond to `trashed` keyword: if it is empty - do not apply any scope, if it equals to 'with' - include trashed records, if equals to 'only' - display only trashed records.

**Comment by klimov-paul** [comment]
PR: #383

**Comment by AlexVanderbist** [comment]
I like this a lot! Let's continue this discussion in the PR :)
