### ISSUE TITLE
sort camelCase (Api) vs snake_case (laravel)

### ISSUE THREAD

**Issue by drjdr** [spatie/laravel-query-builder#384]
Vue: Query:
posts/?sort=firstName

Laravel
->allowSorts(["firstName"]) -> will not be able to sort on this item
->allowSorts(["first_name]) -> required front end to use posts/?sort=first_name as well, because firstName is not allowed

Fix:
QuerybuilderRequest: convert sorts() collection items from "firstName" -> "first_name"
```
 public function sorts(): Collection
    {
        $sortParameterName = config('query-builder.parameters.sort');

        $sortParts = $this->query($sortParameterName);

        if (is_string($sortParts)) {
            $sortParts = explode(',', $sortParts);
        }

        return collect($sortParts)->map(function ($value, $key) {
            return strtolower(preg_replace(['/([a-z\d])([A-Z])/', '/([^_])([A-Z][a-z])/'], '$1_$2', $value));
        })->filter();
    }
```

**Comment by drjdr** [comment]
same for filters

**Comment by AlexVanderbist** [comment]
We prefer not to change the filter column names as people may use either camelCase or snake_case for their database columns. So forcing all filters to be snake_case actually forces everyone to use snake_case column names.

As a fix you can use aliases. This example will allow sorting by `?sort=firstName` but will use the `first_name` column.
```php
    QueryBuilder::for(User::class)
            ->allowedSorts([AllowedSort::field('firstName', 'first_name')])
            ->get();
```

Alternatively you can do the string conversion on the font-end :) 

Good luck and feel free to open a new issue if you have any other questions.
