### ISSUE TITLE
Query builder with Pagination and Fractal

### ISSUE THREAD

**Issue by zoroaster88** [spatie/laravel-query-builder#391]
I am trying to combine laravel-fractal with this package.

Before I do something like this:

```php

        $paginator = $user->paginate();
        $users = $paginator->getCollection();

        return Fractal::collection($users, UserTransformer::class)
            ->serializeWith(new JsonApiSerializer())
            ->paginateWith(new IlluminatePaginatorAdapter($paginator))
            ->respond(200);
```

I was able to find a solution without pagination, but I am not sure how to pass $paginator to paginateWith().

I come out with below solution, but I am doing something wrong, because pagination show like all results, but data show just 2 when using filter. This because I get paginator for all users, since I am not sure how to get paginator for filtered users, to pass to paginateWith().

This is my current updated code:

```php
       // This get paginator for all users, but I must get just for filtered result
        $paginator = $user->paginate();

        $users = QueryBuilder::for($user->query())
            ->allowedFilters(['name', 'email'])
            ->paginate() // I must return this
            ->appends(request()->query());

        return Fractal::collection($users, UserTransformer::class)
            ->serializeWith(new JsonApiSerializer())
            ->paginateWith(new IlluminatePaginatorAdapter($paginator))
            ->respond(200);
```

Any help much appreciated!

Thanks

**Comment by zoroaster88** [comment]
After posting this, and reading my own question, I come up with a solution that works :)

But I am not sure if I am doing something wrong.

Here is my updated code:

```php

        $users = QueryBuilder::for($user->query())
            ->allowedFilters(['name', 'email']);

        $paginator = $users->paginate(); // Get paginator

        $users = $paginator->appends(request()->query()); // Get users

        return Fractal::collection($users, UserTransformer::class)
            ->serializeWith(new JsonApiSerializer())
            ->paginateWith(new IlluminatePaginatorAdapter($paginator))
            ->respond(200);

```

**Comment by stefanriehl** [comment]
I solved this by installing the [https://github.com/spatie/laravel-json-api-paginate](https://github.com/spatie/laravel-json-api-paginate) package and the  [https://github.com/spatie/laravel-fractal](https://github.com/spatie/laravel-fractal) package.

My code looks like this:

`
        $items = QueryBuilder::for(Project::class)
            ->allowedFilters(...)
            ->allowedSorts(...)
            ->allowedFields(...)
            ->jsonPaginate();

        return fractal()
            ->collection($items, <your transformer>)
            ->paginateWith(new IlluminatePaginatorAdapter($items))
            ->respond(200);
`

**Comment by AlexVanderbist** [comment]
I was gonna propose just the `laravel-json-api-paginate` package as well! Does this work for you as well?

Feel free to close this issue if you don't have any other questions :)

**Comment by thewebartisan7** [comment]
Why you are proposing to use yet another package for paginate? It's better than how I do it? I prefer to keep less package possible when I can.

**Comment by AlexVanderbist** [comment]
@thewebartisan7 How you solve the issue of pagination is up to you. For me it's easier to suggest someone install a package, instead of having to explain the code that's in that package so they can code it themselves. Either way, the issue described here can be fixed with Laravel's default paginator or the package if you want the features included there. The package's paginator is maybe 100 LOC so you can easily copy paste that to your own codebase if you don't want to use packages.

Good luck!

(closing this as it's solved)
