### ISSUE TITLE
Query Filters with operator from client

### ISSUE THREAD

**Issue by garazpasir** [spatie/laravel-query-builder#392]
I am interested in applying filters with operators (supported by SQL) that can be set from the client.
Example:
`filter[author.name][eq]=John` will display a title that has the exact value of John.

Reference:
- [JSON API Fancy Filters (jsonapi module for Drupal)](https://gist.github.com/e0ipso/efcc4e96ca2aed58e32948e4f70c2460)
- [Filter on (nested) relationship attribute?](https://discuss.jsonapi.org/t/filter-on-nested-relationship-attribute/1275) (scott.werner.vt's answer).

how do i achieve it?

**Comment by AlexVanderbist** [comment]
Hi! We don't currently support this as it's not in the official JSON API specs. However, you can achieve this using a custom filter if you're willing to build it yourself.

There's also this PR that does something similar: https://github.com/spatie/laravel-query-builder/pull/223. 

Btw, if you end up building this as a single nice custom filter, feel free to send a PR and maybe we can consider adding this to the package.

Thanks and good luck!
