### ISSUE TITLE
Is there a way to prevent relationships being converted to camel case?

### ISSUE THREAD

**Issue by AlexGodbehere** [spatie/laravel-query-builder#393]
Is there a way to prevent this package from converting relationship names to `camelCase`? All of the relationships in my application are `snake_case`.

**Comment by AlexVanderbist** [comment]
Currently there isn't... I wrongly assumed camel casing relationships was required or best practice for Laravel. 

I'm open for suggestions tho (maybe looking for the matching relationship regardless of case?) - feel free opening a new issue if you want to discuss implementing this :)

**Comment by pionl** [comment]
Hi there, I've got the same problem. My point of view is, that it should not convert the includes array and leave it as it is (so, if you have myRelation, you should use includes(['myRelation')).

Of course it would break current applications using the query builder - I've would suggest to use a config that would turn this behavior. Should I make a PR?

**Comment by suth** [comment]
I've also run into this issue. Seeing as how the conversion was built around an incorrect I see no reason to leave that mistake in place. I tried extending the `AllowedInclude` class to omit the camel casing, but it seemed like there was somewhere else I missed that was applying it as well.
