### ISSUE TITLE
Sorting by json object

### ISSUE THREAD

**Issue by ugurdnlr** [spatie/laravel-query-builder#394]
Hi,

How can I sort by json object?

For example,
I keep the 'body' field as json and i want to default sort by the 'name' object inside the 'body' field.

**Comment by AlexVanderbist** [comment]
The following works out of the box!

```php
    QueryBuilder::for(User::class)
            ->allowedSorts(['body->name'])
            ->get();
```
and the following query: `?sort=-name->first`. Weird syntax but you could use sort aliases as well: https://docs.spatie.be/laravel-query-builder/v2/features/sorting/#using-an-alias-for-sorting

Good luck and feel free to open a new question if you have any other questions :)
