### ISSUE TITLE
Error Spatie-activity-log with spatie-query-builder

### ISSUE THREAD

**Issue by gutofurlan** [spatie/laravel-query-builder#405]
In my Laravel project (5.8) I have the laravel activitylog package (3.2.2) with the database connection specifying "log", but as soon as I put the spatie-query-builder (2.2.0) it crashes and doesn't recognize the log connection, trying to insert in the master base where there is no table.
Does anyone know how to solve?
Thank

**Comment by dominikb** [comment]
I will look into this. Can you provide a sample configuration for me to reproduce this issue?

**Comment by gutofurlan** [comment]
I resolved, i update dependences for packages, thanks ...
