### ISSUE TITLE
Support https://github.com/GeneaLabs/laravel-model-caching package

### ISSUE THREAD

**Issue by cvgeldern** [spatie/laravel-query-builder#407]
It would be nice to let this wonderful package play together with popular packages with related functionality that is out of scope of this package itself. 

I'm in need of a compatible eloquent/model caching package and GeneaLabs/laravel-model-caching caught my eye.

**Comment by freekmurze** [comment]
If this can be done in an easy, non-breaking, testable way, please submit a PR for it.
