### ISSUE TITLE
QueryBuilder::for() with relationship

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-query-builder#411]
I've found this test after I tried to use the QueryBuilder on a relationship method in a sub-resource controller.
The solution I've found is to call `getQuery()` on the relationship method before passing it into the builder. This way `getQuery()` is called twice and the resulting query is a plain database one instead of an eloquent one.
Would it be an option to check if the query is a relation one and call `getQuery()` twice?

https://github.com/spatie/laravel-query-builder/blob/d0d82095138f961241c81efe0a40147009ad6d4d/tests/QueryBuilderTest.php#L172-L193

**Comment by AlexVanderbist** [comment]
This will be fixed in v3 via https://github.com/spatie/laravel-query-builder/pull/443. Thanks!
