### ISSUE TITLE
Livewire

### ISSUE THREAD

**Issue by bbcreation** [spatie/laravel-query-builder#417]
Hi; Is it possible to use with Livewire?

Too few arguments to function Illuminate\Support\Collection::get(), 0 passed in /Users/.../Documents/GitHub/.../vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php on line 23 and at least 1 expected (View: /Users/.../Documents/GitHub/.../vendor/livewire/livewire/src/Macros/livewire-view.blade.php)

**Comment by freekmurze** [comment]
That error doesn't seem related to our package.

Our package and Livewire do not interact directly with each other, so sure, you could use them both in the same project.
