### ISSUE TITLE
The response doesn't contain information about filters. How to return filters ?

### ISSUE THREAD

**Issue by JeremyPinto** [spatie/laravel-query-builder#424]
I try to use the next_page_url variable in my front app, but it doesn't contain any information about current filters. 

The controller endpoint is : 
```php
return QueryBuilder::for(Article::class)
    ->allowedFilters(['category'])
    ->paginate(6)
```

If I request the category "Laravel", I get articles in this category, but the next_page_url is : 
```api/articles?page=2```

I don't have any information that the query is filtered with the category "Laravel", so I will have ALL articles.

How to get filters in the Response ?

I would like to get something like this for next_page_url : 
```api/articles?page=2&filter[category]=Laravel```

If not possible for any reason, I would expect to get current filters in the response.

**Comment by JeremyPinto** [comment]
I found the answer in the doc : https://docs.spatie.be/laravel-query-builder/v2/advanced-usage/pagination/

**Comment by klimov-paul** [comment]
You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) for the integrated pagination solution.
