### ISSUE TITLE
Add feature filter/sort in JSON 

### ISSUE THREAD

**Issue by tabuna** [spatie/laravel-query-builder#43]
I propose to add the ability to filter and sort for fields containing JSON:

Model (example), `content` - Is a JSON or JSONB field.
```
namespace App;

use Illuminate\Database\Eloquent\Model;

class Flight extends Model
{
    /**
     * @var array
     */
    protected $casts = [
        'content' => 'array',
    ];
}
```

Laravel can handle this:
```
// filter
Flight::where('content->en->name', 'alexandr')->get();

// sort
Flight::orderBy('content->en->name', 'desc')->get();
```

My suggestion is to enable filtering and sorting for such things. 
Defining allowed as `content`:

Filtering an API request: `/users?filter[content][en][name]=alexandr`:

```
$flight = QueryBuilder::for(Flight::class)
    ->allowedFilters('content')
    ->get();
```

To avoid overlapping several conditions using the same array. 
You can add a check, for example:

```php
if($query->getModel()->hasCast($property,['object','array'])){

}
```

-----

I hope for your understanding. Thank you.

**Comment by AlexVanderbist** [comment]
Hi! Thanks for the suggestion. I've been coming back to this issue a couple of times last week. If Laravel supports this using the simple `content->en->name` notation I'd love to implement it in this package as well. 

For the URL structure I'm still unsure. Preferably we do not use the nested arrays notation (`/users?filter[content][en][name]=alexandr`) to avoid the issue of fields overlapping altogether.

The JSON API specification (which this package is based on) doesn't specify a clear URL to filter or sort by JSON fields either. For related resources the dot notation is used (just like we're used to in Laravel) so I'd stay away from that. 
That leaves us with the arrow notation `->` (again like we're already using in Laravel). URLs would look like `/users?filter[content->en->name]=alexandr`. But that might be a little bit too opinionated and diverging from JSON API spec.

Thoughts/proposals/PRs welcome :)

**Comment by tabuna** [comment]
@AlexVanderbist Could you give an example of the problem of overlapping fields?

**Comment by AlexVanderbist** [comment]
I was talking about:
>Filtering an API request: /users?filter[content][en][name]=alexandr:
>
>```php
>$flight = QueryBuilder::for(Flight::class)
>    ->allowedFilters('content')
>    ->get();
>```
>To avoid overlapping several conditions using the same array.
>You can add a check, for example:
>...

**Comment by tabuna** [comment]
For this we will check the `cast` models

```
if($query->getModel()->hasCast($property,['object','array'])){

}
```

**Comment by slashequip** [comment]
Is this a problem which could be resolved using the built in custom filters? It feels like a tough call to make with the spec being "agnostic" about filter implementation.

https://github.com/spatie/laravel-query-builder#custom-filters

Personally I've even been using them to clean up standard filters to use `'comment'` instead of things like `'comment_id'`.

Does passing through arrow notation not work as is at the moment?
