### ISSUE TITLE
AllowedFilters are in OR configuration, is it possible to change this to an AND configuration?

### ISSUE THREAD

**Issue by wijnandhonselaar** [spatie/laravel-query-builder#431]
I'm using two filters on my query. When I only pass one of the values, the query works as expected.

When I pass both filter values, I get a result that lists ALL matches.

Is this how the `Allowerfileters()`is supposed to work? Should I create a custom filter to solve this problem, or am I just missing something perhaps?

```
QueryBuilder::for(Order::class)
            ->allowedFilters(
                AllowedFilter::exact('model', 'bike.model', true),
                AllowedFilter::scope('height', 'find_size')
)....
```

**Comment by dominikb** [comment]
Hello!

If you take a look at the implementation, you will see that this is indeed how it is supposed to work.
Filters are only applied if they have a user-supplied value or a default value. (see  `FiltersQuery:: addFiltersToQuery()`)

The underlying call to `Illuminate/Query/Builder.php` uses `whereIn()`, which defaults to using an 'and' concatenation.

In your specific case, you are likely to be best off using a custom filter.

**Comment by wijnandhonselaar** [comment]
Thanks for the info Dominik!
