### ISSUE TITLE
SoftDelete scopes cause ReflectionException

### ISSUE THREAD

**Issue by ampersand** [spatie/laravel-query-builder#432]
When using version 2.6.* to 2.7.0 I am no longer able to add the soft delete scopes as an allowed filter.

```
QueryBuilder::for(User::class))
    ->allowedFilters([AllowedFilter::scope('only_trashed')])
    ->get()
```

This results in a "Method scopeOnlyTrashed does not exist" ReflectionException in
https://github.com/spatie/laravel-query-builder/blob/366aaca9cf6195357812f01f412fe878cec414f5/src/Filters/FiltersScope.php#L26-L28

My guess is, this is caused by the magic inside of the [SoftDeletingScope](https://github.com/illuminate/database/blob/master/Eloquent/SoftDeletingScope.php) that isn't allowing reflection to see the scopes added by the SoftDeletes trait.

I reverted my version back to 2.5.1 to temporarily resolve the issue.

**Comment by telkins** [comment]
FYI.  I just upgraded from 2.5.1 to 2.7.0 and got the same error.  I have an allowed filter (a scope filter, too) that is no longer recognized.

My error: `Method scopeWithSecret does not exist`, although a minor difference for me is that I specify the scope:
```php
AllowedFilter::scope('reveal_secret', 'withSecret')->default(false)
```
I'll poke around a bit and, if not successful, will also revert to 2.5.1.

**Comment by dominikb** [comment]
I've dug into the source code of the `SoftDeletingScope::class` a little and the error lies with how those "scopes" are implemented.
They are added to the model as macros are not taken into account when using a `FilterScope`.

In my opinion, there are two ways to go ahead:
1. Take into account that macros can be used and differentiate both cases
2. Add another filter that is used for macros

**Comment by ampersand** [comment]
I would lean more towards the first option of checking for the macro "scopes".

I wonder if simply catching the `ReflectionException` in the `resolveParameters` method and returning the `$values` would be a valid solution.  I don't know enough about the purpose of this method to determine if this would cause any other issues.

**Comment by telkins** [comment]
Any traction on this issue...?  Has anyone taken a look at @ampersand 's potential fix?

**Comment by AlexVanderbist** [comment]
Fix looks promising, tagging it now :)

**Comment by AlexVanderbist** [comment]
@telkins on a side note: there's also `AllowedFilter::trashed()` as a filter for soft deleted models.

**Comment by telkins** [comment]
> @telkins on a side note: there's also `AllowedFilter::trashed()` as a filter for soft deleted models.

Thx.  Not sure I need it right now, but it's good to know. 🤓
