### ISSUE TITLE
Remove CamelCasing relationship names

### ISSUE THREAD

**Issue by dominikb** [spatie/laravel-query-builder#440]
This is a follow-up ticket for issue #393. (and #366, #332, #307)

Although I personally use camelCased relationship names, I don't think this is a behavior we want to enforce. Especially because there have been multiple tickets regarding this feature.

The conversion happens in two places. Namely in [AddsFieldsToQuery](https://github.com/spatie/laravel-query-builder/blob/95cffd71f64e90ff9102481fdfb12f243d5425db/src/Concerns/AddsFieldsToQuery.php#L54) and in [AllowedInclude](https://github.com/spatie/laravel-query-builder/blob/44aee49b9edf03587bb59d0ee8041eae6e5d2304/src/AllowedInclude.php#L31).

I see multiple ways to handle removing the camel casing:
1. **Removing** the feature with a notice in the changelog.
2. **Remove** the feature, detect if a cast would be necessary and throw a **meaningful exception**.
3. Keep the camel casing and **dynamically** detect if a **conversion** is required.

What are your thoughts?

CC: @suth

**Comment by suth** [comment]
Although it's documented the behavior surprised me even the second time I ran into it. I don't think there's a problem with choosing one default over the other, but if an alias is specified I think it could be safely assumed that casting is not necessary.

Is there any impact on nested relationships as well? Haven't had to use that feature yet.

**Comment by dominikb** [comment]
Nested relationship names will be cast as well. (Can be seen in this [test case](https://github.com/spatie/laravel-query-builder/blob/1321c20de6a1f687b38963b289b0dd814b8beba5/tests/IncludeTest.php#L229))

I just found an older todo that refers to validating that included relationships do exist:
https://github.com/spatie/laravel-query-builder/blob/1321c20de6a1f687b38963b289b0dd814b8beba5/src/Concerns/AddsIncludesToQuery.php#L81
Could we remove camel casing and add this check to give the user a meaningful exception?

**Comment by pionl** [comment]
Hi guys, I would recommend to be able to use a config entry to determine if CamelCase should be used?

**Comment by AlexVanderbist** [comment]
I agree that this is not the best default behaviour. Initially, I only added this because I didn't like the look of case sensitive URL parameters 🙈. Is there any reason to keep this in? I'd accept a PR that just gets rid of this on the v3 branch.

I'd accept a PR for that non-existing relationship exception as well.

**Comment by freekmurze** [comment]
We'll take a look at this in the next major version.
