### ISSUE TITLE
AddFieldsToQuery does not take into account the actual table's name if the name is non-standard

### ISSUE THREAD

**Issue by ebreisman** [spatie/laravel-query-builder#442]
We have a currently existing database with a table named `Person`. We have set the table name to `Person` in the Person model using `protected $table = 'Person';`, however, when trying to select fields to show (e.g. `/person?fields[Person]=last_name` or `/person?fields[person]=last_name`), the `AddFieldsToQuery::ensureAllFieldsExist()` throws an` InvalidFieldQuery` exception because it is looking for `person.last_name` instead of `Person.last_name`. The `ensureAllFieldsExist` method is making an incorrect assumption about our table naming by lower casing the table name. That method should take into account the actual name of the table as indicated in the model itself.

**Comment by dominikb** [comment]
I've taken a look into this issue and I don't think there is a trivial solution to this.

In order to use the `table` property of the given model, we would need an instance of the model. This would require us to resolve the class from the given field name.

I tried to implement this strategy but stopped when namespace resolution became an issue:
```php
// old 
$tableName = Str::snake(preg_replace('/-/', '_', $model));

// new
$modelClass = Str::studly(Str::singular($model));
$tableName = (new $modelClass())->getTable(); // error: class without path!
```

A custom solution could be provided if we allow for a `Strategy` implementation where you could overwrite the default "look-up".
```php
public interface ResolveTablenameFromField {
    public function resolve(string $fieldName): string;
}
```
Your strategy could try model classes with multiple namespace-prefixes or apply different string operations altogether.

@AlexVanderbist is this a feature we want to introduce?

**Comment by AlexVanderbist** [comment]
Can we maybe just get rid of snake-casing the requested model/table name? Instead whatever is requested will be used as the table name. I don't think we use that requested value anywhere else.

**Comment by gpibarra** [comment]
Maybe change the syntax of "allowedFields" method
`
QueryBuilder::for(Post::class)
    ->allowedFields([Post::class=> ['title'] , Author:class => ['author.id', 'author.name']])
    ->allowedIncludes('author');
`
you can get an instance of the class and the table name
`
$tableName = (new $modelClass())->getTable();
`

**Comment by AlexVanderbist** [comment]
@gpibarra even thought I like the idea, I think it'll limit people that are trying to select data from manually joined tables (so from queries without a model). We could support both by checking if the given string is a class but in that case it'd rather just support one correct way that is properly documented. 

I think the easiest solution here is just to remove the snake-casing of the selected fields. OPs example then becomes:
```php
QueryBuilder::for(Person::class)
    ->allowedFields('Person.id', 'Person.last_name');
// GET /persons?fields[Person]=id,last_name (so with exact table name in the URL)
```

If anyone wants to PR this, I'll be happy to merge it on the `v3` branch :)

**Comment by freekmurze** [comment]
We'll take a look at this in the next major version.
