### ISSUE TITLE
FiltersScope broken for "macroed" scopes...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-query-builder#444]
I have the same code, more or less, that works for version 2.5.1, but does not work for 2.8.0.

I'm trying to use a scope filter, and I'm sure everything would work fine if I was using "normal" scopes, but I'm using a "macroed" scope a la Laravel's `SoftDeletingScope`.

So, I can see the before and after code in this package.  Before, the values are "prepared" in a simple manner:
```php
$values = Arr::wrap($values);
```

In 2.8.0, however, things get a little more complicated:
```php
        $values = array_values(Arr::wrap($values));
        $values = $this->resolveParameters($query, $values, $scope);
```

It's inside `resolveParameters()` that reflection is used to find the scope method.  Since it's a macro, it's not found.  :-(

So...is this fixable?  I know I can make the scope a "normal" scope, but would prefer to avoid that if possible.  :-)

Thx.

**Comment by dominikb** [comment]
Hi, telkins. Thanks for opening an issue and providing such detailed information.

This is an unintended behavior that was introduced when attribute casting for filters was implemented.
Please take a look at issue #432 and maybe provide your opinion on how we should go forward with fixing this bug.

**Comment by telkins** [comment]
@dominikb Thanks for the response.  I took a look at #432 and found out that I've already commented on this issue.  LOL!  I'd forgotten about it completely.

Anyway, perhaps this issue should be closed in favor of the other one...?

**Comment by AlexVanderbist** [comment]
>Anyway, perhaps this issue should be closed in favor of the other one...?

Great idea :)
