### ISSUE TITLE
Requested filter(s) `filter` are not allowed. Allowed filter(s) are `title`.

### ISSUE THREAD

**Issue by accidentul** [spatie/laravel-query-builder#447]
It works localy but not o the server any ideea why ?
/api/get-program-categories?filter[title]=infrastructura

**Comment by freekmurze** [comment]
I have no clue...

**Comment by accidentul** [comment]
=))) what a response

**Comment by 1995Everton** [comment]
I saw something about your problem here https://github.com/spatie/laravel-query-builder/issues/324, I hope it helps

**Comment by accidentul** [comment]
> I saw something about your problem here #324, I hope it Helps


Thx a lot it seems that it’s a problem with Apache ... with nginx works perfectly
