### ISSUE TITLE
Individual array delimiter for a single filter

### ISSUE THREAD

**Issue by btxtiger** [spatie/laravel-query-builder#450]
Referencing #229 

It seems the custom array delimiter is also set for includes, sorts, appends, fields; this creates an insane breaking change for existing projects. It should be possible to override the default limiter `,` for just a single filter, where filtering for a string with comma is needed.

I just wanted to be able to find this string in my database `EL63PB1024Z8/24PB15X3PR0,3.482+999.`

```php
AllowedFilter::exact('id', 'ref_id', true, '|'),
```

PR in progress

**Comment by AlexVanderbist** [comment]
Good point! Let's continue this discussion in the PR.
