### ISSUE TITLE
search multiple fields

### ISSUE THREAD

**Issue by gutofurlan** [spatie/laravel-query-builder#452]
Guys I need to have a filter that validates in all fields with orWhere, for example: users? Search = Jhon he has to check that there is jhon in the name, email .... Has anyone done this? thankful

**Comment by btxtiger** [comment]
Shoud be possible using a custom filter:
```php
// GET /users?filter[hasName]=Jhon

AllowedFilter::custom('hasName', new HasNameFilter()),

// ...

class HasNameFilter implements Filter
{
   public function __invoke(Builder $query, $value, string $property): Builder
   {
      return $query->select('user.*')
         ->where('email', 'LIKE', '%' . $value . '%')
         ->orWhere('name', 'LIKE', '%' . $value . '%');
   }
}
```

**Comment by gutofurlan** [comment]
@btxtiger 
Okay, but there is no way for him to get my query and fields?

**Comment by btxtiger** [comment]
Who is him?

**Comment by gutofurlan** [comment]
@btxtiger Filter custom

**Comment by AlexVanderbist** [comment]
Hey @gutofurlan, have a look at the docs regarding custom filters: https://docs.spatie.be/laravel-query-builder/v2/features/filtering/#custom-filters

When using the custom filter @btxtiger has posted above, the `$value` will be the value you supplied in the request. For example: `GET /users?filter[hasName]=Jhon` will have `$value = 'Jhon'` in the custom filter.

Good luck and feel free to open a new issue if you need help with anything else!
