### ISSUE TITLE
Restrict includes by Pagination

### ISSUE THREAD

**Issue by ablishek** [spatie/laravel-query-builder#455]
Hi,

Is there any way I can restrict the includes by pagination. For example if I'm querying the User with it's Posts, I want to bring only the first 9 posts, and not the 140 posts they might have written in the past.

**Comment by abhi-cognitivo** [comment]
Just FYI, I am assuming I can just add a special relationship that restricts the data being brought over that relationship, but that would require someone to switch over to a specialized API if they want to load more data.
