### ISSUE TITLE
Filtering & Sorting by Model append Attributes 

### ISSUE THREAD

**Issue by shingsoso** [spatie/laravel-query-builder#459]
Is there any way to implement filtering & sorting by the model appended attributes ? 
For example : 

```
protected $appends = [
        'average_rating', 'total_review_count', 'thumbnail', 'total_visits_count'
    ];
public function getTotalReviewCountAttribute()
{
        return $this->reviews()->count();
}
```
I want to do sorting on appended attributes such as average_rating , total_review_count, etc

**Comment by ashgibson** [comment]
Appended attributes are added to the model after the database is queried. You will need to do a sort on the collection returned from the query.

`
$collection = QueryBuilder::for(MyModel::class)->get();
$collection->sortBy('average_rating');
`
