### ISSUE TITLE
Filtering greater than, lesser than etc.

### ISSUE THREAD

**Issue by JTinkers** [spatie/laravel-query-builder#462]
I'm looking all around the web and I can't seem to find any answer.

Does Spatie support queries with `?filter[id]>=11`? a.k.a 'greater than or equal'.

I'm trying to find a way not to have to declare 5 filters per column, which in this case will give me 36 filters - each being:

- ge__[column]
- le__[column]
- l__[column]
- g__[column]
- [column]

**Comment by AlexVanderbist** [comment]
Hi, we currently don't support this and probably aren't going to add this any time soon. 

A single custom filter could be used to achieve something like this: `users?filter[money]=>1` and even more advanced queries like `users?filter[money]=>1&<100`. But that'll leave parsing the `>1&<100` string up to your custom filter.

Good luck :)

**Comment by escapro** [comment]
Custom solution for all types of comparison queries.

**ComparisonFilter.php**
```
class ComparisonFilter implements Filter
{
    protected static $types = ['gt' => '>', 'ge' => '>=', 'lt' => '<', 'le' => '<=', 'eq' => '=', 'ne' => '<>'];

    public static function setFilters(string $field, array $givenTypes) {
        
        $result = [];
        
        foreach ($givenTypes as $type) {
            $result[] = AllowedFilter::custom("$field-$type", new ComparisonFilter);
        }

        return $result;
    }

    public function __invoke(Builder $query, $value, string $property)
    {
        list($field, $type) = explode('-', $property);

        if(!array_key_exists($type, self::$types)) return;

        $operator = self::$types[$type];

        $query->where($field, $operator, $value);
    }
}
```

**ProductController.php**
```
class ProductController extends Controller
{
    public function index(Request $request) {

        $products = QueryBuilder::for(Product::class)
        ->offset(request('offset') ?? 0)->limit(request('limit') ?? $this->defaultLimit)
        ->allowedFilters([
            'name',
            'type',
            ...ComparisonFilter::setFilters('sale_price', ['gt', 'ge', 'lt', 'le', 'eq', 'ne']),
            ...ComparisonFilter::setFilters('amount', ['gt', 'ge', 'lt', 'le']),
        ])
        ->allowedSorts('id')
        ->get();
        
        return ProductResource::collection($products);
    }
}
```

**Comment by ivan006** [comment]
Man above hits the spot. Shot bruv

**Comment by JTinkers** [comment]
@ivan006 Or just use GraphQL like any other modern developer :D

**Comment by ivan006** [comment]
get outa here
