### ISSUE TITLE
Use with Livewire

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-query-builder#464]
I saw this https://github.com/spatie/laravel-query-builder/issues/417 and wanted to give it a test, but I think you actually can't use this with livewire because you can't set `filter[name]` as a php variable name:

```
Public property [$filter[name]] not found on component
```

**Comment by mokhosh** [comment]
For anyone interested. If you use `wire:model="filter.name"` it updates querystring's `filter[name]`.

**Comment by binaryweavers** [comment]
> For anyone interested. If you use `wire:model="filter.name"` it updates querystring's `filter[name]`.

It updates queryString but it works in next request. For example you search for something say the field on component gets updated but it doesn't filter data in that request. After getting response it updates query string in the url, now in next request, for example you clear the search field but it will reflect the filter from url and will give you the filtered results based on previous value

**Comment by binaryweavers** [comment]
> > For anyone interested. If you use `wire:model="filter.name"` it updates querystring's `filter[name]`.
> 
> It updates queryString but it works in next request. For example you search for something say the field on component gets updated but it doesn't filter data in that request. After getting response it updates query string in the url, now in next request, for example you clear the search field but it will reflect the filter from url and will give you the filtered results based on previous value

It doesn't clear the query string 
```
protected $updatesQueryString = [
        'filter' => [
            'body'  =>  ['except' => '']
        ],
        'page' => ['except' => 1],
    ];
```
this doesn't work as well
```
    protected $updatesQueryString = [
        'filter' => ['except' => ''],
        'page' => ['except' => 1],
    ];
```
