### ISSUE TITLE
Integrity constraint violation: 1052 Column &#039;column&#039; in where clause is ambiguous

### ISSUE THREAD

**Issue by KillWil** [spatie/laravel-query-builder#466]
Hello,

Filtering model field and in the same time with scope and join may cause ambigous in where clause.

**How to reproduce :**
1 table 'table_one' with a code field
1 another table 'table_two' with a code field
1 model 'table_one' with a scope 'MyScope' (I'm not using whereHas functions which is too long to execute)

```
public function scopeMyScope($query) {
         return $query->join("table_two", 'table_one.code', '=', 'table_two.code');
}
```

Then call a get request :
`GET myroute?filter[code]=15&filter[my_scope]`

**Solution :**
Fully qualified with the table name the properties fields in Exact Filter file :
/laravel-query-builder/src/Filters/FiltersExact.php

**$query->getModel()->getTable().'.'.**

```
public function __invoke(Builder $query, $value, string $property)
    {

        if ($this->addRelationConstraint) {
            if ($this->isRelationProperty($query, $property)) {
                $this->withRelationConstraint($query, $value, $property);

                return;
            }
        }

        if (is_array($value)) {
            $query->whereIn($query->getModel()->getTable().'.'.$property, $value);

            return;
        }

        $query->where($query->getModel()->getTable().'.'.$property, '=', $value);
    }

```
I can make a pull request if you want.

Thanks a lot,

**Comment by AlexVanderbist** [comment]
Thanks! Let's continue this issue in your PR.
