### ISSUE TITLE
Ignore arrays

### ISSUE THREAD

**Issue by sribna** [spatie/laravel-query-builder#470]
I use this awesome package to filter different lists. A user can manipulate a GET request and pass an array instead of string, which leads to a fatal error. Not a big problem, but would it be better to forbid arrays for some fields?

**Comment by AlexVanderbist** [comment]
Hi @sribna, can you give an example of such a request? Something like this: `GET /users?filter[name][key]=value`?

**Comment by AlexVanderbist** [comment]
This will be fixed by #488
