### ISSUE TITLE
default table for allowedFields ...

### ISSUE THREAD

**Issue by scramatte** [spatie/laravel-query-builder#472]
Hello,

I append allowedFields to my queryBuilder and get query must be something like bellow

`
/api/v1/contacts?filter[name]=firstname&fields[billing.contacts]=id,name
`

As you can see,  for fields, I must specify table name else it doesn't works and raise exception.

Query builder shouldn't detect automatically default table name ?
 
```
 $contacts = QueryBuilder::for(Contact::class)
                ->allowedFilters(['id','name'])
                ->allowedFields(['id', 'name'])
                ->paginate(30)
                ->appends(request()->query());
```

Regards

**Comment by AlexVanderbist** [comment]
You are right, this behaviour seems to have broken/been removed somewhere in the past. I'll try to fix this soon!

**Comment by AlexVanderbist** [comment]
I've just checked this again in the latest version of the package and everything seems to be working as expected. This test should cover this specific feature as well: https://github.com/spatie/laravel-query-builder/blob/766db08500085247a88ea56295c328f3eb0648ef/tests/FieldsTest.php#L68

Feel free to open a new issue about this if you (or anyone else) is still experiencing this issue. Thanks!
