### ISSUE TITLE
appending attributes / laravel resources

### ISSUE THREAD

**Issue by s8v** [spatie/laravel-query-builder#490]
Hi, I'm having problems using appends with laravel resources. The problem is that resources loads it even if I didn't explicitly called it in request. How could I fix it?

**Comment by malinushj** [comment]
Hi @s8v !
The way I handle appends with Resources is by settings the `$appends` fields on the model to public and in the resource I'm checking it like this:
```php
class MyModel extends Model
{
    public $appends = []; // this is very important for checking in the resource if the append has been added
}
```

```php
/**
 * @mixin \App\MyModel
 */
class MyResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            // Check if the model's appends has that specific value, and use a callback to return it so it doesn't run everytime
            'my_append' => $this->when(in_array('my_append', $this->appends), function() {
                return $this->my_append;
            }),
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at
        ];
    }
}
```

This way if you have a controller which sets the appends either through the query builder or with code (`->appends('my_append')`) it will work the same in the resource.

**Comment by s8v** [comment]
> Hi @s8v !
> The way I handle appends with Resources is by settings the `$appends` fields on the model to public and in the resource I'm checking it like this:
> 
> ```
> class MyModel extends Model
> {
>     public $appends = []; // this is very important for checking in the resource if the append has been added
> }
> ```
> 
> ```
> /**
>  * @mixin \App\MyModel
>  */
> class MyResource extends JsonResource
> {
>     public function toArray($request)
>     {
>         return [
>             'id' => $this->id,
>             // Check if the model's appends has that specific value, and use a callback to return it so it doesn't run everytime
>             'my_append' => $this->when(in_array('my_append', $this->appends), function() {
>                 return $this->my_append;
>             }),
>             'created_at' => $this->created_at,
>             'updated_at' => $this->updated_at
>         ];
>     }
> }
> ```
> 
> This way if you have a controller which sets the appends either through the query builder or with code (`->appends('my_append')`) it will work the same in the resource.

Nice, it's working. Thanks!!!
