### ISSUE TITLE
Passing a Relation object to QueryBuilder not possible

### ISSUE THREAD

**Issue by boris-glumpler** [spatie/laravel-query-builder#506]
Hello,

just tried to pass a `BelongsToMany` relation into `QueryBuilder` and got told off:

```
vendor/spatie/laravel-query-builder/src/QueryBuilder.php on line 32

Argument 1 passed to Illuminate\Database\Eloquent\Builder::__construct() must be an instance of Illuminate\Database\Query\Builder, instance of Illuminate\Database\Eloquent\Builder given
```

This makes sense because `$builder->getQuery()` at line 32 would actually return a `Illuminate\Database\Eloquent\Builder` instance if `$builder` is an instance of `\Illuminate\Database\Eloquent\Relations\Relation`.

I did check `QueryBuilder` beforehand, tho, and the docblock does suggest that `$builder` can be a `Relation` instance. So, I'm wondering if the docblock is just out of date or if this is a bug and I should be able to pass in a `Relation` instance? Maybe you can help me out here.

Cheers,
Boris

**Comment by AlexGodbehere** [comment]
I second this question. How does one use this package with eloquent relationships? I'm trying to call the following and receiving the same error as above:

`return QueryBuilder::for(auth()->user()->friends()->allowedFilters('username'))`

**Comment by AlexGodbehere** [comment]
@boris-glumpler After coming across [this](https://github.com/spatie/laravel-query-builder/issues/441) issue, it seems as though all you have to do is call `->getQuery()` on the relationship.

**Comment by boris-glumpler** [comment]
Sure, but then you lose access to any pivot data. Anyways, seems like v3 fixed this issue.
