### ISSUE TITLE
 [InvalidArgumentException]   Could not find package spatie/laravel-query-builder at any version matching your PHP version 7.0.10.0

### ISSUE THREAD

**Issue by leandroruel** [spatie/laravel-query-builder#51]
i'm trying install this package but this error occurs:
` [InvalidArgumentException]  Could not find package spatie/laravel-query-builder at any version matching your PHP version 7.0.10.0`

what i'm doing wrong?

**Comment by freekmurze** [comment]
This package requires PHP 7.1

**Comment by leandroruel** [comment]
Ok, my bad
