### ISSUE TITLE
AllowedInclude can't be used for nested relationships

### ISSUE THREAD

**Issue by marttosc** [spatie/laravel-query-builder#522]
Version: 3.0.0

I have a nested relationship that I can pass it on in the allowedIncludes method like...

```php
QueryBuilder::for(Model1::class)
    ->allowedIncludes([
        'model2.nested_relationship',
    ]);
```

... and it works fine.

But, when I try to use the `AllowedInclude::relationship` method, it throws an error.

```php
QueryBuilder::for(Model1::class)
    ->allowedIncludes([
        // So I can call it using ?include=nested_relationship instead of model2.nested_relationship
        AllowedInclude::relationship('nested_relationship', 'model2.nested_relationship'),
    ]);
```

Exception:

```
Argument 1 passed to Spatie\\QueryBuilder\\AllowedInclude::__construct() must be of the type string, null given, called in vendor/spatie/laravel-query-builder/src/AllowedInclude.php on line 39
```

**Comment by marttosc** [comment]
After some workarounds, when I do this...

```php
use Spatie\QueryBuilder\AllowedInclude;
use Spatie\QueryBuilder\Includes\IncludedRelationship;
use Spatie\QueryBuilder\QueryBuilder;

QueryBuilder::for(Model1::class)
    ->allowedIncludes([
        new AllowedInclude('nested_relationship', new IncludedRelationship, 'model2.nested_relationship'),
    ]);
```

And change the line 29 of `AddsIncludesToQuery.php`

https://github.com/spatie/laravel-query-builder/blob/e17fbfc4a5a89f320d5d99eb0373b5224551d98f/src/Concerns/AddsIncludesToQuery.php#L29

to...

```php
if ($include instanceof IncludeInterface || $include instanceof AllowedInclude) {
```

Then, it works!

Does it make sense to be implemented in a PR?

**Comment by AlexVanderbist** [comment]
Related: https://github.com/spatie/laravel-query-builder/pull/414 (cc @dominikb)

As discussed in the linked PR, the parts or the models of a relationship are mapped to the parts of the alias. E.g. `AllowedInclude::relationship('userAlias.postsAlias', 'users.posts')` will cause the following allowed includes: `userAlias` and `userAlias.postsAlias`. 

However, the more I look at it, the more I think an alias should just be a "string replacement". So the above example of `AllowedInclude::relationship('userAlias.postsAlias', 'users.posts')` allows just one include: `userAlias.postsAlias` (which then includes `users.posts`). If you want to only include users you'll have to specify another include.

(Alternatively we can check if the alias contains a dot and if the number of alias parts matches the number of relationship parts to make sure each alias-part maps to an existing relationship. Personally I'm not a fan of this as we're combining two ways of thinking. I'd much rather have an alias just be a string that gets replaced with the entire nested relationship it represents. But again, always open for thoughts on this)
