### ISSUE TITLE
Bug on Select Field when field is write in UPPERCASE

### ISSUE THREAD

**Issue by maiconmva** [spatie/laravel-query-builder#524]
when i try to get only PES_COD field, 

this error shows:
![image](https://user-images.githubusercontent.com/5194641/92518415-b5090880-f1ee-11ea-81a0-4eb4d74e452e.png)

and if i get updated_at works fine..
this query works:

![image](https://user-images.githubusercontent.com/5194641/92518341-91de5900-f1ee-11ea-9dd9-046430ad4a64.png)

**Comment by marttosc** [comment]
Hi maiconmva,

This happens because it use the snake-casing of the selected fields. Did you try to pass `pes_code` instead of `PES_CODE`?

**Comment by maiconmva** [comment]
hello @marttosc 

this should work:

![image](https://user-images.githubusercontent.com/5194641/92602215-3a8ac800-f284-11ea-9066-52837b3bffbd.png)

this is what u told to do

![image](https://user-images.githubusercontent.com/5194641/92602348-6a39d000-f284-11ea-808b-6a5d323dcaa1.png)

**Comment by marttosc** [comment]
Ok, I've understand now. Your model has uppercase fields.

You can try to use [filter aliases](https://spatie.be/docs/laravel-query-builder/v2/features/filtering#filter-aliases), like this.

```php
$entries = QueryBuilder::for(Model::class)
    ->allowedFilters([
        AllowedFilter::partial('pes_cod_old', 'PES_COD_OLD')
    ])
    ->get();
```

If this doesn't work, the problem probably is in the `ensureAllFieldsExist` method.

**Comment by marttosc** [comment]
It seems that's a similar problem that occurs in [#515](https://github.com/spatie/laravel-query-builder/issues/515#issuecomment-689229711).

**Comment by aliene-ctrl** [comment]
> It seems that's a similar problem that occurs in [#515](https://github.com/spatie/laravel-query-builder/issues/515#issuecomment-689229711).

It's a really annoying feature. IMO `ensureAllFieldsExist` can be safely deleted.

**Comment by aliene-ctrl** [comment]
#525

**Comment by AlexVanderbist** [comment]
Hi @maiconmva, sorry you ran into this issue. This is something we'll be addressing soon in dominikb's PR (#534). As @marttosc suggested using an alias is probably the best way forward for now: 

```php
$entries = QueryBuilder::for(Model::class)
    ->allowedFilters([
        AllowedFilter::partial('pes_cod_old', 'PES_COD_OLD')
    ])
    ->get();
```
