### ISSUE TITLE
Cannot use include alias on allowedFields

### ISSUE THREAD

**Issue by Yeenot** [spatie/laravel-query-builder#527]
Hello, I have a problem where I cannot use my include alias on allowedFields.

Example:
This will not work: `/sample?include=tag&fields[test]=id,name`
but this will work: `/sample?include=tag&fields[taggable]=id,name`

```
->allowedFields([
   'test.id', 'test.name'
])
->allowedIncludes([
    AllowedInclude::relationship('test', 'taggable')
])
```

**Comment by AlexVanderbist** [comment]
Hi @Yeenot, this is something that's not currently supported. Aliases defined in the `allowedIncludes` cannot be used as aliases in the `fields` query parameter. In fact, aliases for `allowedFields` aren't supported at all right now. Feel free to open a PR or an issue to discuss this further. Thanks :)
