### ISSUE TITLE
Can not load deleted relations

### ISSUE THREAD

**Issue by thoss** [spatie/laravel-query-builder#529]
I'm using the `AllowedFilter::trashed()` Filter. 
Its working on the root Model but I cant load deleted relationships with the `allowedIncludes` method or filter on relations.

Is it possible to inherit the `withTrashed` to the childs?

**Comment by AlexVanderbist** [comment]
Hi @thoss, this is not possible out of the box with the `AllowedFilter::trashed()` filter. I'd suggest creating a custom filter that filters the query by `trashed()` scope on the relationships. Something like this:

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Spatie\QueryBuilder\Exceptions\InvalidFilterValue;
use Spatie\QueryBuilder\Filters\Filter;

class TrashedChildrenFilter implements Filter
{
    public function __invoke(Builder $query, $values, string $property): Builder
    {
        $query->whereHas('relatedChildren', function ($q) {
            $q->withTrashed();
        });
    }
}
```

Good luck and feel free to open a new issue if this does not answer your question.

**Comment by satun14** [comment]
And so, if you got here, then your despair has reached its peak and you want to do a rather perverse thing through this tool =)

Stack:
```
"laravel/framework": "5.6.*",
"spatie/laravel-query-builder": "2.8.4",
```

First, we create a custom filter:
```php
use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\Filters\Filter;

class FiltersRelationsTrashed implements Filter
{
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        $relations = $this->prepareValue($value);

        $this->connectRelationsWithTrashed($query, $relations);

        return $query;
    }

    private function connectRelationsWithTrashed($query, array $relations)
    {
        foreach ($relations as $relation => $value) {
            $query->with([$relation => function ($q) use ($value) {
                $q->withTrashed();

                if (is_array($value)) {
                    $this->connectRelationsWithTrashed($q, $value);
                }
            }]);
        }
    }

    /**
     * Generate from 'user.role.permission,user.item'
     * array like [ 'user' => [ 'role' => [ 'permission' => null ], 'item' => null]]
     *
     * @param $value
     * @return array
     */
    private function prepareValue($value): array
    {
        $relations = [];

        if (!is_array($value)) $value = [$value];

        foreach ($value as $row) {
            array_set($relations, $row, null);
        }

        return $relations;
    }
}
```

Now you can add this filter to the allowedFilters:
```php
$users = QueryBuilder::for(User::class)
            ->allowedIncludes([])
            ->allowedSorts([])
            ->allowedFilters([
                AllowedFilter::custom('trashedRelations', new FiltersRelationsTrashed()),
            ]);
```
**Important!** You have to make sure that **allowedIncludes** is executed before **allowedFilters**, as our filter overwrites standard **with**

Now you can add the **filter[trashedRelations]=user.role.permission,user.item** line to your request and get the deleted records in the query results

However, in the end, problems remain...
* how to filter by such values? (by default, laravel builder builds a subquery for filtering with a check for deleted_at is null)
