### ISSUE TITLE
Ability to include certain fields from related model

### ISSUE THREAD

**Issue by Tarasovych** [spatie/laravel-query-builder#53]
In Eloquent I can use [`with()`](https://laravel.com/api/5.6/Illuminate/Database/Eloquent/Builder.html#method_with) to fetch certain fields from related model.
I'd like to able do the same with `allowedIncludes()` like `allowedIncludes('related_model:id,name')`.

**Comment by viezel** [comment]
or even better, being able to do:

```
->allowedIncludes(['products' => function($query) {
     $query->where('price', 100)
}, 'stock', 'warehouses'])
```

**Comment by brunen9** [comment]
@Tarasovych did you try the [Selecting specific columns](https://github.com/spatie/laravel-query-builder#selecting-specific-columns)?

**Comment by Tarasovych** [comment]
@brunen9 I need specific column for related model. I don't need specific columns for the model whose class is used for `QueryBuilder::for()` argument.
