### ISSUE TITLE
whenAppended no longer working

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-query-builder#531]
I don't know if this is an QueryBuilder bug or Laravel has changed this call:

```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PostResource extends JsonResource
{
    /**
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->getRouteKey(),
            'thumbnail' => $this->whenAppended('thumbnail'),
        ];
    }
}
```

```
class IndexController extends Controller
{
    public function __invoke()
    {
        $models = QueryBuilder::for(Post::class)
            ->allowedAppends([
                'thumbnail',
            ])
            ->jsonPaginate();

        return PostResource::collection($models);
    }
}
```
The appending fields are just not included in the response.

**Comment by francoism90** [comment]
It seems this change has caused the whenAppended method to stop working: https://github.com/laravel/framework/commit/9c297949bc2ded6a7b6f205ddddf0b238967c506

**Comment by francoism90** [comment]
It seems to be caused by spatie/laravel-json-api-paginate, if I'm using `->get()` instead of `->jsonPaginate()` the whenAppends are working fine.

https://github.com/spatie/laravel-query-builder/blob/master/src/QueryBuilder.php#L96 - checks only for Model/Collection, but this returns a `LengthAwarePaginator` instead of `Illuminate\Database\Eloquent\Collection`

**Comment by arukas** [comment]
yes,me too.
I use $model->allowedAppends(['src'])->paginate(); is's not show src
$model->allowedAppends(['src'])->get(); is't show src.
