### ISSUE TITLE
Has v3 been merged into v2.8.3 by mistake?

### ISSUE THREAD

**Issue by denitsa-md** [spatie/laravel-query-builder#535]
I did a `composer update` today and started getting errors on type hints of the eloquent builder incompatible with spatie's query builder. It surprised me because it's a change introduced in v3 and we're at `^2.3` in composer.

Then I stepped through to the QueryBuilder and it looks like the one from v3 even though we're on v2.

Then I checked my composer.lock just to be sure we're at 2.8.3 and not 3.

Then I checked out this diff: https://github.com/spatie/laravel-query-builder/compare/2.8.2...2.8.3

And it kind of seems that the changes from 3 have appeared in 2.8.3.

Issue #526 could be related to this.

**Comment by freekmurze** [comment]
I've fixed this by releasing 2.8.4

**Comment by freekmurze** [comment]
Thanks for reporting btw 👍
