### ISSUE TITLE
Nested relation includes too strict?

### ISSUE THREAD

**Issue by slashequip** [spatie/laravel-query-builder#54]
Hey,

Given this query builder:
```
QueryBuilder::for(Site::class)
    ->allowedIncludes('division.organisation')
    ->get();
```

If I only try to include `division` in my request I get an error saying `division` isn't in the list of allowed includes. Is this intended behaviour? Feels too restrictive/strict to me.

The work around is to do this:
```
QueryBuilder::for(Site::class)
    ->allowedIncludes('division', 'division.organisation')
    ->get();
```

Feels a little repetitive?

If I can get some time I don't mind attempting a PR but let me know how you feel about this.

**Comment by freekmurze** [comment]
I'd accept a PR with tests.
