### ISSUE TITLE
400 when calling from REST API in Production

### ISSUE THREAD

**Issue by dlogvin** [spatie/laravel-query-builder#541]
Block of code being involved: 

```
public function sortByDate()
    {
        $assignments = QueryBuilder::for(Auth::user()->homeworks())
            ->allowedFilters(['duedate'])
            ->latest()
            ->get();
        return response()->json([
            'assignments' => $assignments,
        ]);
        // ?filter[duedate]=date
    }
```

In local environment it works as expected, in production I get a 400.

**Comment by dominikb** [comment]
Hi @dlogvin,

an HTTP 400 response is a generic error response and it's hard for us to help you without further information. Can you provide the stack trace or the exception that causes this error? (**Please make sure no sensitive data is included in the stack trace!**)

**Comment by dlogvin** [comment]
> Hi @dlogvin,
> 
> an HTTP 400 response is a generic error response and it's hard for us to help you without further information. Can you provide the stack trace or the exception that causes this error? (**Please make sure no sensitive data is included in the stack trace!**)

Hello! Apparently, I cannot make use of `?filter[duedate]=date` in production, I had to use `?duedate=2020-05-25` for example. I ended up making the query myself since I still got some trouble while filtering, I was not getting what I needed with `?duedate`
