### ISSUE TITLE
Model guarded attribute doesn't play

### ISSUE THREAD

**Issue by hubroot** [spatie/laravel-query-builder#56]
Hi,

Model {
   guarded : deleted_at
}

QueryBuilder(Model)->get()

returns all Model attributes, is there a way to link the QueryBuilder and Laravel Model guarded attribute together ?

**Comment by freekmurze** [comment]
No. If you want to limits attributes being returned you could use a resource class that doesn't return all attributes.

Alternatively take a look at the `hidden` property of a model
