### ISSUE TITLE
How can I achieve OrWhere

### ISSUE THREAD

**Issue by tsndp** [spatie/laravel-query-builder#568]
Taking from official Docs:

```
Basic usage
// GET /users?filter[name]=john&filter[email]=gmail

$users = QueryBuilder::for(User::class)
    ->allowedFilters(['name', 'email'])
    ->get();

// $users will contain all users with "john" in their name AND "gmail" in their email address
```

How can i get below data:
$users contain all users with "john" in their name **OR** "gmail" in their email address

**Comment by AlexVanderbist** [comment]
Hi! We currently don't support this out of the box. I'm happy to discuss this issue further if someone would be willing to create a PR to add this functionality somehow.

**Comment by AlexVanderbist** [comment]
On a sidenote: something similar was already discussed before in this issue: https://github.com/spatie/laravel-query-builder/issues/367

In that case the solution was using custom sorts with each their own `orWhere` query.

**Comment by uwla** [comment]
> Hi! We currently don't support this out of the box. I'm happy to discuss this issue further if someone would be willing to create a PR to add this functionality somehow.

I would be willing to create a PR for this feature out of the box.

I think the proposed solution from https://github.com/spatie/laravel-query-builder/discussions/611#discussioncomment-4996139 is actually good: pass 2 extra optional parameters that determine if we should use AND or OR.

What do you think? Let's walk this through
