### ISSUE TITLE
Example selecting specific columns on relationship not working

### ISSUE THREAD

**Issue by matthijsfringe** [spatie/laravel-query-builder#58]
The following given example does not seem to work:
`GET /posts?include=author&fields[author]=name`

The value of the author relation will be null.

It looks like when calling a One To One (Inverse) or a One To Many (Inverse) relationship and specifying at least one field of the relationship, you have to include the primary_key as following:
`GET /posts?include=author&fields[author]=id,name`

Same goes for the One To One and the One To Many relationships while you are specifying at leat one field for the relationship. There it seems you have to include the foreign_key as following:
`GET /author?include=post&fields[post]=author_id,body`
and
`GET /author?include=posts&fields[posts]=author_id,body`

Many To Many Relationships work as expected.

Is this supposed to work this way or should the example work as given?

**Comment by AlexVanderbist** [comment]
Hi! I've checked this out and it looks like selecting specific fields using `select()` causes eloquent to ignore required fields for the relationship... (I guess we missed the giant red warning in the docs).

A possible solution might be to automatically `select` necessary foreign/local keys based on the relationship you're trying to include. However it feels like that might be quite brittle as eloquent relationships can become quite complex. Different relationships require different columns to be loaded as well (e.g. polymorphic relationships require a morph type column to be loaded, ...).

I'll look into this again tomorrow. For now it looks like adding the foreign key to your custom selection of related fields will be the easiest solution.

**Comment by prodigy7** [comment]
+1
