### ISSUE TITLE
issue when i use the allowedFilters()

### ISSUE THREAD

**Issue by mohhamedion** [spatie/laravel-query-builder#584]
like in the picture, i passed ?level=1 to the url and this error show up.

![image](https://user-images.githubusercontent.com/41584933/103141856-67a79d00-46f2-11eb-98e1-5ab3d7c5b69f.png)

then, i change the url to ?filter[level] = 1 like in the documentation
and i got this
![image](https://user-images.githubusercontent.com/41584933/103141873-c3722600-46f2-11eb-87a8-6fe9c1d37e9d.png)

this is the code i used, am using laravel 8
```
        return QueryBuilder::for(Test::class)->allowedFilters([
            'level'
        ])->get();
```
Thank you.

**Comment by AlexVanderbist** [comment]
Interesting! Can you share your query-builder config file with us?

**Comment by Radiergummi** [comment]
I experienced the same issue, but noted I didn't flush the configuration cache after installing and publishing the config file. Right after running `artisan config:cache` filtering was working flawlessly. Contrary to the documentation, the config file seems to be required though.
