### ISSUE TITLE
Column not found when attempting to filter on pivot table

### ISSUE THREAD

**Issue by AlexGodbehere** [spatie/laravel-query-builder#586]
I have a `User` model that is accessible via the `Company` model's `members()` relationship, defined like this:

```php
public function members()
    {

        return $this->belongsToMany(User::class, 'company_invites', 'company_id', 'target_user')
          ->withPivot('role')
          ->as('membership')
          ->withTimestamps()
          ->wherePivotNotNull('accepted_at');
    }
```

I'm trying to filter by the `role` column on the pivot table using the following query:

```php
return QueryBuilder::for($company->members())->allowedFilters('username', AllowedFilter::exact('membership.role'))
```

But I keep getting the following error when requesting `/members?filter[membership.role]=manager`:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'membership.role' in 'where clause' (SQL: select count(*) as aggregate from `users` inner join `company_invites` on `users`.`id` = `company_invites`.`target_user` where `company_invites`.`company_id` = 1 and `company_invites`.`accepted_at` is not null and LOWER(`membership`.`role`) LIKE %manager%)
```

I'm able to filter by `username` no problem and the relationship is configured correctly:

```php
ray($company->members()->first());

// Prints:
array:1 [
  0 => array:23 [
    "id" => 1
    "created_at" => "2020-12-23T15:45:05.000000Z"
    "updated_at" => "2021-01-13T15:31:46.000000Z"
    "first_name" => "..."
    "last_name" => "..."
    "username" => "..."
    
    ...

    "membership" => array:5 [
      "company_id" => 1
      "target_user" => 1
      "role" => "director"
      "created_at" => "2020-12-23T22:31:00.000000Z"
      "updated_at" => "2020-12-23T22:31:00.000000Z"
    ]
  ]
]

```

Am I missing something here?

**Comment by AlexGodbehere** [comment]
Looking into this a bit further it appears as though the issue stems from `FiltersExact.php` checking if a method exists with the first part of the `.` delimited string (in this case `membership`) on the model by calling `getModel()`.

It seems as though `getModel()` is not resolving the appended pivot column so therefore doesn't exist.

```php
protected function isRelationProperty(Builder $query, string $property): bool
    {
        if (! Str::contains($property, '.')) {
            return false;
        }

        if (in_array($property, $this->relationConstraints)) {
            return false;
        }

        $firstRelationship = Str::camel(explode('.', $property)[0]);

        if (! method_exists($query->getModel(), $firstRelationship)) {
            // This is retuning false
            return false;
        }

        return is_a($query->getModel()->{$firstRelationship}(), Relation::class);
    }
```

If I print out the contents of `$query->getModel()` then as expected `role` is nowhere to be seen. If I print out `$query()->get()` instead, the `role` property is amongst the attributes on the model as expected.

**Comment by ftaurino** [comment]
Perhaps you should try with a Resource

**Comment by AlexVanderbist** [comment]
Hi @AlexGodbehere, thanks for being patient. It looks like we simply don't support adding a condition on a pivot table using `wherePivot`. I'm happy to merge a PR that solves this somehow, but I'm not sure where to start... 

As a solution I'd propose creating a custom filter that utilises Laravels's [wherePivot](https://laravel.com/docs/master/eloquent-relationships#filtering-queries-via-intermediate-table-columns) to query your membership roles for a company.

Good luck!
