### ISSUE TITLE
InvalidFilterQuery when using in conjunction with json api paginate package

### ISSUE THREAD

**Issue by imknight** [spatie/laravel-query-builder#594]
if using QueryBuilder with allowedFilters, then it will break the JSON API package because the "page" query parameter

**Comment by AlexVanderbist** [comment]
Hi @imknight! Thanks for reporting this. We're currently using this package in combination with the JSON API paginate package basically everywhere without any problems. I'm gonna close this issue as it's been a while but definitely feel free to open a new one with some more information (query builder config, versions, etc...) if you're still experiencing this problem. Thanks!
