### ISSUE TITLE
Support for Laravel Query Builder? -- Subject class `Illuminate\\Database\\Query\\Builder` is invalid.

### ISSUE THREAD

**Issue by vicenterusso** [spatie/laravel-query-builder#597]
Hello, I just installed and got this error. 

This is my controller:

```php
use Spatie\QueryBuilder\QueryBuilder;

protected function index(Request $request)
{
        $query = DB::table("tablename");
        //(..) full query without the ->get()
        return QueryBuilder::for($query)->get();
}
```
And this is my API response:

```json
  "message": "Subject class `Illuminate\\Database\\Query\\Builder` is invalid.",
  "exception": "Spatie\\QueryBuilder\\Exceptions\\InvalidSubject",
  "file": "/var/www/html/vendor/spatie/laravel-query-builder/src/Exceptions/InvalidSubject.php",
  "line": 11,
```

Also I have a Ray debug output inside `QueryBuilder's initializeSubject()`:

```php
protected function initializeSubject($subject): self
{
    ray($subject);
    throw_unless(
        $subject instanceof EloquentBuilder || $subject instanceof Relation,
        InvalidSubject::make($subject)
    );

    $this->subject = $subject;

    return $this;
}
```

![image](https://user-images.githubusercontent.com/80538/105851353-b9796680-5fc1-11eb-928a-38ca5d0cccf9.png)

**Comment by tex1712** [comment]
Maybe it's late, but for someone else it could be helpful.

You need to pass to the **QueryBuilder** the model itself. Also you need to indicate allowed for sorting fields.

Exemple:
`$comments = QueryBuilder::for(Comment::class)
->allowedSorts([
            'title',
            'created_at',
            'updated_at'
        ])
->get();`

**Comment by klimov-paul** [comment]
You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) instead. It privdes suport for raw DB queries.

**Comment by sethjfischer** [comment]
> Maybe it's late, but for someone else it could be helpful.
> 
> You need to pass to the **QueryBuilder** the model itself. Also you need to indicate allowed for sorting fields.
> 
> Exemple: `$comments = QueryBuilder::for(Comment::class) ->allowedSorts([ 'title', 'created_at', 'updated_at' ]) ->get();`

According to the documentation you are supposed to be able to pass a query, not just the model itself.  

https://spatie.be/docs/laravel-query-builder/v5/introduction#content-works-together-nicely-with-existing-queries
