### ISSUE TITLE
allowedFields by relation camelCase problem

### ISSUE THREAD

**Issue by bianchi** [spatie/laravel-query-builder#598]
I have an error when trying to define allowedFields for nested relations with camelCase name. Shouldn't it work like include? [https://spatie.be/docs/laravel-query-builder/v3/features/including-relationships#include-casing](url)

Query string:
`include=localizacaoOrigem,material&fields[material]=nome&fields[localizacaoOrigem]=nome`

Error:
`Requested field(s) 'localizacao_origem.nome' are not allowed. Allowed field(s) are 'material.nome, localizacaoOrigem.nome`.`

Code:
```
 $query = QueryBuilder::for(TransferenciaEstoque::class);

        return $query
            ->allowedFields(['material.nome', 'localizacaoOrigem.nome'])
            ->allowedIncludes([
                'material', 'localizacaoOrigem',
            ])
            ->allowedFilters([
                AllowedFilter::exact('material', 'material.codigo'),
                AllowedFilter::exact('localizacao_origem_id', 'localizacaoOrigem.id'),
            ])
            ->defaultSort('-' . Jhob::tableName(TransferenciaEstoque::class) . '.alterado_em')
            ->allowedSorts(['realizada_em'])
            ->get();
```

It works if I change localizacaoOrigem to localizacao_origem in allowedFields code:
```
$query = QueryBuilder::for(TransferenciaEstoque::class);

        return $query
            ->allowedFields(['material.nome', 'localizacao_origem.nome'])
            ->allowedIncludes([
                'material', 'localizacaoOrigem',
            ])
            ->allowedFilters([
                AllowedFilter::exact('material', 'material.codigo'),
                AllowedFilter::exact('localizacao_origem_id', 'localizacaoOrigem.id'),
            ])
            ->defaultSort('-' . Jhob::tableName(TransferenciaEstoque::class) . '.alterado_em')
            ->allowedSorts(['realizada_em'])
            ->get();
```

**Comment by bianchi** [comment]
Someone know how to deal with it?

Besides I'm have the same problem with _append_

**Comment by josephxanderson** [comment]
I'm investigating this issue as well. Is there any way we can use `camelCase` fields? Maybe something like `AllowedField::field('firstName', 'first_name')` similar to `AllowedSort::field()`?

**Comment by yoelpc4** [comment]
Try snake case for the relation part for current solution e.g: 

```
->allowedFields(['material.nome', 'localizacao_origem.nome'])
```

**Comment by AlexVanderbist** [comment]
Hi! There are indeed some issues with string casing in the current version. In the next version of the package I'm looking to get rid of all casing conversions and just pass the requested string the the query builder. If someone wants to kickstart this, feel free to send a PR and I'll be happy to merge it in a new major version of the package 👍
