### ISSUE TITLE
Filed selection not working for nested hasMany relationship

### ISSUE THREAD

**Issue by DHSprout** [spatie/laravel-query-builder#605]
Filed selection not working for nested hasMany relationship.

It is working proper when we have one to one relation.

Scenario: I have relation like 
employee has many address and i want to specify got some fields from address in this case it is not working.

Could you please help me on this?

**Comment by AlexVanderbist** [comment]
Hi @DHSprout! I'm not sure if I understand your question correctly. I'm gonna close this issue as it's been inactive for a while but please feel free to open a new issue if you're still having questions. Make sure to include a code example so we can help you better! Thanks and good luck 👍

**Comment by anayarojo** [comment]
Hi @AlexVanderbist , I have a problem similar to mentioned previously, I can't select fields from model relationships.

Here is the context using `spatie/laravel-query-builder` version `4.0.4`:

I have this a database with the following tables structure:
![image](https://user-images.githubusercontent.com/6903495/210457459-4a90043a-97ed-40a9-8814-ef9c2947fa6e.png)

Also, the following models in Laravel:
![image](https://user-images.githubusercontent.com/6903495/210457499-cd3e1e1a-1bd5-49f7-b691-6b708a6c3eba.png)

With this Laravel query builder configuration:

```php
private function getQuery()
{
    return QueryBuilder::for(Order:class)
            ->allowedFields([
                'id',
                'created_at',
                'updated_at',
                'company_id',
                'subcompany_id',
                'items.id',
                'items.qty',
                'items.price',
                'items.product_id',
                'items.product.id',
                'items.product.name',
                'company.id',
                'company.name',
                'subcompany.id',
                'subcompany.name',
            ])
            ->allowedIncludes([
                'company',
                'subcompany',
                'items.product',
            ])
            ->allowedFilters([
                'company_id',
                'subcompany_id',
            ])
            ->allowedSorts([
                'id',
                'created_at',
                'updated_at',
            ]);
}
```

This is the HTTP query 
```bash
https://myproject.test/query
?limit=5
&include=items,company,subcompany
&fields[orders]=id,created_at,updated_at,company_id,subcompany_id
&fields[items]=id,qty,price
```

And the result is something like this:
```bash
[
 {
   id: int,
   created_at: date,
   updated_at: date,
   company_id: int,
   subcompany_id: int,
   company: object,
   subcompany: object,
   items: [], // This is returning empty
 }
]
```

I'm looking for to get the items with the specified fields, something like: `items: [{id: int, qty: int, price: int}]`.
How can I achieve that? Is it possible?

Thanks, Alex

**Comment by anayarojo** [comment]
Hi there, I could solve this issue

That I needed was adding all fields that keep the relationships. For example, using the mentioned scenario:
- To include the `company ` relationship I need to add `company_id` field.
- To include the `subcompany` relationship I need to add `subcompany_id` field.
- To include the `items` relationship I must add `order_id` field from items fields.

The HTTP query now looks like this and works successfully:
```
https://myproject.test/query
?limit=5
&include=items,company,subcompany
&fields[orders]=id,created_at,updated_at,company_id,subcompany_id
&fields[items]=id,order_id,qty,price
&fields[companies]=id,name
&fields[subcompanies]=id,name
```
Now I understand this warning in the documentation.
[Selecting fields for included relations](https://spatie.be/docs/laravel-query-builder/v4/features/selecting-fields#content-selecting-fields-for-included-relations)

Note: Also I noticed to specify the fields to the relations I have to use it name in plural.
