### ISSUE TITLE
Scope Filters of arrat values

### ISSUE THREAD

**Issue by ronssij** [spatie/laravel-query-builder#614]
```
AllowedFilter::scope('duration', 'whereInDurationRange')

// Model scope
public function scopeWhereInDurationRange(Builder $query, $duration)
{
    $min = $duration[0] * 60;
    $max = $duration[1] * 60;

    return $query->where('duration', '>=', $min)
        ->where('duration', '<=', $max);
}
```

The query works using a callback filter.

```
AllowedFilter::callback('duration', function ($query, $duration) {
  $min = $duration[0] * 60;
  $max = $duration[1] * 60;

  return $query->where('duration', '>=', $min)
      ->where('duration', '<=', $max);
})
```

But doesnt work on scope filter as expected. The filter value is not passed as an array but instead as a string.

![image](https://user-images.githubusercontent.com/24932380/110285556-5d711b80-801e-11eb-9e40-b929dce93d71.png)

**Comment by williamxsp** [comment]
@ronssij What was the problem?

**Comment by williamxsp** [comment]
If anyone else is having this problem, you must use the three dots syntax in your scope as explained here https://github.com/spatie/laravel-query-builder/issues/334#issuecomment-552113812
