### ISSUE TITLE
Nested array in filters

### ISSUE THREAD

**Issue by dadigu** [spatie/laravel-query-builder#62]
I'll start of by saying thank you for a great package.

How ever there is one functionality that I'm missing, that is to have nested array filter query params. To give you some context is that I'm trying to build a filter that need a very nested set from the url query string. I was able to build a normal range filter by calling `filter[price][min]=1` and `filter[price][max]=10` That works all fine and good when I'm querying directly to a Products model.

However our database set up is something like this `Product->hasMany(Stock)->hasOne(Warehouse)` So what I wanted to achieve is to build a filter such as this: `filter[stock][warehouseName][min]=10` Currently if I try this query then it blows up with a 500 error.

I was able to get my filter to work but then the query params look something like this `filter[stock][warehouseName:min]=10` but then in the filter I need to explode the keys and the whole thing is very dirty and doesn't match the way i'm filtering the price for example.

Is this something that could be implemented/allowed?

**Comment by freekmurze** [comment]
Our package does support calling scopes: https://github.com/spatie/laravel-query-builder#scope-filters

You could define `scopeStock`, `scopeMinimumPrice` and `scopeMaximumPrice` on your model. 

Would that work for you?

**Comment by dadigu** [comment]
Oh cool, I see that this is a recent addition to the package, I didn't notice it. This actually would solve another problem I have, that's fantastic. I'll see if I can use the scope filter for what I'm trying to to, Thanks!

How ever I still think that the `$filtersMapper` in the Request macro `filters` should be recursive so it would be possible to have very nested filters if someone needs that for some very custom filters.

I'll see if I can make a PR for that if you are interested.

Thanks again for pointing out the scopeFilter. Powerful 💪

**Comment by freekmurze** [comment]
Sure, send us a well tested and well documented PR.

If the code is simple enough, we’ll merge it 👍
