### ISSUE TITLE
Getting InvalidFieldQuery exception when using allowedFields with custom query parameters

### ISSUE THREAD

**Issue by vincent-lu** [spatie/laravel-query-builder#622]
Hi I'm having trouble getting this to work:

Assuming this is what I got in my controller index():
```php
QueryBuilder::for($model)
    ->allowedFields($fields)
    ->allowedIncludes($includes)
    ->allowedFilters($filters)
    ->allowedSorts($sorts)
    ->allowedAppends($appends)
    ->get();
```

If I query something like `/products?sort=-id&fields[products]=id` the above works as intended.

However if I add some arbitrary query parameters to my request url, say something like `&foo=bar` so the query now looks like `/products?sort=-id&fields[products]=id&foo=bar` I get InvalidFieldQuery exception, the error message looks like this:

`Requested field(s) products?foo=bar.id are not allowed. Allowed field(s) are products.id.....`

If I remove the `fields[products]=id` in my query, or remove the `->allowedFields($fields)` (basically disable `allowedFields`), it works but obvious I lose the ability to select specific fields.

Using Laravel 8 and Laravel Query Builder 3.3.4. Thanks.

**Comment by AlexVanderbist** [comment]
Hi @vincent-lu! Are you still having issues with this? If not, feel free to close the issues.

If you are, can you please post the exact URL you tried and the error message it returned? 

`Requested field(s) products?foo=bar.id are not allowed. Allowed field(s) are products.id.....` makes it seem like there's a lot going wrong. For a start `products?foo=bar.id` is definitely not a field so I'm quite confused how that happened.

Feel free to post your query builder config file too if you've changed anything there. Thanks!

**Comment by vincent-lu** [comment]
Hi @AlexVanderbist thanks for getting back to me. Honestly the original complaint was so long ago before I completely rewrote my wrapper around `spatie/laravel-query-builder` I don't remember what the cause was and how I fixed it.

Will just close this.
