### ISSUE TITLE
Filter doesn't not filter by null/empty

### ISSUE THREAD

**Issue by vincent-lu** [spatie/laravel-query-builder#624]
This issue seemed was fixed a long time ago here https://github.com/spatie/laravel-query-builder/issues/88 / https://github.com/spatie/laravel-query-builder/commit/2334c94e840de882dd20e8b54c51b357109e5bcd

But using current version of  `"spatie/laravel-query-builder": "^3.3"` I don't get the expected result when:

Request: `/users?filter[last_name]=`
Expected behaviour: `User::where('last_name', '')->orWhere('last_name', null)`
Current behaviour: `User::all() // no filtering on last_name at all`

Thanks in advance.

**Comment by freekmurze** [comment]
I'm thinking that changing this behaviour now could be a breaking change. It's probably something for us to fix in the next major release.

**Comment by vincent-lu** [comment]
np thanks @freekmurze

**Comment by rickgoemans** [comment]
This of course only works for a single column but feel free to adjust it with a customer delimiter for checking multiple columns.

**Comment by TheDoctor0** [comment]
There is a simpler solution to this problem - extending the `AllowedFilter` and overriding the `filter` function:
```php
class AllowedNullableFilter extends AllowedFilter
{
    public function filter(QueryBuilder $query, $value): void
    {
        $valueToFilter = $this->resolveValueForFiltering($value);

        ($this->filterClass)($query, $valueToFilter, $this->internalName);
    }
}
```
Then it can be used as you would expect:
```php
QueryBuilder::for(Model::class)
  ->allowedFilters([
    AllowedNullableFilter::exact('column'),
  ])
```

**Comment by benswinburne** [comment]
Another way you can do this is

```
<?php

namespace App\Filters;

use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\Filters\Filter;

class TypeNullFilter implements Filter
{
    public function __invoke(Builder $query, $value, string $property)
    {
        $query->when(
            $value === 'null',
            fn($query) => $query->whereNull($property),
            fn($query) => $query->where($property, $value)
        );
    }
}
```

```
 $query->allowedFilters([
    AllowedFilter::custom('type', new TypeNullFilter()),
]);
```

Which allows you to pass `filter[type]=null` onto the query string.

This is obviously an issue if you expect a string value `"null"` but in my case it was filtering an enum column so no risk of that.

**Comment by bianchi** [comment]
I needed to support arrays allowing null values, so I made another condition in @benswinburne code:


```
<?php declare(strict_types=1);

namespace App\QueryBuilder\Custom;

use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\Filters\Filter;

class ExactFilterAllowNull implements Filter
{
    public function __invoke(Builder $query, $value, string $property): void
    {
        if (is_array($value)) {
            $hasNull = collect($value)->contains('null');
            $valuesWithoutNull = collect($value)->filter(fn ($value) => $value !== 'null')->toArray();
            
            $query->whereIn($property, $valuesWithoutNull);

            if ($hasNull) {
                $query->orWhereNull($property);
            }

            return;
        }

        $query->when(
            $value === 'null',
            fn ($query) => $query->whereNull($property),
            fn ($query) => $query->where($property, $value)
        );
    }
}


```

**Comment by Chomiciak** [comment]
Will this issue be addressed?

**Comment by sneycampos** [comment]
ping @freekmurze this was fixed or any solution in the current release?

**Comment by AlexVanderbist** [comment]
Please feel free to open a new PR if anyone believes there is still room for improvement in this package. In the meantime, I will remove it from the documentation.
