### ISSUE TITLE
Disable InvalidFilterQueryException does not work on v3.2.2

### ISSUE THREAD

**Issue by urameshibr** [spatie/laravel-query-builder#628]
Hello, actually im using the v3.2.2 of this package, i must to disable the InvalidFilterQueryException when any not available filter appears on query string. I tought adding the key `"disable_invalid_filter_query_exception" => true` in `config/query-builder.php` solves, but unfortunally that does not work.

i did try to clear the chache and config of Laravel by the artisan, nothing happens.

_Originally posted by @urameshibr in https://github.com/spatie/laravel-query-builder/discussions/627_

**Comment by AlexVanderbist** [comment]
What version of the package are you using? On the latest version the check for the config value should be here: https://github.com/spatie/laravel-query-builder/blob/master/src/Concerns/FiltersQuery.php#L65-L67

Feel free to send a PR if this needs to be changed or tested differently.

**Comment by SlimGee** [comment]
I have almost the same issue but throws an `InvalidFilterQuery` exception on unknown sorts, I checked the source code, on the method that `ensures sorts are valid` there is no check for the config flag

**Comment by AlexVanderbist** [comment]
I've had a quick look into this issue but couldn't replicate it. Feel free to open a PR adding that check for the config flag on the `v3` branch.
