### ISSUE TITLE
hasManyThrough pulls ID's from the wrong table

### ISSUE THREAD

**Issue by lioneaglesolutions** [spatie/laravel-query-builder#631]
When using the QueryBuilder with a hasManyThrough relationship, the output has models pulled by the ID of the pivot table - not the model itself.

**Controller Method**
```php
    public function index(Site $site)
    {
        $patients = QueryBuilder::for($site->patients())->jsonPaginate();

        return PatientResource::collection($patients);
    }
```

**Relationship Definition**
```php
class Site extends Model
{
    ....
    public function patients()
    {
        return $this->hasManyThrough(
            Patient::class,
            PatientLocation::class,
            'site_id',
            'id',
            'id',
            'patient_id'
        );
    }
}

```
**Request URL**
`/api/v1/sites/1/patients?page[number]=1&page[size]=25`

When passing the request to this controller, when querying using the first site (`$site->id = 1`), I get the below output;
![image](https://user-images.githubusercontent.com/61766491/119314160-c11ef280-bcb7-11eb-973f-8c48c6fd8d01.png)

The ID's 1, 15, 19 and 23 are actually coming from the pivot table for the model `PatientLocation`.
![image](https://user-images.githubusercontent.com/61766491/119308392-54ecc080-bcb0-11eb-947a-86f6ec3fb222.png)

The return patients should have had the ID's 4, 18, 22 and 26 as seen from the database image above.

When I use this code in the controller, it all works fine;
```php
    public function index(Site $site)
    {
        $patients = QueryBuilder::for(Patient::class)->bySite($site)->jsonPaginate();

        return PatientResource::collection($patients);
    }
```
**Correct Response**
![image](https://user-images.githubusercontent.com/61766491/119314192-ce3be180-bcb7-11eb-91d8-f8dcaf86d024.png)

**Scope Code**
```php
    public function scopeBySite(Builder $query, Site $site)
    {
        return $query->whereHas('site', function (Builder $query) use ($site) {
            $query->where('sites.id', $site->id);
        });
    }
```

But it is tedious to have to define a scope for relationships that are already defined.

The `Patient::class` uses `users` for the table and `PatientLocation::class` uses `patient_location`

**Comment by AlexVanderbist** [comment]
Hi, that doesn't seem right indeed. Does that query work when you don't use the query builder package?

If you've not using any filters/includes/etc, the query builder package wont actually change the query. This means that the executed query would be the same as `$site->patients()->jsonPaginate()`.

**Comment by lioneaglesolutions** [comment]
@AlexVanderbist there is definitely some strange behaviour going on.

Let's just focus on `Avis` with `id = 196`. 

This is what is in the database essentially;
`u = users, pl = patient_locations`
| u.id | u.first_name |  | pl.id | pl.client_id | pl.site_id | pl.department_id |
| :---: | :------------:| :--: | :---------: | :---------: | :---------: | :---------: |
|196 | Avis| | 193 | 1 | 1 | 1 |
|193 | Kaitlyn| | 190 | 8 | 15 | 29 |

This works as expected and returns the models correctly
```php
    public function index(Site $site)
    {
        $patients = $site->patients()->paginate();

        return PatientResource::collection($patients);
    }
```

Response (one of the models only and some data removed for easier viewing)
```javascript
      {
         "id":196, // correct id
         "first_name":"Avis", // correct name
         "location":{ // patient_location.id = 193 which is correct
            "client":{
               "id":1,
            },
            "site":{
               "id":1,
            },
            "department":{
               "id":1,
            }
         },
      }
```

This however doesn't work correctly
```php
    public function index(Site $site)
    {
        $patients = QueryBuilder::for($site->patients())->jsonPaginate();

        return PatientResource::collection($patients);
    }
```

Response
```javascript
      {
         "id":193, // wrong ID but correct name and other attributes?
         "first_name":"Avis", // correct name
         "location":{ // patient_location.id = 196 which is incorrect
            "client":{
               "id":8,
            },
            "site":{
               "id":15,
            },
            "department":{
               "id":29,
            }
         },
      }
```

**Comment by lioneaglesolutions** [comment]
I think the issue lies with `jsonPaginate` actually... when doing;
```php
return QueryBuilder::for($site->patients())->paginate();
```
I believe it is running as expected.
