### ISSUE TITLE
Filter not working in case of nested hasMany relationship

### ISSUE THREAD

**Issue by DHSprout** [spatie/laravel-query-builder#639]
In my scenario I have to do search on the coulmn which is present in 3rd table respective of table relationship .

For example: 
QueryBuilder::for(User::class)
            ->allowedFilters('campaigns.redirectionurls.url')
            ->allowedIncludes('campaigns,campaigns.redirectionurls')
            ->allowedFields('name', 'uuid', 'id', 'campaigns.product_url', 'campaigns.created_by', 'campaigns.id', 'campaigns.redirectionurls.id', 'campaigns.redirectionurls.campaign_id')
            ->paginate();

In this query it is failing with error :
 Unknown column 'redirectionurls' in 'where clause' 

It is considering redirectionurls in the allowedFilters as column instead of relationship.
Could you please help.

**Comment by mitchierichie** [comment]
@DHSprout see my issue #640 - it's totally undocumented and unexpected behavior, but they only check for the existence of a method that matches the CAMEL case of the allowedFilter. As a workaround until (hopefully) my PR for this issue gets merged, you can duplicate all your relationship methods in camel case.

What I did was create a method that just calls my existing relationship method, for example I have product_model relationship, I created productModel() that just returns product_model().

**Comment by AlexVanderbist** [comment]
Hey, can you PR a failing test for this please? I've played around with it but its seems like this test covers the issue you're experiencing:
https://github.com/spatie/laravel-query-builder/blob/fce2df57b3e09f55b781380579319bdfdc73a6c9/tests/RelationFilterTest.php#L70
