### ISSUE TITLE
cursorPaginate breaks inRandomOrder

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-query-builder#645]
I'm testing the newly introduced `cursorPaginate`, all seems to work fine, however using `inRandomOrder` results in:
```
{
    "message": "array_flip(): Can only flip string and integer values, entry skipped",
    "exception": "ErrorException",
    "file": "/home/user/www/src/api/vendor/laravel/framework/src/Illuminate/Collections/Collection.php",
    "line": 382,
..
```

Is this expected or a known bug? I'm simple calling a custom filter and works fine using `paginate`:
```
<?php

namespace App\Support\QueryBuilder\Sorters;

use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\Sorts\Sort;

class RandomSorter implements Sort
{
    public function __invoke(Builder $query, bool $descending, string $property): Builder
    {
        return $query->inRandomOrder();
    }
}
```

Thanks!

**Comment by francoism90** [comment]
Hmm, shouldn't this return a `lazyCollection` instead of a ` Collection`?

Is this a Laravel bug? If I change `Illuminate/Collections/Collection.php:382",` to be the same as `Illuminate/Collections/LazyCollection.php:382", it all works fine.

**Comment by driesvints** [comment]
You can't use `inRandomOrder` with cursor based pagination. The entire concept of cursor based pagination is that you have a fixed order.

**Comment by francoism90** [comment]
@driesvints Thanks for your reply. :)

What if you use a random seed? Something like `$query->inRandomOrder(1000)`.
If I understand correctly it isn't possible to use `orderBy` giving by IDs?

**Comment by driesvints** [comment]
> What if you use a random seed? Something like $query->inRandomOrder(1000).

I haven't tested that myself.

> If I understand correctly it isn't possible to use orderBy giving by IDs?

Sure you can. I'm not sure why you think it isn't?

**Comment by francoism90** [comment]
@driesvints I've tried using InRandomOrder including a seed, but it unfortunately still breaks with the same error. Applying the lazy collection logic fixed the issue, but I don't think this is the cause?

Oh, still need to find out how cursor pagination works, sorry!

**Comment by francoism90** [comment]
@AlexVanderbist This hasn't been fixed, why is it closed? :)
