### ISSUE TITLE
CHANGELOG.md has forgotten about 1.18.0

### ISSUE THREAD

**Issue by Peter-Krebs** [spatie/laravel-query-builder#647]
The version 1.18.0 added support for Laravel 6 and PHP 8, according to [1.18.0 changelog](https://github.com/spatie/laravel-query-builder/blob/1.18.0/CHANGELOG.md).

- In [version 2.0.0's changelog](https://github.com/spatie/laravel-query-builder/blob/2.0.0/CHANGELOG.md) this change has already been forgotten and doesn't list 1.18.0
- The current version (as of this writing) [with the changelog for 4.0](https://github.com/spatie/laravel-query-builder/blob/701ec14466894f02265c340b82fe91ea1fc78b7e/CHANGELOG.md) also has no mentioning of 1.18.0

I assume this in-between version has been forgotten over time.  
Fixing the history of changelogs is not feasable IMO, but could be rectify this lost version in the current changelog?

Thanks!

**Comment by freekmurze** [comment]
We don't use v1 anymore, so we're not going to invest time it. Feel free to PR changes you need to the v1 version.

**Comment by Peter-Krebs** [comment]
It is not about V1 for me, it's about representing the correct history in the changelog.  
A PR to the v1 branches doesn't do anything - the last v1 version was 1.18.0 I mentioned. The changelog is correct there.

If you don't mind forgetting about 1.18.0 in the changelogs since 2.0.0 I don't think I have to care either.  
So nevermind, this can stay closed then.
