### ISSUE TITLE
AllowedFields are not taking into consideration the relationship fields

### ISSUE THREAD

**Issue by PharaohAsh** [spatie/laravel-query-builder#681]
**Using V4.0.1**

When we do the following:
```
QueryBuilder::for(Post::class)
    ->allowedFields('author.id', 'author.name')
    ->allowedIncludes('author');
```

And query the endpoint like so:
```
GET /posts?include=author&fields[author]=id,name
```

It appears to list _all_ the fields of the `author` and not **just** `id` and `name`.

I think the issue lies [here `->get($table)`](https://github.com/spatie/laravel-query-builder/blob/main/src/Concerns/AddsFieldsToQuery.php#L57) where it's grabbing the `$table` instead of the `$relation` from the collection of fields.

**Comment by wattsie** [comment]
I too have just ran into the similar issue (v4.0.1 as well)

I tried applying a resource to each of the keys within the main resource. ie.
```
    public function toArray($request)
    {
        // return parent::toArray($request);
        return [
            'id' => $this->id,
            'name' => $this->name,
            'first_include' => (new FirstResource($this->first)),
            'second_include' => (new SecondCollection($this->second)),
        ];
    }
```
But it appears, when I call the `$this->first` it pulls in the entire record, thus does not obey the include'd requirement within the URL.

It would be awesome if any included/related models apply their resource or resource collections.

**Comment by wattsie** [comment]
FYI: I have found a work around.

By checking the `relationsToArray` I have found which additional includes have been defined.

Then I just check and convert into either Resource or ResourceCollection as required.

```
class PrimaryResource extends JsonResource
{
    public function toArray($request)
    {
        $ret_val = [
            'id' => $this->id,
            'name' => $this->name,
        ];
        // Include resource
        if (array_key_exists('first_include', $this->relationsToArray())) {
            $ret_val['first_include'] = (new FirstIncludeResource($this->first_include));
        }
        // Include a resource collection
        if (array_key_exists('second_include', $this->relationsToArray())) {
            $ret_val['second_include'] = (new SecondIncludeCollection($this->second_include));
        }
        return $ret_val;
    }
}
```

**Comment by jpgilchrist** [comment]
I just ran into this issue as well today. Same thing specifying fields on a relationship is not added to the select statement. If the field is for the root object, then it does work. 

?include=author&fields[post]=id&fields[author]=id,name

outputs 

`select post.id from post ... `

omitting the ?field[post]=id just results in a `select * ...`

**Comment by claudiofabiao** [comment]
Same problem here. Using version 4.0.1 too.

**Comment by klimov-paul** [comment]
You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) instead. It does provide the ability to specify selected fields for the relations.

**Comment by rezaffm** [comment]
Hello, I am facing the same issue - is there any solution?

**Comment by dominikb** [comment]
As pointed out by @PharaohAsh initially the problem is with how the table name is inferred using the relation string:

```php
QueryBuilder::for(Post::class)
  ->allowedIncludes('author')
  ->allowedFields('author.id', 'author.name')

// Relation author is transformed to table 'authors'
// AddsFieldsToQuery.php
$table = Str::plural(Str::snake($relation)); // TODO: make this configurable
```

A workaround could be to specify the included fields with this transformation in mind:
```php
QueryBuilder::for(Post::class)
  ->allowedIncludes('author')
  ->allowedFields('authors.id', 'authors.name')
```

One thing to keep in mind: you always need to include the **key** for 1-to-1 relations and the **foreign_key** for 1-to-many relations for Eloquent to be able to correctly associate the retrieved results. [Stackoverflow: Query specific columns for relations](https://stackoverflow.com/a/19921418/9989613)

@rezaffm Upgrading to v5 will currently not help with this issue.

I'll try to open a PR to fix this issue in a couple of days.

**Comment by rezaffm** [comment]
Great stuff, much appreciated.

Would be great if it works for 4v as well then, not ready for Laravel 9 yet :-)

**Comment by lrfahmi** [comment]
This issue can't be fixed yet?

../Concerns/AddsFieldsToQuery.php

```
$table = Str::plural(Str::snake($relation)); // TODO: make this configurable

$fields = $this->request->fields()->mapWithKeys(function ($fields, $table) {
    return [$table => $fields];
})->get($table);
```
Why not rollback like the previous version? Is it related to the others?
```
$fields = $this->request->fields()->mapWithKeys(function ($fields, $relation) {
    return [Str::camel($relation) => $fields];
})->get($relation);
```

**Comment by anayarojo** [comment]
I could solve this issue using, from the HTTP query, the relationship name in plural and adding the fields that keep the relationships.

For example:

![image](https://user-images.githubusercontent.com/6903495/211083912-9e7ba354-6274-4a2d-94e5-ea5a2c003e56.png)


```
https://myproject.test/query
?limit=5
&include=items,company,subcompany
&fields[orders]=id,created_at,updated_at,company_id,subcompany_id
&fields[items]=id,order_id,qty,price
&fields[companies]=id,name
&fields[subcompanies]=id,name
```

**Comment by zeinabmsalem** [comment]
> As pointed out by @PharaohAsh initially the problem is with how the table name is inferred using the relation string:
> 
> ```
> QueryBuilder::for(Post::class)
>   ->allowedIncludes('author')
>   ->allowedFields('author.id', 'author.name')
> 
> // Relation author is transformed to table 'authors'
> // AddsFieldsToQuery.php
> $table = Str::plural(Str::snake($relation)); // TODO: make this configurable
> ```
> 
> A workaround could be to specify the included fields with this transformation in mind:
> 
> ```
> QueryBuilder::for(Post::class)
>   ->allowedIncludes('author')
>   ->allowedFields('authors.id', 'authors.name')
> ```
> 
> One thing to keep in mind: you always need to include the **key** for 1-to-1 relations and the **foreign_key** for 1-to-many relations for Eloquent to be able to correctly associate the retrieved results. [Stackoverflow: Query specific columns for relations](https://stackoverflow.com/a/19921418/9989613)
> 
> @rezaffm Upgrading to v5 will currently not help with this issue.
> 
> I'll try to open a PR to fix this issue in a couple of days.

>Regarding the issue of passing the foreign_key for 1-to-many relations is there is any solution for not passing it?

**Comment by thewebartisan7** [comment]
Spatie, please to update your docs for avoid to lost so much time with this, since this example here will not works with default config: https://spatie.be/docs/laravel-query-builder/v5/features/selecting-fields#content-selecting-fields-for-included-relations

Is missing to mention to use plural when selecting fields for a relation like post->author

**Comment by thewebartisan7** [comment]
Spatie, please to update your docs for avoid to lost so much time with this, since this example here will not works with default config: https://spatie.be/docs/laravel-query-builder/v5/features/selecting-fields#content-selecting-fields-for-included-relations

Is missing to mention to use plural when selecting fields for a relation like post->author

```php
// fields[authors] and NOT fields[author]
// GET /posts?include=author&fields[authors]=id,name

QueryBuilder::for(Post::class)
    ->allowedFields('author.id', 'author.name')
    ->allowedIncludes('author');
```
