### ISSUE TITLE
Eloquent query gets ignored since 1.9.1

### ISSUE THREAD

**Issue by mr-jingles** [spatie/laravel-query-builder#69]
Hi, 
since Version 1.9.1 Eloquent Querys get ignored. Basically I do something like this:

QueryBuilder::for(Order::select(#some columns))
                                  ->allowedFilters(#same columns as above)
                                  ->paginate($request->per_page);

Before 1.9.1 only those columns I selected where in the endresult - with 1.9.1 onwards this part will be ignored. Is this a bug or do I have to refactor this code somehow?

Thanks

**Comment by freekmurze** [comment]
Feel free to subject a PR that fixes this problem. Could you also provide a test?

**Comment by ziming** [comment]
The following code previously works but now fails too:

```
return new UserResource(QueryBuilder::for(User::class)
            ->allowedIncludes(['abc','def'])
            ->findOrFail($id)
        );
```

With an error message like:

```
{
    "message": "Method Illuminate\\Database\\Query\\Builder::collection does not exist.",
    "exception": "BadMethodCallException",
```

I believe it is related to the issue mr-jingles raised too

**Comment by afraca** [comment]
It doesn't seem to be the case **any** query will be ignored, I just used `QueryBuilder::for(MyModel::whereHas())` and it looked fine.

**Comment by AlexVanderbist** [comment]
Hi! Sorry to keep you waiting for so long. I've just added a test in f9bc6c7 to test this issue and it looks like it's no longer happening in the latest version of the package... Are you still having this issue? If so, feel free to open a new issue and we'll look at it :)

**Comment by mr-jingles** [comment]
I worked around that problem - so currently I am not facing that issue. If it occurs again I might open a new issue. ;) Thanks!
