### ISSUE TITLE
Can this package be used with MongoDB model?

### ISSUE THREAD

**Issue by mrlinnth** [spatie/laravel-query-builder#698]
Tried to search if mongodb is supported or not at old issues/discussion and couldn't find any.

Can someone help or guide me in the right direction?

I am connecting Mongo DB and want to use this package but facing issue.

![image](https://user-images.githubusercontent.com/4952597/145562894-fb904fb7-0a7e-4f84-ad12-ac74dfbdb847.png)

**Comment by weogrim** [comment]
It seems to me that this package is not capable of working with MongoDB. I've been trying right now to find out why, and I locate `Spatie\QueryBuilder\Filters\FiltersPartial` which construct RAW **SQL** query:

```
(...)
$sql = "LOWER({$wrappedProperty}) LIKE ?";
(...)
$query->whereRaw($sql, ["%{$value}%"]);
```

**Comment by mrlinnth** [comment]
@weogrim yea I also concluded that this is not compatible for MongoDB models yet.

Since I am developing a REST API app, I have switched to laraveljsonapi package instead.

**Comment by klimov-paul** [comment]
You may try to use [illuminatech/data-provider](https://github.com/illuminatech/data-provider) instead.

**Comment by ce-brex** [comment]
Just ran into this issue as well, my current workaround is to use Filter::callback() or Filter::custom() instead.
