### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kimulisiraj** [spatie/laravel-query-builder#703]
<img width="307" alt="Screenshot 2021-12-28 at 13 05 09" src="https://user-images.githubusercontent.com/8648780/147555042-c5952cea-c44e-4404-a549-2c112a123f5e.png">
👆That link is broken on the about us section. 
Please change it to `https://spatie.be/docs/laravel-query-builder/v3/introduction`

**Comment by freekmurze** [comment]
Done!

**Comment by kimulisiraj** [comment]
🎉👏
