### ISSUE TITLE
Navigation in v5 docs broken

### ISSUE THREAD

**Issue by jsandfordhughes** [spatie/laravel-query-builder#712]
The navigation on the v5 docs seem to be trying to visit a URL with /v3/ in the URL which then gets stuck in an unlimited redirect loop.

I have had a look in the docs folder however I cannot see the navigation code. 

The top of the page also states we are on v3 docs.

Screenshots attached to try and help with the explanation.

![CleanShot 2022-01-13 at 12 25 34](https://user-images.githubusercontent.com/35659248/149329971-2580d89a-04b8-4121-8369-6a040e6f3377.png)

![CleanShot 2022-01-13 at 12 26 53](https://user-images.githubusercontent.com/35659248/149330127-2a802079-3842-4816-998e-8ad57e52731d.png)

**Comment by williamxsp** [comment]
If you type v5 at the url bar instead of v3 it loads correctly.

**Comment by jsandfordhughes** [comment]
Yes that is correct, just wanted to make them aware 😄
