### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by punyflash** [spatie/laravel-query-builder#725]
Trying to migrate my project to Laravel 9. After upgrading `laravel-query-builder` to version 5.0.0 I get the error:
```
Call to undefined method Spatie\QueryBuilder\QueryBuilder::allowedAppends()
```
It seems like there is no more [appending attributes](https://spatie.be/docs/laravel-query-builder/v4/features/appending-attributes) point for version 5 as well. Why this feature was removed?

**Comment by pionl** [comment]
Good to know, maybe update the "changelog" and release notes? Thank you

**Comment by wi-wissen** [comment]
For me, the Feauture appending attributes was very helpful. For example to add computed properties only when needed or allowed by role.

Fortunately you still kept all needed functions in `QueryBuilderRequest`. So I only had to restore `AppendsAttributesToResults` and `InvalidAppendQuery` and overwrite `__call` from `QueryBuilder`.

Is it planned to leave `QueryBuilderRequest` like this? If not, it would be a consideration changing variables like

`private static $includesArrayValueDelimiter = ',';` to `protected` for easier overwriting?

**Comment by kurorido** [comment]
I follow @wi-wissen suggestion and made a fork.

https://github.com/kurorido/laravel-query-builder/commit/067595efaeacfcb7c91f46df5f878ddce3cd9fb6

**Comment by btxtiger** [comment]
@kurorido how did you install the fork?
Composer wouldn't allow me to install it, because the branch name `"Invalid version string "main"`

**Comment by euoia** [comment]
I was also using this feature and was surprised by its removal after upgrading to Laravel 9.

@freekmurze Given that this is a breaking change, I would love to see some guidance on how to migrate existing code that was using this feature. Given that people were using this feature, UPGRADING.md could be worded a bit better:

>  The rest of the public API was not changed, so you'll be able to upgrade without making any changes.

I guess the simplest way is to modify your code to call `append` on the query result. In my own code, I have a class that wraps QueryBuilder (and adds pagination, aggregation, etc) so this was quite straightforward to do. I added validation like this:

```php
           $appendStr = $request->input("append", null);
        $appends = $appendStr === null ? [] : explode(",", $appendStr);
        $appendsNotAllowed = [];

        foreach ($appends as $append) {
            if (collect($this->allowedAppends)->contains($append) === false) {
                $appendsNotAllowed[] = $append;
            }
        }

        if (count($appendsNotAllowed) > 0) {
            $allowedAppendsStr = implode(", ", $this->allowedAppends);
            $appendsNotAllowedStr = implode(", ", $appendsNotAllowed);

            throw new \Exception(
                "Requested append(s) `{$appendsNotAllowedStr}` are not allowed. Allowed append(s) are `{$allowedAppendsStr}`."
            );
        }
```

I do feel like there is a place for a library with these additional features (pagination, aggregation, transformation, etc). @freekmurze do you know if that's something Spatie is likely to create? If not, I could possibly tidy up and release my version.

**Comment by prodigy7** [comment]
That is a great pity that the functionality has been removed. This is important for me in some respects. Now I'll probably have to work with not so nice workarounds.

**Comment by TheFrankman** [comment]
Anyone come up with an elegant solution for this ? I was hoping to use this package as a means to resolve the append methods constantly causing query bloat. Maintaining a Fork can be quite troublesome and whose to say that future updates of this package will make the fork incompatible.

**Comment by btxtiger** [comment]
We recently found out that using the Model Attributes can create a huge performance lack, as it seems those functions get called for each model even if they are not explicitly required. So we decided to implement our own logic by using a custom queryParameter and naming the functions different than `get....Attribute`. This way we are also able to call nested functions if it is required. I can share our code later.

**Comment by TheFrankman** [comment]
> We recently found out that using the Model Attributes can create a huge performance lack, as it seems those functions get called for each model even if they are not explicitly required. So we decided to implement our own logic by using a custom queryParameter and naming the functions different than `get....Attribute`. This way we are also able to call nested functions if it is required. I can share our code later.

I would appreciate the code share. I like you have the same issue, it will be a massive task to unpick it at this stage, but at least we have unit tests !

**Comment by harlan-zw** [comment]
Can we at least keep this issue open (and renamed for clarity) to make it easier to find this issue until it's properly documented?

**Comment by btxtiger** [comment]
@TheFrankman 
This is how I solved it for now. I'll update this comment if I find some conflicts in my app. But it seems to work fine for now.
```php
if ($request->append) {
   $appends = collect(explode(',', $request->append));
   $data->each(function ($row) use ($appends) {
      $appends->each(function ($attr) use ($row) {
         $attrFnName = Str::camel('get_' . $attr . '_attribute');
         if (method_exists($row, $attrFnName)) {
            return $row->append($attr);
         }
         
         throw new \Exception("Append attribute <$attr> not found in model " . get_class($row));
      });
      
      return $row;
   });
}
```

**Comment by abbluiz** [comment]
It seems there are more ways of defining Attributes in Laravel 11 than creating "
get...Attribute()" methods.

**Comment by btxtiger** [comment]
Since we had the requirement now, I added support for loading nested appends on relations:
`/api/vendors?include=vendorProjects&append=vendorProjects.merchandise_value,vendorProjects.sku_count`

```php
   // FIX APPENDS WITH RELATION SUPPORT
   protected function addAppendsFix(Request $request, Collection|LengthAwarePaginator|Model $data): Collection|LengthAwarePaginator|Model {
      if ($request->append) {
         $appends = collect(explode(',', $request->append));

         $applyAppends = static function ($item, $path) use (&$applyAppends) {
            $segments = explode('.', $path);
            $current = $item;

            foreach ($segments as $index => $segment) {
               if ($index === count($segments) - 1) {
                  $method = Str::camel('get_' . $segment . '_attribute');
                  if (method_exists($current, $method)) {
                     $current->append($segment);
                  } else {
                     throw new \RuntimeException("Append attribute <$segment> not found in model " . get_class($current));
                  }
               } else {
                  $current = $current->{$segment};

                  if (!$current) {
                     throw new \RuntimeException("Relation <$segment> not found or not loaded in model " . get_class($item));
                  }

                  if ($current instanceof Collection) {
                     $current->each(fn($relItem) => $applyAppends($relItem, implode('.', array_slice($segments, $index + 1))));
                     return;
                  }

                  if (!$current instanceof Model) {
                     throw new \RuntimeException("Invalid relation type <$segment> in model " . get_class($item));
                  }
               }
            }
         };

         $processData = static function ($item) use ($appends, $applyAppends) {
            $appends->each(fn($path) => $applyAppends($item, $path));
         };

         if ($data instanceof Collection || $data instanceof LengthAwarePaginator) {
            $data->each($processData);
         } elseif ($data instanceof Model) {
            $processData($data);
         } else {
            throw new \RuntimeException('Unsupported data type: ' . gettype($data));
         }
      }

      return $data;
   }
```
