### ISSUE TITLE
PostgreSQL exception

### ISSUE THREAD

**Issue by josiasmontag** [spatie/laravel-query-builder#73]
#71  seems to break the `FilterPartial` in combination with Postgres.

I am getting:
``
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: ` character varying
LINE 1: ..._accounts"."user_id" is not null and LOWER(`some_filter`...
``

``
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select "my_accounts".* from "my_accounts" where "my_accounts"."user_id" = 1 and "my_accounts"."user_id" is not null and LOWER(`some_filter`) LIKE %something%)
``

PostgreSQL 9.6.3

Downgrading to version 1.9.2 solves the issue.

**Comment by freekmurze** [comment]
Seems like we only need to apply those backticks when using MySQL.

**Comment by josiasmontag** [comment]
Better: use `` $query->getGrammar()->wrap($property); ``
