### ISSUE TITLE
Config file publish documented is incorrect

### ISSUE THREAD

**Issue by Bosphoramus** [spatie/laravel-query-builder#738]
Docs say that the publish command for the configuration file is 
`php artisan vendor:publish --provider="Spatie\QueryBuilder\QueryBuilderServiceProvider" --tag="query-builder-config"`

But it doesnt work, its actually
`php artisan vendor:publish --provider="Spatie\QueryBuilder\QueryBuilderServiceProvider"`

**Comment by dominikb** [comment]
Hi 👋 

Did you check out issue #729? Are you using version 5 of this package?

The `--tag` parameter in the command narrows the scope of the published resources and can be omitted in this case. Check out the docs on [Laravel - Publish file groups](https://laravel.com/docs/9.x/packages#publishing-file-groups) for more information on that.

**Comment by Bosphoramus** [comment]
Oh ok thank you @dominikb 
So based on what im reading in that issue, shouldnt the documentation be adjusted and suggest the commans without the tag, so something gets published? Its weird to follow the installation options, and when at the moment you try to publish you get “No configuration files to publish”, when the docs clearly say that you have to use that commans if you want to publish the config file.

**Comment by dominikb** [comment]
Are you using the same version as in the documentation? Publishing older versions with this command will not work. I just tried it with v5 and this was my output. I think the documentation is correct.

```
composer create-project laravel/laravel test-laravel-query-builder
cd test-laravel-query-builder
composer require spatie/laravel-query-builder 

php artisan vendor:publish --provider="Spatie\QueryBuilder\QueryBuilderServiceProvider" --tag="query-builder-config"
```

> Copied File [/vendor/spatie/laravel-query-builder/config/query-builder.php] To [/config/query-builder.php]
> Publishing complete.

**Comment by Bosphoramus** [comment]
Id swear it was the latest query builder version on Laravel 8 instead of 9
