### ISSUE TITLE
PostgreSQL error on Filter Relationship

### ISSUE THREAD

**Issue by joaoVtr** [spatie/laravel-query-builder#755]
Hi. I have a problem when i try to filter a relationship on QueryBuilder. Error SQLSTATE[42883] Undefined function: 7 ERROR:  function lower

My error
![image](https://user-images.githubusercontent.com/61917597/170124723-aa43a79e-c198-4338-9134-542db951e237.png)

My code
  ```
 $query = QueryBuilder::for($this->model)
            ->allowedFilters($columns);
```
And my query
![image](https://user-images.githubusercontent.com/61917597/170125584-cfcec49a-5b59-42b3-9f20-dc218fc323fa.png)

I'm using Laravel 9, PostgreSQL 13.5, PHP 8.1

The issue #73 have a similar problem, but i dont understood the solution.

**Comment by joaovdiasb** [comment]
Hi, i belive it's becouse of this line: https://github.com/spatie/laravel-query-builder/blob/2e738da1ed5c34a452b1fc041862a5852ef8704d/src/Filters/FiltersPartial.php#L21
With some types of column you will be able to do it this way, but not for types like uuid, bigint...
the solution i found was to create a custom filter

and hi from Brazil, ES

**Comment by joaoVtr** [comment]
@joaovdiasb Obrigado pela resposta. Também criei um filtro pra isso. Nos resta ficar de olho caso o pacote faça alguma atualização a respeito. vlw
