### ISSUE TITLE
Ability to include withTrashed

### ISSUE THREAD

**Issue by twickstrom** [spatie/laravel-query-builder#77]
In the index of my user controller I have the following:

```
return QueryBuilder::for(User::class)
	->with('phoneNumbers')
	->allowedIncludes('trashed')
	->get();
```

I was hoping to pass an include param like this:

```
http://127.0.0.1:8000/v1/users?include=trashed
```

To append the `withTrashed()` global scope to the query. 

Is this possible? I am most likely missing something obvious, I have tried a few variations in my testing usually ending up with an error like:

```
"message": "Call to a member function addEagerConstraints() on boolean",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/Users/timwickstrom/Sites/Wavefire/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
    "line": 522,
```

Thanks for the help! This has been a HUGE time saver.

**Comment by twickstrom** [comment]
In case anyone else is looking for this I was able to make it work using filters.

```
return QueryBuilder::for(User::class)
	->with('phoneNumbers')
	->allowedFilters('withTrashed')
	->get();
```

And to interact with it is simple. Here is an example:
`http://127.0.0.1:8000/v1/users?filter[withTrashed]=true`

**Important Note**: in Laravel, withTrashed does not accept parameters, however adding =true or =1 is necessary for the scope to be attached.

**Comment by lionslair** [comment]
For me this approach is looking for a withTrashed field on the table. How did you get around that?

**Comment by twickstrom** [comment]
Make sure that you are using soft delete trait within your model. More info here:

https://laravel.com/docs/5.6/eloquent#soft-deleting

**Comment by paxcodes** [comment]
@twickstrom important note + @denitsa-cm last comment helped me:

```php
use Spatie\QueryBuilder\AllowedFilter;

// for ...?filter[withTrashed]=1
// it will not work with ...?filter[withTrashed]
...
->allowedFilters([AllowedFilter::scope('withTrashed')])
...
```
