### ISSUE TITLE
Exact filter on relationship making multiple sub query resulting in slow performance

### ISSUE THREAD

**Issue by anikgoel** [spatie/laravel-query-builder#788]
Hi

I am using this package at lot of places but recently putting multiple filters on relationship. And in the query log I found it is appending a lot of sub-query (exists) resulting in slow performance. What can be done?

I am using below filters - 

            AllowedFilter::exact('fuel_id', 'ownerVehicle.fuel_id'),
            AllowedFilter::exact('body_vehicle_id', 'ownerVehicle.body_vehicle_id'),
            AllowedFilter::exact('vehicle_first_register_year', 'ownerVehicle.vehicle_first_register_year'),
            AllowedFilter::exact('gearbox_id', 'ownerVehicle.gearbox_id'),
            AllowedFilter::exact('model_id', 'ownerVehicle.model_id'),
            AllowedFilter::exact('product_category_type_id', 'ownerVehicle.vehicle.product_category_type_id'),
            AllowedFilter::exact('product_type_id', 'ownerVehicle.vehicle.productCategoryType.product_type_id'),
            AllowedFilter::exact('brand_id', 'ownerVehicle.model.brand_id'),
            AllowedFilter::exact('model_id', 'ownerVehicle.model_id'),
            AllowedFilter::exact('body_condition_id', 'ownerVehicle.body_condition_id'),
            AllowedFilter::exact('owner_number', 'ownerVehicle.owner_number'),

**Comment by ericknyoto** [comment]
I faced a same issue, the performance really slow and even the mysql was time out for searching in a table of a million rows.

```php
$invoices = QueryBuilder::for(Invoice::class)
            ->allowedFilters([
                AllowedFilter::exact('invoice_number'),
                AllowedFilter::exact('type'),
                AllowedFilter::exact('invoiceDetails.order_id'),
                AllowedFilter::exact('invoiceDetails.order_number'),
                AllowedFilter::exact('sales_channel_id'),
            ])
            ->allowedIncludes('invoiceDetails')
            ->get();
```
            
Any idea how to solve this? Thanks.
