### ISSUE TITLE
hasMany relationship search filter throws an error

### ISSUE THREAD

**Issue by rajasekar-d** [spatie/laravel-query-builder#80]
### hasMany relationship search filter throws an error

**Eloquent Query:** 
`QueryBuilder::for(User::class)->allowedIncludes('roles')->allowedFilters(Filter::exact('role_id'))->with('roles')->paginate(20);`
**Query Parameters:** 
`/users?include=roles&filter[role_id]=5`
**Exception:** 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'role_id' in 'where clause' (SQL: select count(*) as aggregate from `users` where `role_id` = 5)

![image](https://user-images.githubusercontent.com/11868287/41609731-2426ead6-7409-11e8-881d-bb0130d48d71.png)

### Also i want to filter multiple columns(name, email) with single field
**Eloquent Query:**
`QueryBuilder::for(User::class)->allowedFilters('name','email')->paginate(20);`
**Query Parameters:**
`/users?filter[search]=search`

**Comment by freekmurze** [comment]
Out of the box a given `Filter` will operate on the table you're building up a query for.

If you want to filter on a related take a look at [this example in the readme](https://github.com/spatie/laravel-query-builder#custom-filters).
