### ISSUE TITLE
By default sorting by a non-existant property throws an error

### ISSUE THREAD

**Issue by jamiehd** [spatie/laravel-query-builder#81]
If you visit http://my-api.com/users?sort=thisfielddoesnotexist you recieve an sql error:

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'thisfielddoesnotexist' in 'order clause' (SQL: select `users`.* from `users` order by `thisfielddoesnotexist` asc limit 15 offset 0)"

I didn't set any  explicitly allowed sorting but it seems weird that the default allows for an SQL error to be triggered by the user.

**Comment by jamiehd** [comment]
Also if you do something like this:  http://my-api.com/users?fields[users]=doesnotexist

Then you get a similar SQL error. There does not even seem to be an allowedFields method so I can't see any way to avoid this at all.

Please let me know if I'm missing something obvious.

**Comment by AlexVanderbist** [comment]
Hi! The problem with the fields and sort url parameters is that we don't know what fields are available to sort/include. An `allowedFields` method would solve both of these issues, feel free to send a non-breaking and tested PR :) Thanks
