### ISSUE TITLE
laravel queryBuilder->withCount

### ISSUE THREAD

**Issue by DJafari** [spatie/laravel-query-builder#87]
if i want get relationship count only (`builder->withCount('childs')`) how can do it ?

**Comment by pactode** [comment]
You can chain the method to the `QueryBuilder` like this:

```php
$users = QueryBuilder::for(User::class)
    ->allowedFilters('name')
    ->withCount('posts')
    ->get();
```

**Comment by DJafari** [comment]
my bad, thanks

**Comment by paul-crashley** [comment]
Is there a way to do this as an allowed include? Or if not, is there a plan to do this or allow a pull request with such a feature?
