### ISSUE TITLE
filter not worked when value is empty

### ISSUE THREAD

**Issue by DJafari** [spatie/laravel-query-builder#88]
i want define a filter 

when value is empty ( `?filter[parent_id]=` ) must be : 

```php
where('parent_id', null)
```

```php
request()->filters() // return [];
```

when value not empty ( `?filter[parent_id]=1` ) :

```php
where('parent_id', 1);
```

```php
request()->filters() // return ['parent_id' => 1];
```

but in your library when value is empty, custom filters not called! how can solve it ?

**Comment by robsontenorio** [comment]
What URL does it build with this?

```
where('parent_id', null)
```

**Comment by DJafari** [comment]
@robsontenorio 

currently because `filter[parent_id]=` is empty, in `request->filters()` skipped, but i want get null parent_id from database

**Comment by DJafari** [comment]
i found a trick for that: 

JavaScript:
```js
let category = new Category();
category.where('parent_id', 0);
```

laravel:
```php
public function scopeParentId(Builder $query, $value): Builder {
    $value = (($value == 0) ? null : $value);
    return $query->where('parent_id', $value);
}
```

this is a trick, but i think you must add filters reverse, if i add `parent_id` as `allowedFilters` for example ( `Filter:scope('parent_id')` ) you must add it event value is empty

**Comment by nivv** [comment]
@AlexVanderbist if you make a request with an empty filter it breaks in my current setup. If the filter is null I want to ignore it.


```
# Below should be ignored as a filter in my current app
/api/objects?filter[available]=

# Below should activate the filter
/api/objects?filter[available]=true
```
A workaround is of course to change my front end to remove the key when the filter isn't used. What do you think?

**Comment by elightbo** [comment]
I noticed that if you call 

`/api/objects?filter[available]=false`

the filter isn't called at all. Not sure if that's intended. For now I'm formatting my urls like this instead:

`/api/objects?filter[available]=-1`
`/api/objects?filter[available]=1`

**Comment by elightbo** [comment]
Just noticed my issue was https://github.com/spatie/laravel-query-builder/issues/88
