### ISSUE TITLE
[Question] throwing exception when no results found.

### ISSUE THREAD

**Issue by danswiser** [spatie/laravel-query-builder#90]
I have the following code which works perfectly when filtering the collection however it would be really nice to be able to simply throw a model not found exception when there are no results.
```
$users = QueryBuilder::for($model)->query(User::class)
          ->allowedIncludes('department')
          ->allowedFilters('id', 'fname', 'lname', 'uname', 'department_id')
          ->defaultSort('lname')
          ->get();

        return new UserCollection($users);
```
Is there a simple way to throw a `Illuminate\Database\Eloquent\ModelNotFoundException` when no results are found without adding additional code in the controller or extending the QueryBuilder class?

**Comment by robsontenorio** [comment]
If you are building a API, a empty array as json is the best pratice, when requesting collections. 

“Not found” strategy should be for single resources like `/users/99999`
