### ISSUE TITLE
[Feature] Adding extra parameters to filter/sort

### ISSUE THREAD

**Issue by rebaz88** [spatie/laravel-query-builder#94]
In some cases the operator is selected from client. For example, the user wants to list the people who's salary is less than 2500$ or in a different filter request greater than 2500$. So they want to make this operation switch with the client. Would that be possible to add this feature?
something similar to this filter

First request:
['field' => 'salary', 'value' => '2500', 'operator' => 'less than']

Second request;
['field' => 'salary', 'value' => '2500', 'operator' => 'greater than']

**Comment by freekmurze** [comment]
I think you could achieve the desired result by using [a custom filter](https://github.com/spatie/laravel-query-builder#custom-filters). In that filter you could detect the operator given in the request.
