### ISSUE TITLE
%5B and %5D in URLs instead of [ and ]

### ISSUE THREAD

**Issue by drnkwtr** [spatie/laravel-query-builder#949]
Hello, dear community and developers!

Today i met a problem on submitting form. Each filter[any] gone to filter%5Bany%5D. It looks pretty bad as i think, so iirc it can't be fixed in URL, so is there any way to replace ?filter[any] to ?any=123&any_other=1234?

Thanks a lot for your replies, so appreciate.

**Comment by AlexVanderbist** [comment]
Hey @drnkwtr, 

Unfortunately query string parameters are always URL-encoded to ensure that special characters do not interfere with the URL structure. Using the `filter[field]` (nested query string parameter) syntax is totally valid tho and even supported by many front-end and back-end frameworks and packages.

Specifically for this package; if you prefer a different way to define filters in the URL, you can update your configuration by setting `query-builder.parameters.filter` to `null`. This will allow you to use filters like `?foo=bar&baz=value` for the query builder.

Good luck!
