### ISSUE TITLE
Expose a public "isAppended($field)" method on QueryBuilder.

### ISSUE THREAD

**Issue by adaojunior** [spatie/laravel-query-builder#95]
I believe it would be a good solution for cases such as counting a relationship:

```
$builder = QueryBuilder::for(Customer::class);

if($builder->isAppended('orders_count')) {
    $builder->withCount('orders_count');
}
```

You may also consider adding `whenAppended($field)`:

```
$builder->whenAppended('orders_count', function($builder){
    $builder->withCount('orders_count');
})
```

**Comment by AlexVanderbist** [comment]
That `whenAppended` method looks like a pretty neat solution! Feel free to send a PR including tests for this 👍

**Comment by AlexVanderbist** [comment]
We'll continue handling this in the PR 👍
