### ISSUE TITLE
Filtering data with relations

### ISSUE THREAD

**Issue by fariskarcic** [spatie/laravel-query-builder#96]
Hey so I have this issue where I cannot figure out how would I get data.

I'm getting filtered list of users which is connected to roles (many to many/ pivot).
So is there possibility to get role names from some query like this
`$users = QueryBuilder::for(User::class)
            ->allowedIncludes('roles')
            ->allowedFilters('name', 'email', 'date_created', 'is_active')
            ->get();`

**Comment by freekmurze** [comment]
tack on `->with(['roles'])` to your query so the relation is eager loaded. After that, if you set up your relation right, you can can the `roles` as a property on you user model.

**Comment by ronssij** [comment]
Getting some issue with relation filtering.

`QueryBuilder::for(User::class)
                    ->with('gallery')
                    ->allowedIncludes('gallery')
                    ->allowedFilters(Filter::exact('collection', 'gallery.collection_name'))
                    ->get();`

On user Model
`public function gallery ()
    {
        return $this->hasMany(Media::class, 'model_id');
    }`

And still got this

![image](https://user-images.githubusercontent.com/24932380/62015222-213bcf00-b1dc-11e9-9872-8d90ed229d7e.png)

**Comment by AlexVanderbist** [comment]
@ronssij you're missing a `)` in your example. Also, this issue is closed and quite old. Please create a new issue if you still need help :)
