### ISSUE TITLE
Please auto group related record filters of the same type

### ISSUE THREAD

**Issue by ivan006** [spatie/laravel-query-builder#965]
Say a user wants to filter using multiple criteria for related a record of the same type.

E.g.

```
get_records?filter[related_typeA_records.attrX]=valX
&filter[related_typeA_records.attrY]=valY
```

 i cant imagine a case where users intends to not have these criteria grouped. But you guys are not grouping them automatically. This is odd. Let me explain:

this is what you guys interpret the query to mean

get me records where 
- at least one related type A record meets criteria x and 
- at least one related type A record meets criteria y

but the below interpretation would much more useful (grouping) and way more likely to be what the user is trying to achieve 

get me records where 
- at least one related type A record meets
  - criteria x and
  - criteria y

**Comment by AlexVanderbist** [comment]
Hey, this is an interesting idea. Generally, all query builder filters are combined using a logic `AND`. However, like you mentioned, once combined, the various related attribute filters are logical `OR`s. I'm not sure whether we need to add any code to handle this specific edge case (in practice I've created custom filters for these kind of edge cases) but let's continue this discussion in your PR.

**Comment by ivan006** [comment]
what PR? also this isnt a hedge case this is very standard usage. anyway i just made my own library but i would suggest you guys look into this. @AlexVanderbist

**Comment by ivan006** [comment]
also its not a matter of OR/AND its a matter or "HAS child with x AND Y" instead of "HAS child with x AND has child with Y". So its a logical groiping problem not an logical operator problem (AND/OR)
